### ISSUE TITLE
Issue: Letters "m" and "p" stick together

### ISSUE THREAD

**Issue by soviet-man** [IBM/plex#103]
For example:
![default](https://user-images.githubusercontent.com/33825590/33025639-95d7eaf8-ce1f-11e7-83a2-29256c8b9c54.png)

**Comment by fitojb** [comment]
From which rendering environment was that screenshot taken from?

**Comment by soviet-man** [comment]
OS = Manjaro Linux

Editor configuration
Font size = 10
Font weight = bold

System font configuaration
antialias = true
hinting = true
autohint = true
hintstyle = full
rgba = none

**Comment by mjabbink** [comment]
make sure you have TrueType (TT) files and **NOT** OpenType (OT). This will certainly cause this issue.

**Comment by soviet-man** [comment]
Where can I download TTF version?

**Comment by bernaferrari** [comment]
font_you_want/desktop/pc

**Comment by soviet-man** [comment]
The same
![default](https://user-images.githubusercontent.com/33825590/33486682-0acfcbd8-d6bc-11e7-8bf2-58e82ea24691.png)

**Comment by mjabbink** [comment]
https://ibm.github.io/type/

**Comment by mjabbink** [comment]
Is this still happening with the TTF files downloaded from IBM GitHub? Hmmm.

**Comment by mjabbink** [comment]
@BoldMonday

**Comment by soviet-man** [comment]
Yes, downloding from https://ibm.github.io/type/ changes nothing

**Comment by BoldMonday** [comment]
The IBM Plex TrueType fonts have been optimised (hinted) for screen, and for Windows GDI ClearType rasterization in particular. This optimisation ensures that platforms as old as Windows XP will still render the type nice and sharp.

The images shown in this thread are rendered on a different platform (Linux) with a different rasterizer. Therefore we cannot ensure that the type will always render perfectly in different environments.

Also: it appears that the system font settings already applies its own optimisation (autohinting):
```
antialias = true
hinting = true
autohint = true
hintstyle = full
rgba = none
```

**Comment by soviet-man** [comment]
@BoldMonday, yes maybe.
But I am not going to change font configuration in my system for one particular font to look nice while all other applications look like a crap.

**Comment by Vintodrimmer** [comment]
@soviet-man Isn't autohinter discouraged from use anyway?
If I understand correctly, it should provide worse results for most (if not all ) fonts.

So I would consider turning it off even if you don't plan on using Plex.

![img](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-02-15-14%3A47%3A54-screenshot.png)

**Comment by BoldMonday** [comment]
@Vintodrimmer TrueTypes can be – and in the case of IBM Plex are – specifically hinted for screen. OpenTypes cannot do that. Both formats have pros and cons, none of both is superior.

**Comment by soviet-man** [comment]
@Vintodrimmer, what font settings do you recommend? What are the best for rendering?

**Comment by Vintodrimmer** [comment]
@soviet-man It strongly depends on your monitor. What I can invariably recommend is to set the correct DPI in the fontconfig and to turn the autohint off.

Other than that just go through the settings and see what looks the best. Relevant parameters are:

- hinting
- antialiasing
- subpixel geometry
- lcdfilter

In my particular case I use full hinting and default LCD-filter, but once again, best settings are the ones you enjoy on your particular screen.
