### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by gusdaud** [IBM/plex#106]
Is the font available in any CDN ? Or will it be ?

**Comment by seejamescode** [comment]
It is being planned for a major font CDN at the beginning of 2018. In the meantime, cdnjs did add it: https://cdnjs.com/libraries/IBM-type

**Comment by gusdaud** [comment]
Thank you for letting us know!

**Comment by MartinKolarik** [comment]
It's also available at jsDelivr: https://www.jsdelivr.com/package/npm/@ibm/type

**Comment by mjabbink** [comment]
@seejamescode Is this resolved? If so let’s close.

**Comment by seejamescode** [comment]
I would like to keep it open until we get it on Dave’s platform and document that.

**Comment by hmaesta** [comment]
https://github.com/google/fonts/issues/1378

**Comment by davelab6** [comment]
These fonts are now available in fonts.google.com/collection/Plex so this issue can now be closed

**Comment by cpitclaudel** [comment]
One problem with this js package is that is resets the font size of the body {} element to 16px.  Is that a bug?
