### ISSUE TITLE
Provide a variable to modify the font asset path for webpack builds

### ISSUE THREAD

**Issue by seager** [IBM/plex#112]
As described in [Problems with url(...)](https://github.com/webpack-contrib/sass-loader#problems-with-url) the Sass partials hardcode the path to the plex font as for example `../fonts/Mono/web/woff/IBMPlexMono-Regular-Latin3.woff` with the statement `src: url('../fonts/Mono/web/woff2/IBMPlexMono-Regular-Latin3.woff2')`. This relative URL makes building an application which consumes the scss difficult using webpack. 

The url path is a path relative to the root Scss file `src/styles/_fonts.scss`. When building with webpack and the Sass loader, "all linked assets must be relative to the output" which means that the font url should be relative to where the output is built. The intermediate css file that is created by webpack has many url references to load the font using the above relative path. However, the intermediate css file is generally placed in a dist directory where webpack is building the project (the output directory), and the above url does not resolve to the fonts correctly.

The Sass loader page describes two approaches, the far simpler approach is 'Library authors usually provide a variable to modify the asset path' where Plex would provide a `$fonts-path` variable that is defaulted to '../fonts' and the variable is used in the various `src: url` imports. Then projects which consume the scss can override the variable to specify where the fonts actually are.

Using url loader is an option but is difficult to implement.

**Comment by joshblack** [comment]
Hi there! 👋 

You should be able to use `$font-prefix` similar to how it's being done in the webpack example: https://github.com/IBM/type/blob/master/examples/webpack/src/index.scss#L1

Hope that helps!

**Comment by hankthewhale** [comment]
@joshblack this should be documented in the readme for webpack users.

**Comment by joshblack** [comment]
@hankthewhale agreed! The reason it's not there is that there is a hope that we'll have a dedicated CDN for this project which should eliminate the need (hopefully) 😄

**Comment by joshblack** [comment]
@hankthewhale I think documentation for it would totally still be valuable for teams that are deploying in private environments with no external network access btw 😄

**Comment by hankthewhale** [comment]
Very fair point. Okay, I'll document this *eventually.* Hopefully this week.

**Comment by seejamescode** [comment]
Hey y’all, I have added a line and code snippet detailing `$font-prefix`. We did determine the webpack example to be out of scope with the v1.0.0 release. Please contribute to the readme if you believe it could use more content.
