### ISSUE TITLE
ExtraBold and/or Black Weights

### ISSUE THREAD

**Issue by cssobral2013** [IBM/plex#116]
It wouldn't be a bad idea adding ExtraBold and/or Black weights.

**Comment by inferno986return** [comment]
More choice is nearly always a good thing. :-)

**Comment by mjabbink** [comment]
Could be for 2018.

**Comment by mjabbink** [comment]
I mean 2019.

**Comment by ezadoo** [comment]
Any news on this? Is this still planned or was it cancelled?
