### ISSUE TITLE
An emtpy element in tables of MS Word is no longer showing '¤' but '|': 

### ISSUE THREAD

**Issue by SieDa** [IBM/plex#123]
IBM GCUID defines SC01000 (International Currency Symbol) : '¤' 
As text in MS Word is formatted with IBM Plex, the empty table elements are reduced to a '|' instead of showing the '¤'-sign. Alt-0164 (00A4) is not defined in IBM Plex inside the desktop fonts.

**Comment by mjabbink** [comment]
@BoldMonday Is this something we can address by adding that glyph?

**Comment by SieDa** [comment]
I would expect so. You can test with an alternative glyph at that position before designing it.

**Comment by BoldMonday** [comment]
@mjabbink Yes, it will be solved when adding the currency symbol. We will add it for next delivery.

**Comment by seejamescode** [comment]
@BoldMonday was this shipped in our latest release?

**Comment by BoldMonday** [comment]
@seejamescode Not yet. Addition of /currency glyph to all fonts is scheduled for next release.
