### ISSUE TITLE
Will you support TeX / LaTeX Math mode for science 

### ISSUE THREAD

**Issue by SieDa** [IBM/plex#124]
Seeing it work in TeX is a great thing. 
ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/fonts/plex-otf/doc/plex-otf-doc.pdf

Will you provide the math fonts to support TeX or work with tug.org to make that happen? 
For more details see chapters regarding 'math symbols' / Donald Knuth / Modern Typeface 1986-2011.

**Comment by Boshomi** [comment]
There are two ctan packages: 
* [plex-otf](https://ctan.org/pkg/plex-otf)
* [plex](https://ctan.org/pkg/plex)

**Comment by SieDa** [comment]
It is not yet for **math mode**. 
"IBM Plex has no math sym­bols. You have to use one the ex­ist­ing math fonts if you need it."

**Comment by inferno986return** [comment]
"we do not have ≔ and ≝ in the current design. We will design a version of Plex with full mathematical glyphs next year." to quote @mjabbink from https://github.com/IBM/type/issues/122

**Comment by SieDa** [comment]
Why is the ticket closed? 
How do you reflect the plan to "design a version of Plex with full mathematical glyphs", if there is no opfen ticket on that in GitHub?

**Comment by StatisticalProgrammer** [comment]
> 
> 
> Why is the ticket closed?
> How do you reflect the plan to "design a version of Plex with full mathematical glyphs", if there is no open ticket on that in GitHub? 

Please see the open ticket: [#250 "Full Math Symbols?"](https://github.com/IBM/plex/issues/250)
