### ISSUE TITLE
Request: Could you add Powerline glyphs?

### ISSUE THREAD

**Issue by AlmightyScientist** [IBM/plex#125]
**Plex** is my favorite font of the moment, though I would love it so much more with *Powerline* glyps (:

Is that possible? :o

**Comment by squiddle** [comment]
there is https://github.com/sgolovine/PlexNerdfont

**Comment by diroussel** [comment]
@squiddle that repo doesn't exist anymore

I guess one can use https://github.com/sgolovine/nerdfont-patcher to patch plex?
