### ISSUE TITLE
Support for CSS font-variant

### ISSUE THREAD

**Issue by gmosx** [IBM/plex#131]
It would be fantastic if the Plex font supported various CSS font-variant options, e.g.

```
font-variant-numeric
font-variant-caps
```
etc.

More info: [CSS font-variant](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant)

**Comment by BoldMonday** [comment]
Plex already supports a number of OpenType features that should be called when certain options are invoked:
```font-variant-numeric: ordinal;
font-variant-numeric: slashed-zero;
font-variant-numeric: diagonal-fractions;```
Have you tried these?

**Comment by gmosx** [comment]
I wasn't aware of that, I will try it, thanks!
Still, I would love to see support for `tabular-nums`.

**Comment by BoldMonday** [comment]
Not sure I understand your request. Default numbers are already tabular numbers.

**Comment by seejamescode** [comment]
Closing for now since we believe we support this. @gmosx, please provide screenshots and more explanation if we are mistaken.
