### ISSUE TITLE
IBM Plex Sans Bold

### ISSUE THREAD

**Issue by sjclark** [IBM/plex#132]
I'm probably missing something here but how would you reference IBM Plex Sans Bold for usage. I can only locate semibold & italic weights?

**Comment by seejamescode** [comment]
Hey @sjclark, we left out Bold css at the start of this because it was not a part of our typography choices. However, we are separating our typography choices out and giving you that capability in [this pull request](https://github.com/IBM/type/pull/130).

**Comment by seejamescode** [comment]
All weights have been added in v1.0.0!
