### ISSUE TITLE
Build script for GF version

### ISSUE THREAD

**Issue by m4rc1e** [IBM/plex#133]
We'd like to get the ball rolling at GF.

There may be a few metadata tweaks we need to make in order for us host the fonts.

Is it ok for us to write a build script to transform the fonts so they're suitable for us?

if so, I'll file a pr once I'm done

cc @davelab6

**Comment by m4rc1e** [comment]
We need to update the OS/2 fsSelection, head macStyle and nametable entries for the fonts to work correctly on Android.

The font's bbox also extends past the win Ascent and win Descent vals.

cc @davelab6

**Comment by seejamescode** [comment]
Please work off of https://github.com/IBM/type/tree/plex since that is our big refocus on Plex that will be merged this week. You can track the progress at #130.

**Comment by BoldMonday** [comment]
@m4rc1e What are your suggestions to change there? Perhaps we can include them upstream.

(Be aware though that Plex desktop ttf fonts have slightly different settings than their woff/woff2/eot counterparts.)

**Comment by davelab6** [comment]
GF makes its own WOFF/WOFF2/EOT files based on the desktop TTFs offered for
download.

**Comment by m4rc1e** [comment]
@BoldMonday Here's a dump for a family we just released.

| filename                    | fsSelection | macStyle | usWeightClass |
|-----------------------------|-------------|----------|---------------|
| Barlow-Thin.ttf             | bit 6       | 0        | 250           |
| Barlow-ThinItalic.ttf       | bit 1       | bit 1    | 250           |
| Barlow-ExtraLight.ttf       | bit 6       | 0        | 275           |
| Barlow-ExtraLightItalic.ttf | bit 1       | bit 1    | 275           |
| Barlow-Light.ttf            | bit 6       | 0        | 300           |
| Barlow-LightItalic.ttf      | bit 1       | bit 1    | 300           |
| Barlow-Regular.ttf          | bit 6       | 0        | 400           |
| Barlow-Italic.ttf           | bit 1       | bit 1    | 400           |
| Barlow-Medium.ttf           | bit 6       | 0        | 500           |
| Barlow-MediumItalic.ttf     | bit 1       | bit 1    | 500           |
| Barlow-SemiBold.ttf         | bit 6       | 0        | 600           |
| Barlow-SemiBoldItalic.ttf   | bit 1       | bit 1    | 600           |
| Barlow-Bold.ttf             | bit 5       | 1        | 700           |
| Barlow-BoldItalic.ttf       | bit 5+1     | bit 0+1  | 700           |
| Barlow-ExtraBold.ttf        | bit 6       | 0        | 800           |
| Barlow-ExtraBoldItalic.ttf  | bit 1       | bit 1    | 800           |
| Barlow-Black.ttf            | bit 6       | 0        | 900           |
| Barlow-BlackItalic.ttf      | bit 1       | bit 1    | 900           |


https://www.microsoft.com/typography/otspec/os2.htm
https://www.microsoft.com/typography/otspec/head.htm


Also, thank you for your email on the usWeightClass issue. You provided an image showing a Thin's weight class set to 100 showing no ill effects. I'll make up my own test to confirm your findings.


@davelab6 We have FB tests and a naming spreadsheet. How about we write a gf-doc on font naming. We could provide all the settings for each editor etc

**Comment by m4rc1e** [comment]
Just ran all the Sans Roman fonts through win7 IE9. Looks absolutely fine to me.

![desktop_windows_7_ie_9 0_](https://user-images.githubusercontent.com/7525512/36220366-34653240-11b2-11e8-8729-15444a1ee7ba.jpg)

I'll try them out on Win Word tomorrow.

**Comment by davelab6** [comment]
If you modify the usWeightClass to be what we've previously required and
use your diff tool, there should be zero visual diff, right? :)

Writing a gf-doc with screenshots etc for everything would be great :) File
and issue to track that, and as a stretch goal, having extensions for all
those editors that checks these things based on that doc.

**Comment by BoldMonday** [comment]
@m4rc1e Thanks for proving me right on the usWeightClass values in TTF fonts. :)

**Comment by davelab6** [comment]
Thank you for the tip!! :)

**Comment by BoldMonday** [comment]
@m4rc1e @davelab6 The IBM Plex fonts are following the fsSelection and macStyle bits pretty much in a similar manner as in your example above. There is one difference though, which is that in your case you set the fsSelection Regular bit (6) for every roman weight except Bold.

The comments in the official spec at https://www.microsoft.com/typography/otspec/os2.htm#fss for fsSelection state that bit 6 should not necessarily be synched with the macStyle bits.
_“Arial Light would have all bits cleared; it is not the regular version of Arial.”_

So is this really an Android requirement? Because then it is not following the specs correctly.

**Comment by davelab6** [comment]
I think it's not a problem (and an improvement to our checks) if bit 6 is
unset for non regular fonts; the problem I remember was when several styles
had the bold bit set (eg weights 700, 800 & 900, instead of only 700) and I
don't remember problems with regular/light styles. But Marc should test it,
using his screen shot diff tool, to see if it makes a difference.

**Comment by m4rc1e** [comment]
> If you modify the usWeightClass to be what we've previously required and
use your diff tool, there should be zero visual diff, right? :)

I just made a set with the bits set to our liking. Yep, its zero. 

```
Regression Report:

Fonts: ["IBMPlexSans-Bold.ttf", "IBMPlexSans-BoldItalic.ttf", "IBMPlexSans-ExtraLight.ttf", "IBMPlexSans-ExtraLightItalic.ttf", "IBMPlexSans-Italic.ttf", "IBMPlexSans-Light.ttf", "IBMPlexSans-LightItalic.ttf", "IBMPlexSans-Medium.ttf", "IBMPlexSans-MediumItalic.ttf", "IBMPlexSans-Regular.ttf", "IBMPlexSans-SemiBold.ttf", "IBMPlexSans-SemiBoldItalic.ttf", "IBMPlexSans-Thin.ttf", "IBMPlexSans-ThinItalic.ttf"]

View: glyphs-all_16pt
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same
PASSED: Desktop_Windows_7_ie_9.0_.jpg is the same
PASSED: Desktop_Windows_7_chrome_50.0_.jpg is the same
PASSED: Desktop_Windows_10_edge_15.0_.jpg is the same
PASSED: Desktop_Windows_7_firefox_45.0_.jpg is the same
```

I'll try the fonts out on Win  apps later.

**Comment by m4rc1e** [comment]
I just went through past emails and found the fsSelection, macStyle and usWeightClass settings are crucial for the fonts to work correctly in Google Docs. I'll find a way to try and test this.

@graphicore didn't you do several tests to determine these settings for Google Docs?

**Comment by m4rc1e** [comment]
> I think it's not a problem (and an improvement to our checks) if bit 6 is
unset for non regular fonts; the problem I remember was when several styles
had the bold bit set (eg weights 700, 800 & 900, instead of only 700) and I
don't remember problems with regular/light styles. But Marc should test it,
using his screen shot diff tool, to see if it makes a difference.

A large majority of fonts on GF have been built with GlyphsApp. To set the fsSelection in GlyphsApp, you modify the style linking field.

![screen shot 2018-02-15 at 11 07 13](https://user-images.githubusercontent.com/7525512/36253873-d44561de-1240-11e8-8b9b-49e05197ac27.png)

If you don't specify a linked style, Glyphsapp will enable bit 6 (REGULAR) by default. I've also checked Noto. They have enabled bit 6 for all fonts which are not the Bold weight; Light, Medium, etc.

 I'll test whether setting bit 6 for non Regular weights will cause any issues. If it doesn't, I'll refactor the FB test so non Regular weights can be either 0 or bit 6.

**Comment by BoldMonday** [comment]
@m4rc1e Interesting. We don't do any specific post-processing on fsSelection (although I noticed there is a special bit for Condensed!), and the current values are the standard output of the AFDKO.

**Comment by graphicore** [comment]
> @graphicore didn't you do several tests to determine these settings for Google Docs?

Maybe, ff so, I made it on the fly. I can't remember writing library grade code for this.

**Comment by m4rc1e** [comment]
@graphicore thanks

I just went through our collection and checked if any families have set the fsSelection to 0 in the same manner as Plex. There were only two families Roboto Slab and Roboto Mono. 

I just tested Roboto Mono in Google Docs and found no issue

![screen shot 2018-03-07 at 14 52 00](https://user-images.githubusercontent.com/7525512/37099048-5d0b1118-2217-11e8-8213-c5611922e899.png)

In this case, I'm happy for us to proceed.

**Comment by davelab6** [comment]
fsSelection sensitivity is on Docs Android app.

**Comment by m4rc1e** [comment]
LGTM on Android Docs

![screen shot 2018-03-09 at 14 41 40](https://user-images.githubusercontent.com/7525512/37212796-fc12794a-23a7-11e8-89d9-3db51452967b.png)

**Comment by davelab6** [comment]
Then all is well :)

**Comment by BoldMonday** [comment]
Thanks for checking @m4rc1e!
