### ISSUE TITLE
Preview on Windows 10 in PowerPoint 2016 is a mess

### ISSUE THREAD

**Issue by kletkeman** [IBM/plex#139]
![image](https://user-images.githubusercontent.com/3819677/36692496-32639704-1b06-11e8-821a-4942b980fbf7.png)

**Comment by BoldMonday** [comment]
Thanks for the report! Three questions:
1. Have you installed OpenType (otf) or TrueType (ttf) versions of Plex?
2. What version of Windows are you running?
3. Does this happen only in Powerpoint, or also in WordPad?

**Comment by BoldMonday** [comment]
@kletkeman For your info: we have not been able to replicate your problem. Below is an image of Powerpoint 2016 on Windows 10, with latest IBM Plex Sans TrueType fonts installed.
![powerpoint2016-fontmenu](https://user-images.githubusercontent.com/13793769/36834012-aed7a848-1d31-11e8-85ff-201700725996.png)

**Comment by hisnameiskhaya** [comment]
I've got a similar problem. I select Plex in my Master slide and Powerpoint displays Calibri. It's a TTF file.
Works fine in Word, and in Keynote

**Comment by BoldMonday** [comment]
@hisnameiskhaya We have not been able to reproduce this behaviour yet.

Please provide as much details as you can:
What platform, and what version of PowerPoint are you running?
What version of IBM Plex do you have installed?
Does this happen in every PowerPoint document? Or only existing ones, or only new ones?
Please elaborate.

**Comment by KarenK313** [comment]
I have the same issue.

Loaded the full IBM Plex family in to Font Book. Downloaded from Google Fonts. All worked great.

Working on PPT comp using IBM Mono Plex. Worked fine for 2 weeks. I go back into project, and the entire IBM Plex family is missing from the font menu in PPT only. I can use the entire IBM Plex family in all Adobe programs, not PPT. 

I use PPT for Mac version 16.23.

I deleted the entire family from Fontbook and then reloaded entire family, restated laptop and still did not work - same issue. not showing up in PPT program only.

**Comment by KarenK313** [comment]
@BoldMonday 
one more thing to add to my previous post. The entire IBM Plex family downloaded from Google Fonts also does NOT show up in MS word. 
Im using MS Word fro Mac version 16.23

**Comment by BoldMonday** [comment]
@KarenK313 Thank you for the report. Since you are using Adobe apps: is it possible you are using IBM Plex Mono via Adobe Fonts as well?

I recommend to download the IBM Plex fonts from this repository (https://github.com/IBM/plex/releases/latest) and install the TTF fonts on your system.
Could you please check if that solves the issue?

**Comment by KarenK313** [comment]
@BoldMonday 
Thanks for the reply! 
I deleted the IBM fonts from Google in Font Book, restarted my laptop, downloaded the TTF per the link you sent re-opened PPT and the font still does not show up in PPT. I also had a friend try ...and she had the same issue. 
Any other thoughts on this?
I really want to use this font for a brand refresh project and hope we can get this figured out. Thanks!

**Comment by BoldMonday** [comment]
@KarenK313 It is hard to determine what is causing this issue for you. And unfortunately I am not able to reproduce it.
I did a test on the latest MacOS (10.14.4) with Word and PowerPoint 2016 (16.23). As you can see from this screenshot all is working fine here.

**Comment by SteveKimmel** [comment]
I have a similar problem on a Win10 laptop with Powerpoint 2016 and IBM Plex Sans fonts.  With IBM Plex Sans the text is collapsed onto itself and unusable.  This goes away when I change to another font.  The problem appeared within the past month, so May or June of 2019.  No issues with Word.   Thinking I will delete the Plex fonts from my PC.

![powerpoint 2016 with Arial Black font headings](https://user-images.githubusercontent.com/18617628/60358006-fb779c00-9989-11e9-8c57-8be9a5839383.jpg)
![powerpoint 2016 with IBM Plex Sans font headings](https://user-images.githubusercontent.com/18617628/60358008-fb779c00-9989-11e9-8a4a-b8b61a3dab57.jpg)

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
