### ISSUE TITLE
How can I install Plex font on an HTTP server?

### ISSUE THREAD

**Issue by ms2art** [IBM/plex#141]
I need to create an HTML page that uses the Plex font and host it on a server we own. I'm assuming I have to install the font on the server somehow so that it is available to the HTML page, but I don't know the installation process--whether there's an actual installation routine, or if it's a matter of copying certain font files to a specific location on the server.

Thanks for any help.

**Comment by inferno986return** [comment]
Could be there's more to it, but to my understanding it's as easy as:

1. Make a font directory for your website.
2. Place the font files in that directory, you can use ttf, otf or woff.
3. Declare the fonts in the CSS. Plex did have web development code, if it's still around it would be a useful reference.

**Comment by ms2art** [comment]
Can you give an example of "declaring" the fonts? Are you talking about naming a location where the font files can be found, or just saying that specific elements or classes use the Plex font? I think where I'm stumbling is in understanding how the (server? HTML?) knows where the font files are. I'll also look for the web  development code.

**Comment by seejamescode** [comment]
Hi @ms2art, I believe these instructions will help you host your own font files. The CSS you will download assumes that you have maintained it’s folder structure to use the fonts:

1. Download `web.zip` from [this link](https://github.com/IBM/plex/releases/latest)
2. Unzip `web.zip` and drag all of the files into your project’s root directory
3. In your HTML’s `<head>` tag, add the css file reference:
```
<head>
    <link href="./css/ibm-plex.min.css" rel="stylesheet">
    <link href="./yourProjectStyles.css" rel="stylesheet">
</head>
```
4. Then go to your project’s css file (`./yourProjectStyles.css` from above) and add a font-family rule like:
```
* {
  font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;
}
```

The rule above will apply IBM Plex Sans to all elements. If you want to apply a different part of the Plex family, try any of the other font-family rules listed [here](https://github.com/IBM/plex/blob/master/README.md#web-usage).

**Comment by ms2art** [comment]
That worked like a charm! Thanks!
 
----- Original message -----From: James Y Rauhut <notifications@github.com>To: IBM/plex <plex@noreply.github.com>Cc: ms2art <michael_stewart@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [IBM/plex] How can I install Plex font on an HTTP server? (#141)Date: Wed, Mar 7, 2018 11:02 AM 
Hi @ms2art, I believe these instructions will help you host your own font files. The CSS you will download assumes that you have maintained it’s folder structure to use the fonts:
        Download web.zip from this link        Unzip web.zip and drag all of the files into your project’s root directory        In your HTML’s <head> tag, add the css file reference:
<head>    <link href="./css/ibm-plex.min.css" rel="stylesheet">    <link href="./yourProjectStyles.css" rel="stylesheet"></head>
        Then go to your project’s css file (./yourProjectStyles.css from above) and add a font-family rule like:
* {  font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;}
The rule above will apply IBM Plex Sans to all elements. If you want to apply a different part of the Plex family, try any of the other font-family rules listed here.
