### ISSUE TITLE
Include License Description and License url in font name tables

### ISSUE THREAD

**Issue by m4rc1e** [IBM/plex#142]
It would be nice to include the OFL description and url in the name tables.

**License Description (nameID 13)**
This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL

**License Url (nameID 14)**
http://scripts.sil.org/OFL

**Comment by BoldMonday** [comment]
@m4rc1e Are you sure you are looking at the most recent IBM Plex files? Those entries in the name table have been defined.

**Comment by m4rc1e** [comment]
@BoldMonday Thanks! I've pr'd the v2.000 editions to GF
