### ISSUE TITLE
[Cyrillic] Alternates for Bulgarian, Macedonian, & Serbian languages

### ISSUE THREAD

**Issue by cssobral2013** [IBM/plex#143]

**Comment by inferno986return** [comment]
There aren't many typefaces it seems I'm aware of that go for this so I'd like to see IBM Plex support the other Cyrillic letters. 

Stefan Peev has made a good start at this and I'd recommend looking at his work for ideas. For example, look at Linguistics Pro which adds these letterforms to Utopia: https://github.com/StefanPeev/Linguistics-Pro

**Comment by arrowtype** [comment]
A bit of detail is added for this issue in this comment:

https://github.com/arrowtype/recursive/issues/430#issuecomment-754897057

**Comment by moyogo** [comment]
Just a note, the Serbian and Macedonian italic variants are the norm, they are used in the documents defining the orthographies for example. The Serbian and Macedonian roman letter be is not a variant in those documents and may be at the discretion of the font. Some users actually prefer not to have the roman letter be different.

For the Bulgarian variants, there are no normative forms, they may be at the discretion of the font but have become increasingly popular, so it's nice to have them.
For what it's worth the Bulgarian variants can actually be useful as a stylistic set as well, as they  are based on italics which may be useful for non-Bulgarian as well.

**Comment by BoldMonday** [comment]
FWIW -- Bulgarian forms for Cyrillic are being developed currently:

https://github.com/IBM/plex/issues/448#issuecomment-1479232879

**Comment by arrowtype** [comment]
Awesome! I'm sure a lot of people will be excited to use that. Thanks for the update here!
