### ISSUE TITLE
Backlog visibility & release dates

### ISSUE THREAD

**Issue by jbarco** [IBM/plex#147]
It would be extremely useful to know the next release dates and what they going to include. The use of milestones or any other similar mechanism would help the community a lot.

As an example, I would like to know when the font will support Arabic. I don't need a specific date but an idea of when this is going to be available.

**Comment by davelab6** [comment]
@mjabbink said on [twitter](https://twitter.com/mikeabbink/status/975045463245230081), 

> Arabic expected in December. 
> Greek and Hebrew coming up in May.
> Thai in July and Devanagari in October.

**Comment by mjabbink** [comment]
@jbarco 
— Devanagari now first week in November 2018
— Arabic early January2019
— Thai looped April–May 2019
— Korean available in April 2019
