### ISSUE TITLE
Problems with unicode-range

### ISSUE THREAD

**Issue by jlpereira** [IBM/plex#151]
Hi guys, 

There seems to be a problem in how to declare the unicode-range property within @ font-face.

Firefox development console
![captura](https://user-images.githubusercontent.com/16530364/37860269-b3fea516-2f00-11e8-96de-825e15f2ccf5.PNG)

unicode-range should not include '' as how is including now on the sass files, to give an example:

```
@font-face {
  font-family: 'IBM Plex Mono';
  font-style: normal;
  font-weight: 400;
  src: local('IBM Plex Mono'), local('IBMPlexMono'),
    url('#{$font-prefix}/fonts/Mono/web/woff2/IBMPlexMono-Regular-Latin2.woff2')
      format('woff2'),
    url('#{$font-prefix}/fonts/Mono/web/woff/IBMPlexMono-Regular-Latin2.woff')
      format('woff');
  unicode-range: 'U+0100-024F, U+0259, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF, U+FB01-FB02;
}
```

should be:

```
@font-face {
  font-family: 'IBM Plex Mono';
  font-style: normal;
  font-weight: 400;
  src: local('IBM Plex Mono'), local('IBMPlexMono'),
    url('#{$font-prefix}/fonts/Mono/web/woff2/IBMPlexMono-Regular-Latin2.woff2')
      format('woff2'),
    url('#{$font-prefix}/fonts/Mono/web/woff/IBMPlexMono-Regular-Latin2.woff')
      format('woff');
  unicode-range:  U+0100-024F, U+0259, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF, U+2C60-2C7F, U+A720-A7FF, U+FB01-FB02;
}
```

Cheers!

**Comment by mjabbink** [comment]
@boldmonday

**Comment by BoldMonday** [comment]
@mjabbink we did not write the css

**Comment by asudoh** [comment]
@alisonjoseph @vpicone Any ideas...? (My apologies if neither of you are involved in this area) Thanks!

**Comment by vpicone** [comment]
@jlpereira is right, there shouldn't be a quotation mark in unicode-range declarations. But when I generate the sass and subsequent css I don't get that quotation mark. 

Are you using our build script to export the scss? The `createFontFace` tool doesn't include those quotation marks.

**Comment by jlpereira** [comment]
Thanks so much @vpicone @asudoh @mjabbink for take a look of this.
We're are not compilling the scss files, we are importing it using the package(https://www.npmjs.com/package/@ibm/type) with Webpack.

**Comment by jlpereira** [comment]
<img width="1440" alt="Captura de pantalla 2019-03-20 a la(s) 19 31 10" src="https://user-images.githubusercontent.com/16530364/54723588-c7990900-4b46-11e9-823b-725c4bf412df.png">

Here is an image where you can see the scss file. All scss files related with the fonts has the quotation mark
