### ISSUE TITLE
In Mono, regular and bold weights must be width-compatible

### ISSUE THREAD

**Issue by fgcintra** [IBM/plex#153]
Regular and bold weights in Mono variant do not have the same width. This causes misalignment and  prevents a proper usage of both weights on the same context, such as terminals and code editors.

**Comment by BoldMonday** [comment]
All glyphs in all weights of IBM Plex Mono have the same advance width of 600 units.
Please provide visual examples to demonstrate where the fonts do not have the same width.

**Comment by fgcintra** [comment]
Sure, I noticed that the issue was not a Fira Mono fault, but instead a problem related with the application rendering. I am closing this issue.
