### ISSUE TITLE
Old style figures

### ISSUE THREAD

**Issue by tlexcellent** [IBM/plex#154]
Hi. First of all, congratulations and thank you for these beautiful fonts.
I wonder if you plan to release oldstyle figures, at least for Serif & Sans. Tabular lining & oldstyle figures could be useful too.

**Comment by BoldMonday** [comment]
This issue has already been discussed #92.

**Comment by tlexcellent** [comment]
Sorry, i search for «figure», which don’t show results for figures…

**Comment by BoldMonday** [comment]
No problem. Happy to hear you like the fonts!

**Comment by mjabbink** [comment]
maybe for Serif

**Comment by tecosaur** [comment]
I'm not sure whether this is better here or in issue 92, but anway. Regarding this I feel that a quote from The Elements of Typographic Style is Appropriate, both regarding the value of 'old-style' figures, and also the point raised about successful fonts not having them.

#### Elements of Typographic Style v3 ¶ 3.2.1
> In the 1960s, phototypesetting machines with their truncated fonts once again made text figures difficult to find. The better digital foundries now offer a wide selection of fonts with text figures and small caps. These are often sold separately and involve extra expense, but they are essential to good typography. It is better to have one good face with all its parts, including text figures and small caps, than fifty faces without. It is true that text figures are rarely useful in classified ads, but they are useful for setting almost everything else, including good magazine and newspaper copy. They are basic parts of ty- pographic speech, and they are a sign of civilization: a sign that dollars are not really twice as important as ideas, and numbers are not afraid to consort on an equal footing with words. It is also true that a number of excellent text faces, both serifed and unserifed, were originally issued without text figures. Examples include Adrian Frutiger's Mfridien, Eric Gill's Gill Sans, Paul Renner's Futura, Hans Eduard Meier's Syntax, Hermann Zapf's Comenius and Optima, and Gudrun Zapf-von Hesse's Carmina. In several of these cases, text figures were part of the original conception or even the finished design but were scuttled by the foundry. Many such missing components have belatedly been issued in digital form. With any text face that is missing text figures, it is reasonable to enquire whether commercial intimidation or, in effect, commercial censorship may not have played a role.

**Comment by tecosaur** [comment]
@mjabbink I'd be nice to know if you have any comment on that :slightly_smiling_face:

It may be one person's opinion, but I haven't found much fault with Bringhurst's advice yet, and I know I'd value these options.

While some people may misuse them, I imagine most people who go hunting for such features have an inkling of where they are appropriate.
