### ISSUE TITLE
Cyrillic with grave and acute accents?

### ISSUE THREAD

**Issue by boykobb** [IBM/plex#155]
I have found out that currently grave and acute accents (combining marks 0300 and 0301) do not work properly with Cyrillic vowels. Are there plans to cater for this in some near future?

**Comment by BoldMonday** [comment]
It should not be hard to add this.

In what situations are combining grave and acute used in Cyrillic?

**Comment by boykobb** [comment]
Grave and acute are used mostly to disambiguate how a word should be pronounced, especially when a word changes meaning depending on the accent. Common examples are, of course, textbooks, dictionaries, and all kinds of learners' literature. More rarely, any other text. In Bulgarian, there are monosyllabic words that have different meanings with and without a grave, and printing the accent is _required_ by the syntax (not a matter of choice).
Thank you for helping. I am looking forward to seeing grave and acute supported for Cyrillic in this beautiful typeface family.
