### ISSUE TITLE
Small Caps

### ISSUE THREAD

**Issue by type-maniac** [IBM/plex#157]
Do you plan to have small caps? SC are great for emphasizing something within text without "shouting."

**Comment by mjabbink** [comment]
Using a caps wisely is not really shouting. If in messaging yes, if inline with text no. I recommend using them only in Acronyms and names of technology or businesses that are set in caps and do not recommend to highlight words to emphasis within messaging. Using a weight change for that is likely better than caps or even small caps.

It’s not in our plan as I’ve seen little evidence of designers implementing good typography at IBM so adding more opportunity to be heavy handed and messy is not what we want to support. Maybe in a few years. In addition, Helvetica, Syntax, Avenir, Futura, Gil Sans, and Akzidenz Grotesk have all lived a nice long life without small caps (and still going strong). All the modern typography giants like, Müller-Brockmann, Rand, Armin Hoffmann, Crouwel might argue with that statement as well.

**Comment by dbitouze** [comment]
In French typography, it is recommended to displaying centuries ordinals with small caps so too bad Plex doesn't provide them.
