### ISSUE TITLE
Russian pre-1918 Cyrillic

### ISSUE THREAD

**Issue by dmdobrowolski** [IBM/plex#158]
Cyrillic in your fonts is great, however these days most of Cyrillic fonts contain glyphs for letters used in Russian before the revolution of 1917 (and the consequent orthographic reform of 1918), namely
U+0462 Cyrillic capital letter yat
U+0463 Cyrillic small letter yat
U+0472 Cyrillic capital letter fita
U+0473 Cyrillic small letter fita
U+0474 Cyrillic capital letter izhitsa
U+0475 Cyrillic small letter izhitsa

As of now there is only fita (despite the most frequent of these letters was yat).

Bulgarians would also ask for big yus (U+046A — capital, U+046B — small), used in Bulgarian until 1945.

Having all the four letters would be really good for using your fonts in the humanities.

**Comment by mjabbink** [comment]
@BoldMonday

**Comment by BoldMonday** [comment]
@mjabbink I will add these to the list for a future update.

I suggest to add U+017F Latin lowercase long s then too, since it is a similar archaic glyph.

**Comment by AlsoScratch** [comment]
Speaking of the Cyrillic letter Fita, shouldn't it be a wavy line instead of straight?

**Comment by dmdobrowolski** [comment]
@AlsoScratch The middle line in cyrillic Fita (U+0473) has to be wavy, straight line gives you another letter (U+04E9) used in some Turkic languages but not in pre-Bolshevik Russian. The current one IS wrong, unfortunately.

**Comment by AlsoScratch** [comment]
> The middle line in cyrillic Fita (U+0473) has to be wavy, straight line gives you another letter (U+04E9) used in some Turkic languages but not in pre-Bolshevik Russian. The current one IS wrong, unfortunately.

@mjabbink @BoldMonday

**Comment by tay1orjones** [comment]
Hey there! [v6.1.0](https://github.com/IBM/plex/releases/tag/v6.1.0) was just released that references this issue. 

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/468) to provide feedback or voice concerns. Thanks!

**Comment by tay1orjones** [comment]
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!

**Comment by moyogo** [comment]
Regarding the bar of fita or the bar of barred o: https://github.com/notofonts/latin-greek-cyrillic/issues/46

**Comment by BoldMonday** [comment]
**Plex Serif v3.0**

<img width="687" alt="image" src="https://github.com/IBM/plex/assets/13793769/437e94c9-b1c7-4811-8847-e9e1b695747b">

**Comment by BoldMonday** [comment]
**Plex Sans v3.4**

<img width="669" alt="image" src="https://github.com/IBM/plex/assets/13793769/caf8b6dd-3207-4244-a8b1-90554cf263b2">
