### ISSUE TITLE
Powerpoint 2016 on PC mangles quotes, curly braces and brackets

### ISSUE THREAD

**Issue by arbydev** [IBM/plex#159]
Font - IBM Plex Sans Light

Using OTF version of fonts. 
Windows 10 machine
Does not occur in Microsoft Word
Does not occur in Wordpad.

![image](https://user-images.githubusercontent.com/23506871/38391618-5aab7b76-38ea-11e8-885d-898398484032.png)

**Comment by BoldMonday** [comment]
Thanks for the detailed report. It appears PowerPoint 2016 is misinterpreting kerning.
In general: TrueType is the recommended format for use on Windows.

Could you please check the following:
- Are these the latest OTF versions from this repository?
- Does the same behaviour occur with the TTF version of the fonts?

Thanks.

**Comment by BoldMonday** [comment]
For the record: testing the latest OTF versions in an earlier version of PowerPoint (2013) shows no problems with kerning for the combinations in question.

<img width="980" alt="windows8" src="https://user-images.githubusercontent.com/13793769/39423441-3f83d1f4-4c72-11e8-94ac-0d8d1758d769.png">

Still we recommend to use TrueType versions on Windows, and in particular when using Office.
