### ISSUE TITLE
Add documentation about missing OpenType features in webfonts

### ISSUE THREAD

**Issue by phortuin** [IBM/plex#162]
It seems stylistic alternates (I use `ss01` and `ss02` for single storey a and g) are not included in the Latin1 subset of (at least) IBM Plex Sans and IBM Plex Mono. I haven’t tested other subsets as found in the `split` folder of this repo, nor the Condensed & Serif versions of IBM Plex. 

Please fix this; it’s an excellent service to developers to provide these "split" versions, but a drag that I now have to load the full character set just for these stylistic alternates.

If there is a technical reason, I would recommend some additional notes explaining this in the README.

(Additionally, it seems using italic swaps out the single storey 'a' with a double storey 'a', whereas the 'g' stays the same as non-italic. Not sure if that is by choice?)

Thanks.

**Comment by BoldMonday** [comment]
Currently the split webfonts are completely targeted at having the smallest file size. This means that all OpenType features are removed from them.

Even if we would allow `ss01` and `ss02` features to remain in the fonts, then these will only work for the accented versions of /a and /g in the Latin-1 fonts. They will not work for other accented versions of those letters. This might create more confusion for people that use Latin-2 or Vietnamese.

A about this note in the README is a good suggestion.

The different behaviour in italics is a deliberate choice btw.

**Comment by BoldMonday** [comment]
@seejamescode:
> Please note that split font files do not have any OpenType features.
