### ISSUE TITLE
Rendering question

### ISSUE THREAD

**Issue by Vintodrimmer** [IBM/plex#163]
Good day,

This is more of a question than an issue. Which of the two examples has the correct rendering?'
Left one uses `fontconfig` with my native 211DPI, while the right one is GTK+ with standard 96DPI.

![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-04-22-13%3A01%3A08-screenshot.png)

More specifically, you can see that on the left "I" and "l" are of the same height, while on the right "I" is shorter than "l". Which way was it intended?

**Comment by BoldMonday** [comment]
Have a look at the fonts in a big size and you will see how the heights of capitals and ascenders are intended. Then you will see that these dimensions do differ.

Due to rounding of pixels in small sizes they can be rendered at a similar height sometimes.

**Comment by Vintodrimmer** [comment]
Thank you.
