### ISSUE TITLE
Small letter "i" is override

### ISSUE THREAD

**Issue by HARIPRASADHARI** [IBM/plex#164]
Please check the screenshot
![letter_i](https://user-images.githubusercontent.com/10670604/39303752-fcbf8b6a-4974-11e8-861f-48033b394d9c.png)

**Comment by BoldMonday** [comment]
Please elaborate what the issue is. It is not clear from the screenshot nor the subject.

**Comment by HARIPRASADHARI** [comment]
Check the letters "f" and "i" is collapsed in the word profile.
That dev toolbar shows: am using IBM plex google font link.

**Comment by BoldMonday** [comment]
That is a common Latin `fi` ligature. It is a typographical refinement.

**Comment by HARIPRASADHARI** [comment]
is there any solution?

**Comment by seejamescode** [comment]
You can wrap the two letters in a `<span>fi</span>` and then increase `letter-spacing` on the span. However, since this is the intended outcome we will close the issue.

**Comment by BoldMonday** [comment]
There are ways to disable ligatures in css. But I am not a css expert.
