### ISSUE TITLE
Plex Hebrew letters צ and א

### ISSUE THREAD

**Issue by DanaFisher** [IBM/plex#165]
Examining the new Plex Hebrew font raised up a few concerns. The first alphabet letter in Hebrew **א** is a very important letter that sums up the design of the whole language. In the version we got (beta) the letter looks to hard, almost like an X, the same issue is occurs again with the letter **צ** .
Here is a screen shot with, what I believe is the problem.

![alef and tzade](https://user-images.githubusercontent.com/38466170/39474938-e3d249e2-4d5e-11e8-85d4-8b6979234a85.png)

**Comment by BoldMonday** [comment]
IBM Plex Hebrew has been designed in collaboration with a native Israelean type designer, Yanek Iontef. The detailing of glyphs, and in particular where to apply corners, has been tried, tested, and discussed numerous times over the last few months. A similar effect can be observed in Latin letters such as `f` and `t`, especially in lighter weights.

The typeface’s overall characteristic are explained in great detail in the section “Plexness” on the Plex website:
https://www.ibm.com/plex/plexness/

**Comment by DanaFisher** [comment]
I'm familiar with the collaboration details, yet these issues were raised within our design team and was looking for the right platform to ask for answers.
Adding a comparison with the **צ** and the **y** as you suggested, the **y** is softer, and therefor better.

![image](https://user-images.githubusercontent.com/38466170/39478157-43cfb932-4d6a-11e8-9795-d4249af2f692.png)

**Comment by mjabbink** [comment]
@DanaFisher The **y** is not softer in the radius. They are the same. 

I see no reason for concern. The detail you’re identifying is a distinct feature of Plex and carries much of the conceptual thinking that defines what I call Plexness. The "hardness" you point out is very purposeful and found across all the scripts and is derived from the logotype. I think it’s an excellent place for the translation of this distinct detail from Latin to Hebrew. It’s also not a legibility problem nor do I think it compromises the authenticity of the script in modern Hebrew.

**Comment by mjabbink** [comment]
<img width="949" alt="screen shot 2018-05-01 at 10 29 42 pm" src="https://user-images.githubusercontent.com/32881239/39503618-e7850288-4d94-11e8-97c3-99050c1945b9.png">

**Comment by mjabbink** [comment]
<img width="606" alt="screen shot 2018-05-01 at 10 58 53 pm" src="https://user-images.githubusercontent.com/32881239/39503621-f0be0afc-4d94-11e8-84a1-451a7d69fb9c.png">

**Comment by mjabbink** [comment]
<img width="1286" alt="screen shot 2018-05-01 at 10 59 13 pm" src="https://user-images.githubusercontent.com/32881239/39503646-028f6546-4d95-11e8-8f67-2ef539f48518.png">

**Comment by mjabbink** [comment]
<img width="601" alt="screen shot 2018-05-01 at 10 18 30 pm" src="https://user-images.githubusercontent.com/32881239/39504081-55214d90-4d97-11e8-8223-e9bd92975fbb.png">
<img width="599" alt="screen shot 2018-05-01 at 11 12 13 pm" src="https://user-images.githubusercontent.com/32881239/39504087-5fdb4a38-4d97-11e8-9d3e-e97b9ee38966.png">

**Comment by DanaFisher** [comment]
@mjabbink thank you for taking the time to answer and to elaborate on this matter.
Just to clarify, I have the utter most respect for Yanek and his legacy, as he is one of Israel's typography gurus. I am honoured to be able to discuss his work.
I understand your comments and examples, and appreciate the opportunity to have an interesting discussion regarding typography design and conceptual thinking.

**Comment by mjabbink** [comment]
@DanaFisher You can discuss with him in person May 23rd. I’m sure he’ll be happy to chat and answer questions. I wish I was going too!

**Comment by davelab6** [comment]
What's happening May 23rd :)

**Comment by DanaFisher** [comment]
@mjabbink thank you, I'll definitely do that, very exiting :)

@davelab6 we're introducing the new IBM Plex Hebrew at a meet up in our offices in Tel Aviv and Yanek Iontef will come and speak about the design process.
