### ISSUE TITLE
Give permission to add to Google Docs (and Sheets, Slides...)

### ISSUE THREAD

**Issue by inferno986return** [IBM/plex#169]
I am pleased to see IBM Plex has been added to Google Fonts. However I would like to use the fonts in documents I make on Google Drive. Is there anything you can do to make it possible?

**Comment by davelab6** [comment]
Docs has permission, I just need to make it happen =)

**Comment by inferno986return** [comment]
I look forward to it and who knows it may even assist an IBM employee. Either way, more options is a good thing overall. :-D

**Comment by JoolianGarcia** [comment]
+1

**Comment by seejamescode** [comment]
I used IBM Plex Sans in Google Sheets today.

**Comment by davelab6** [comment]
The extensis Google Docs font plugin is a workaround

**Comment by inferno986return** [comment]
I don't know who did it, but thanks for enabling them on Google Docs/Sheets/Slides. :-D
