### ISSUE TITLE
Alternate glyph for lowercase l (U+006C)

### ISSUE THREAD

**Issue by fooness** [IBM/plex#175]
I’d like to ask if there’s general interest in an alternate glyph for the lowercase `l` (U+006C) which is rounded at the bottom to distinguish it better from the figure `1` …

If there’s just the `l` in e.g. a short URL, some hash, or other thing you maybe have to type in manually from e.g. some piece of paper, then people tend to be unsure about if the `l` is an `l` or a `1` … would love to see this happening.

![screen shot 2018-05-09 at 17 05 42](https://user-images.githubusercontent.com/11408027/39822591-3ecabf6c-53ab-11e8-82fc-b8c416887aa5.png)

![screen shot 2018-05-09 at 17 03 08](https://user-images.githubusercontent.com/11408027/39822571-32064968-53ab-11e8-92f9-fae204598077.png)

**Comment by inferno986return** [comment]
IBM Plex Sans' "l" has a tail too, so it should fit in with the style.

**Comment by mjabbink** [comment]
@BoldMonday let’s look at the older versions again.
