### ISSUE TITLE
NPM @ibm/plex module contains too many files

### ISSUE THREAD

**Issue by akx** [IBM/plex#177]
The [@ibm/plex](https://www.npmjs.com/package/@ibm/plex) NPM package, at least as of version 1.0.2, also contains the FontLab master files as well as the production scripts for them, which is probably not the intention. This also makes the package clock in at a pret-ty hefty 185 MB.

```
$ yarn add @ibm/plex
$ find node_modules/@ibm/plex -type f | grep ufo | wc -l
   19218
$ du -hs node_modules/@ibm/plex
185M	node_modules/@ibm/plex
```

Removing those files leaves the package at a much more sensible 36 MB.

```
$ du -hs node_modules/@ibm/plex
 36M	node_modules/@ibm/plex
```

This is easily resolved with an [`.npmignore` file](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

**Comment by akx** [comment]
This is still an issue with `1.2.3`, and the package keeps on growing.

```
$ yarn add @ibm/plex
└─ @ibm/plex@1.2.3
$ du -hs node_modules/@ibm/plex
261M	node_modules/@ibm/plex
```

**Comment by vpicone** [comment]
@akx Definitely agree about the dev deps (#233). However, this repo is also meant as a resource for typeface developers. To that end, I believe leaving the master files in was intended.

**Comment by BoldMonday** [comment]
From a typeface developer’s point of view I would never use NPM as a way to get source files, and before this project I never even heard of it.

People in the typeface developers world are mostly using Git, Python (pip) and Homebrew. JavaScript is pretty much non-existent.

**Comment by vpicone** [comment]
@BoldMonday In that case, it seems like we'd only want to publish files that would be used in a javascript project (like @akx suggested).

**Comment by AnthumChris** [comment]
@mjabbink Please re-open and consider refactoring this package to only include the needed files for a web app? It feels unnecessary large and @BoldMonday is correct in saying that typeface designers to not use NPM.  Source files could be downloaded from IBM's official Plex websites:

- https://www.ibm.com/plex/
- https://github.com/IBM/plex/releases/tag/v1.3.0

It's a great font and we can encourage the developer community to use it if it's well-packaged and minimally distributed for web apps built with NPM.

**Comment by joshblack** [comment]
Added a quick PR over in: https://github.com/IBM/plex/pull/240 that should cover most of the size. Moved `dependencies` over into `devDependencies` alongside adding `**/sources/**` to `.npmignore` which was the biggest source of size when it comes to fonts 👍
