### ISSUE TITLE
Add support for IPA extensions and provide fonts with glyph variants

### ISSUE THREAD

**Issue by ghost** [IBM/plex#180]
If it is possible, I would prefer it if you were able to include IPA extensions to the typeface. [On the website about this typeface](https://www.ibm.com/plex/), I've read that this typeface is going to receive support for writing systems such as Greek, Arabic and Hebrew (which would give it around the same coverage as certain proprietary typefaces such as Arial, and a greater coverage compared to Roboto, the latter only covering Latin, Greek, Cyrillic and Vietnamese), but Arial already has support for IPA extensions, and this hasn't been planned for this typeface. 

Lato also offers the same coverage as Arial minus Hebrew and Arabic, but Lato has issues such as near-identical "I" and "l", and incorrectly rendered glyphs such as "ę". Noto Sans has an issue rendering the Cyrillic glyph "і" on some systems, where the tittle is absent.

I would also prefer it if it were possible to access variants of glyphs for offline use, as in the [Iosevka typeface](https://github.com/be5invis/Iosevka/blob/master/README.md) - that typeface offers various downloadable stylistic variants and allows the user to be able to build their own variants, for both offline and online use.

**Comment by mjabbink** [comment]
The IPA Unicode range would interesting to add. We can explore this when get to the Plex Math font project this year
