### ISSUE TITLE
IBMPlexSansHebrew-ThinItalic.woff missing from 1.1.0 deliverable

### ISSUE THREAD

**Issue by ronanmulvaney** [IBM/plex#183]
Your @ibm/plex/scss/sans-hebrew/thin/italic/_index.scss refers to
```
    url('#{$font-prefix}/IBM-Plex-Sans-Hebrew/fonts/complete/woff/IBMPlexSansHebrew-ThinItalic.woff') format('woff');
```
![image](https://user-images.githubusercontent.com/29900991/43447389-4ff3a036-94a3-11e8-855a-87e2adcea2ca.png)

This file does not seem to exist in your deliverable and causes issues processing the css through an import of `@import "@ibm/plex/scss/ibm-plex";`

**Comment by BoldMonday** [comment]
This is an error in the css. IBM Plex Sans Hebrew does not contain any italic styles on purpose.

**Comment by ronanmulvaney** [comment]
By that you mean the automated scss creation in https://github.com/IBM/plex/blob/master/scripts/export-scss.js just in case I am picking you up incorrectly and it is how I am consuming the scss.

**Comment by alisonjoseph** [comment]
Taking a look at this now 👀

**Comment by alisonjoseph** [comment]
@joshblack any insight here on why the script is generating this if the files don't exist?

**Comment by alisonjoseph** [comment]
I'm going to manually update the scss/css files and release, but the script will need to get updated at some point to be smarter and not generate css for font weights that don't exist.

**Comment by alisonjoseph** [comment]
@ronanmulvaney this should be fixed in `v1.1.2` Please reopen the issue if you are still seeing references to italic hebrew anywhere. Thanks!

**Comment by ronanmulvaney** [comment]
@alisonjoseph Don't have the privileges to reopen but not seeing any change in 1.1.2 and am still getting an error on ```Can't resolve '@ibm/plex/IBM-Plex-Sans-Hebrew/fonts/complete/woff/IBMPlexSansHebrew-ThinItalic.woff' ```

**Comment by alisonjoseph** [comment]
Hi @ronanmulvaney, so sorry about that, I manually removed them and didn't realize the publish script re-ran the script to generate the files. Try `1.1.3` when you have a chance, I installed it locally and I believe the references to Hebrew Italic are now removed.

**Comment by ronanmulvaney** [comment]
Can confirm resolution at my end. Thanks for the quick turnaround.

**Comment by mjabbink** [comment]
Thanks Alison!
