### ISSUE TITLE
Bugs in Hebrew Nikud (diacritics) positioning.

### ISSUE THREAD

**Issue by chneora** [IBM/plex#185]
When using with a dagesh or a shin/sin dot. the nikud move away.

Also, why the alternative ayin can’t be used via opentype stylistic set (only via the glyphs panel)?

![untitled](https://user-images.githubusercontent.com/26043856/43472275-5918d1be-94ed-11e8-8538-9f75690db5b9.png)

**Comment by mjabbink** [comment]
@BoldMonday This was corrected already in the last update right?
