### ISSUE TITLE
Families.js generates scss for font weights that don't exist

### ISSUE THREAD

**Issue by alisonjoseph** [IBM/plex#186]
families.js currently assumes all fonts have all weights, which is not the case. Needs to be updated to only generate scss/css for the font weights that exist. 

Related to: https://github.com/IBM/plex/issues/183

**Comment by mjabbink** [comment]
All fonts have 8 weights.

**Comment by alisonjoseph** [comment]
We should leave open for now, @joshblack is going to help to fix the script to generate the correct files. It may also make sense to keep this repo to only hold the fonts, and move the sass file generation to the elements repo.

**Comment by sockol** [comment]
Kind of resolved on the most version - it will still generate the italic folders for non-english languages, but it will not import them. So it's usable for now
