### ISSUE TITLE
"IBM Plex Serif" defaults to generic serif in IE 11.0.9600.19080

### ISSUE THREAD

**Issue by roycehart** [IBM/plex#189]
"IBM Plex Serif" displays correctly in Firefox and Chrome, but defaults to generic serif font when viewed in IE 11.0.9600.19080. 

Please view [https://roycehart.com/demo/font-error/](https://roycehart.com/demo/font-error) and screen captures therein for details.

WOFF2 files are hosted on the server and referenced in the CSS.

**Comment by seejamescode** [comment]
Hi @roycehart, thanks for submitting an issue! The problem is that IE [does not support woff2 files](https://caniuse.com/#feat=woff2). You will also have to include woff font-face declarations before the woff2 declarations as seen in our CSS: https://unpkg.com/@ibm/plex@latest/css/ibm-plex.css
