### ISSUE TITLE
German umlauts are not displayed correctly in Chrome

### ISSUE THREAD

**Issue by asudoh** [IBM/plex#191]
@andreas-schmitt-mi commented on [Thu Aug 09 2018](https://github.com/IBM/carbon-components/issues/1022)

## Detailed description

On Chrome version 68 German umlaut characters (ÄÜÖ) are not displayed correctly in text input fields, if they are entered in uppercase. E.g. "Äpfel" is displayed as "Apfel". If I do the same in Firefox 52.9 it works fine and umlauts are displayed correctly. This might be related to the font-family. If I change font-family from "ibm-plex-sans" to Arial, the umlauts are displayed correctly in Chrome, too.

> Is this issue related to a specific component?
- I have noticed it in Text Input and Search component, maybe other components are affected as well.

> What did you expect to happen? What happened instead? What would you like to see changed?
- Umlaut characters in uppercase should be displayed correctly.

> What browser are you working in?
- Chrome 68

> What version of the Carbon Design System are you using?
- 9.6.4

## Steps to reproduce the issue

1. Open Google Chrome 
2. In a carbon components text input field enter "Äpfel" or "ÄÖÜ" e.g. on carbon components demo page [Text input](http://www.carbondesignsystem.com/components/text-input/code)
3. Instead of "Äpfel" the text input displays "Apfel"

## Additional information

- On Chrome 68
![capture](https://user-images.githubusercontent.com/42237709/43894470-66bd5394-9bd2-11e8-8307-8d6ca44188f9.JPG)

- On Firefox 52.9
![capture](https://user-images.githubusercontent.com/42237709/43894524-8a93255a-9bd2-11e8-9b77-324673243926.JPG)

---

@asudoh commented on [Mon Aug 13 2018](https://github.com/IBM/carbon-components/issues/1022#issuecomment-412422775)

Got a reduced case without Carbon:
[umlaut.zip](https://github.com/IBM/carbon-components/files/2281953/umlaut.zip)

This problem seems to reproduce only with Windows (I used Windows7, not sure about Windows10). Adding a border there shows an interesting thing - The accent goes on the border. So it's behaving as though the glyph is crippled.

Not sure if the issue comes from the Plex font, or browser/OS, but given we can reproduce the problem without Carbon, moving this issue to Plex so that Plex folks can take a look at.

**Comment by BoldMonday** [comment]
I had a look at the issue, and ran the same check on Chrome, Firefox and IE11 on Windows 7. In all browsers the accents rendered fine except for Chrome. It appears that the latter is treating text boxes differently and is clipping text at the top of a text box. A margin is required to compensate for this effect.

The vertical metrics settings in the IBM Plex fonts are based on [guidelines by the Googlefonts team](https://github.com/googlefonts/gf-docs/blob/master/VerticalMetrics.md). In that respect there is not much we can do, I’m afraid.

**Comment by andreas-schmitt-mi** [comment]
Thank you very much for looking into this issue. Do you think it is a bug in Chrome or that the guidelines for the vertical metrics may need to be adjusted? I noticed that if I change the font to "Arial" or "Times New Roman" for example, I can see the umlauts correctly in Chrome. Not sure if these fonts are using different vertical metrics settings.

**Comment by BoldMonday** [comment]
As far as I’m concerned it is a bug in Chrome. The clipping does not need to happen because there is plenty of space above the input text box. And other browsers are rendering the type fine.

Arial and Times New Roman use different vertical metrics settings than described in the Googlefonts guidelines. But they are also drawn on a different body height.

**Comment by BoldMonday** [comment]
@moyogo Setting for hhea metrics only concerns MacOS and there is a reason why we set them differently there. For OS/2 Win and OS/2 Typo values we follow the recommendations from Googlefonts and they recommend setting the fsSelection USE_TYPO_METRICS bit.

**Comment by moyogo** [comment]
@BoldMonday The fact that the OS/2 typo metrics haven’t been changed to match the hhea metrics is the issue. The Google Fonts Vertical Metrics document has the following recommendation "[7. Hhea and Typo metrics should match](https://github.com/googlefonts/gf-docs/blob/master/VerticalMetrics.md#7-hhea-and-typo-metrics-should-match)".

The current values in the woff and woff2 are:
- hhea.ascent=1025
- hhea.descent=-275
- hhea.linegap = 0
- OS2.typoAscender=780
- OS2.typoDescender=-220
- OS2.typoLineGap=0
- OS2.USE_TYPO_METRICS is set

That means that the hhea lineheight is 1300 while the typo lineheight is 1000.

This creates 2 issues:
1. The lineheight will be 30% larger on in apps that read the hhea metrics than on apps that read the OS2.typo metrics.
2. The apps that use hhea.ascent=1025 to start printing the line will start further from the baseline than the apps that use the OS2.typoAscender=780 (hhea.linegap and OS2.typoLineGap are both 0 so the don’t factor in). Some apps reading OS2.typoAscender will print what is above 780 while others will cut-off what is above 780 (as Chrome on Windows does, or even Firefox as shown below).

See the results of a test where the typo metrics are set to match the hhea metrics (typoAscender=1025, typoDescender=-220, typoLineGap=0), in `div`, `input` and `textarea`  in IE 11, Edge, Chrome and Firefox on Windows:
![ie-edge-chrome-firefox_on_win10](https://user-images.githubusercontent.com/1923747/44206581-4150ba80-a152-11e8-87d3-26213e233196.png)
and in Safari, Chrome and Firefox on macOS:
![safari-chrome-firefox_on_macosx](https://user-images.githubusercontent.com/1923747/44206583-41e95100-a152-11e8-8f96-98a500fef3ef.png)
Notice the inconsitent lineheight and distance to the first baseline with the current woff, and the difference after the typo metrics have been changed to match the hhea metrics.

@m4rc1e, @davelab6 can you confirm this is what Google Fonts expect?

**Comment by m4rc1e** [comment]
@moyogo Thank you for the analysis. You are correct, we want the hhea and typo to be the same (at least they should sum up to the same vals).

At GF, We added the ttf fonts, https://github.com/IBM/plex/tree/master/IBM-Plex-Sans/fonts/complete/ttf (still using an old version). For these fonts, the hhea and typo both summed equally to 1300. We haven't updated to the latest version yet but I can see they haven't regressed.

Here's a [jsbin](https://jsbin.com/rapoxejuso/edit?html,output) which uses the GF version. On my OS X, Chrome 68, it looks fine.

![screen shot 2018-08-16 at 13 09 54](https://user-images.githubusercontent.com/7525512/44207619-e8832100-a155-11e8-9301-7b505092e9a6.png)

**Comment by BoldMonday** [comment]
@moyogo I get your point, and thank you for the extensive comparisons. And the best solution will probably be to synchronise typo / hhea values and specify 0 for line gaps.

But @m4rc1e I am curious, because [the Googlefonts recommendation](https://github.com/googlefonts/gf-docs/blob/master/VerticalMetrics.md) specifies the following:
```
Typo Ascender = either Cap Height or Ascender height, whichever is tallest
Typo Descender = Typo Ascender - UPM
Typo LineGap = 0.25 * UPM
```
If we follow this scheme for Plex then we will get the following values:
```
Typo Ascender = 780
Typo Descender = -220
Typo LineGap = 250
```
These are the same values as we have now except for TypoLineGap. If we apply these settings then the umlauts will still be clipped in Chrome, because it appears to clips everything higher than 780. Although winAscent correctly specifies the clipping zone at 1025.

To me it appears that the recommendation `Typo Ascender + Typo Descender = upm` does not work for any font that has anything beyond ascender height. I guess a better recommendation would be `Typo Ascender = winAscent, Typo Descender = winDescent, Typo LineGap = 0`.
