### ISSUE TITLE
Character "ghosting" issues

### ISSUE THREAD

**Issue by brancenwright** [IBM/plex#193]
Viewing PDFs at 100% or lower seems to cause a ghosting/fading affect on certain characters. IE. the "a", bottom of the "g", "n" and the "i" (the dot appears misaligned
[ibm-cloud-video-content-delivery-network-with-multicast_ds.pdf](https://github.com/IBM/plex/files/2288705/ibm-cloud-video-content-delivery-network-with-multicast_ds.pdf)
).

**Comment by twardoch** [comment]
Viewing PDF where? (Which app and OS?)
Did you use the OTF or the TTF fonts?

**Comment by BoldMonday** [comment]
This sounds like an issue that we fixed recently.

Please use the latest fonts from the repository and report back if the issue still persists, together with screenshots.
