### ISSUE TITLE
NPM only showing single license still

### ISSUE THREAD

**Issue by ethangeyer** [IBM/plex#195]
Hey guys - thanks for adding the Apache License and publishing an update. NPM only seems to be picking up the single OFL license though. 

Looks like that's all that's [specified here](https://github.com/IBM/plex/blob/master/package.json#L6):
```
{
  "name": "@ibm/plex",
  "description": "The package of IBM’s typeface, IBM Plex",
  "version": "1.1.4",
  "repository": "https://github.com/ibm/plex.git",
  "license": "OFL-1.1",
... 
```

And NPM has a [special syntax](https://docs.npmjs.com/files/package.json#license) for multiple licenses:
![image](https://user-images.githubusercontent.com/6808465/44408448-65cfdc80-a52e-11e8-8441-f4cfd6ba6df9.png)

**Comment by ethangeyer** [comment]
☝️ @alisonjoseph @joshblack

**Comment by alisonjoseph** [comment]
FYI we are actually removing the Apache license per a request from IBM legal.

**Comment by ronanmulvaney** [comment]
Just to mention that on npm; 1.1.4 is published as the "latest" so 1.1.5 may not be getting the distribution to consumers that you want.

**Comment by alisonjoseph** [comment]
Thanks @ronanmulvaney, I'll look in to this and make sure 1.1.5 is on npm

**Comment by ronanmulvaney** [comment]
:-( @alisonjoseph has regressed #183 by the looks of it
```
Module not found: Error: Can't resolve '@ibm/plex/IBM-Plex-Sans-Hebrew/fonts/complete/woff/IBMPlexSansHebrew-ThinItalic.woff' in ....
```

**Comment by alisonjoseph** [comment]
Will take a look

**Comment by ronanmulvaney** [comment]
Confirmed.
