### ISSUE TITLE
Preferred format: TTF or OTF? (Debian/Ubuntu distribution)

### ISSUE THREAD

**Issue by paride** [IBM/plex#198]
While working at the Debian package for Plex, I'm wondering if I should distribute the TTF or the OTF format. Given that both formats are fully supported, which one has to be preferred? OpenType should be technically superior, but according to your `README.md` it seems that you first generate the TTF files and then convert them to OTF using `makeotf`. Also, the WOFF/WOFF2 fonts appear to contain TrueType fonts. Is therefore the TTF version the nearest to the original design? Is there any reason to chose OpenType over it?

(Packaging both the formats in separate packages is an option, but I would like to have a justification for it.)

**Comment by BoldMonday** [comment]
TrueType (TTF) is probably preferred over PostScript (OTF), but I recommend to do a thorough test with both formats.

The IBM Plex TrueType fonts have been optimised for Windows ClearType rendering, which might also be beneficial to Debian. But please run some tests with text in small sizes under different types of rendering (sub-pixel anti-aliasing versus grayscale anti-aliasing for example) to examine what renders better.

Please report your findings here so we can share the insight.

**Comment by cmfwyp** [comment]
![ttf](https://user-images.githubusercontent.com/20808761/44739135-f8d7bc00-aac4-11e8-8917-68dc1ff91a07.png)
![otf](https://user-images.githubusercontent.com/20808761/44739133-f8d7bc00-aac4-11e8-8c07-8986815c23e7.png)
![ttf forced autohinting](https://user-images.githubusercontent.com/20808761/44739136-f8d7bc00-aac4-11e8-9469-d599390b7043.png)
![otf forced autohinting](https://user-images.githubusercontent.com/20808761/44739134-f8d7bc00-aac4-11e8-82e8-2e2c54ddabf3.png)
![serif italic ttf](https://user-images.githubusercontent.com/20808761/44739586-2d984300-aac6-11e8-9104-a1804ed0bb28.png)
![serif italic otf](https://user-images.githubusercontent.com/20808761/44739585-2cffac80-aac6-11e8-9841-1a8d60fe4b06.png)
TTF at 14 ppem:
![browser ttf](https://user-images.githubusercontent.com/20808761/44740906-9a610c80-aac9-11e8-8f91-c918f5d5a5ad.png)
OTF at 14 ppem:
![browser otf](https://user-images.githubusercontent.com/20808761/44740905-9a610c80-aac9-11e8-9691-853301dbe218.png)

If desired, you can force autohinting with fontconfig:

```xml
<match target="font">
	<test name="family" mode="contains">
		<string>IBM Plex</string>
	</test>
	<edit name="autohint" mode="prepend_first">
		<bool>true</bool>
	</edit>
</match>
```

**Comment by atheistray** [comment]
I noticed one small difference, small but important when it comes to legibility. Look at the two screenshots of the wiki page. Look at the caption below the picture and you will see the letter 'a' is different in two screenshots. The OTF one is more legible.

**Comment by twardoch** [comment]
Also: both OTF and TTF fonts are OpenType. OTF are PostScript-flavored OpenType fonts and TTF are TrueType-flavored OpenType fonts. Neither is, generally, technically superior over the other.

**Comment by paride** [comment]
I was wondering: is Plex designed using cubic Bézier curves? In this case the OTF (CFF/PostScript) may be nearer to the original design, as the PostScript natively used Bézier curves, while the conversion towards the TrueType quadratic curves may slightly distort the shapes. At least this is what the FontLab documentation suggests: http://help.fontlab.com/fontlab-vi/Font-Formats/#opentype-tt-ttf.

I am clearly overanalyzing this, and any of the two format would work fine. On the other side there is no hurry, and I'd like to make the best decision.

**Comment by BoldMonday** [comment]
IBM Plex has been drawn completely in cubic bezier curves. Afterwards the outlines have been converted to quadratic curves.

**Comment by madig** [comment]
Does Debian ship with slight hinting by default? If so, the manual hinting done on the font is not even looked at (whereas it is looked at for OTFs).

I personally would recommend OTFs anyway because 

1. I like FreeType's CFF hinting implementation and find most manual TrueType hinting overzealous (note the weight jumps in the native hinting waterfall screenshot and compare to the smooth progression of the OTF)
2. FreeType's CFF renderer is equipped to do stem darkening, which is important when in the far future GUI toolkits on Linux do correct text rendering (Qt 5.9+ will render text correctly when using OTFs iirc).
3. (OTF rendering is very similar to slightly hinted (read: autohinted) TTF rendering, so fonts look harmonious next to each other, despite the different formats)

Side note: the "forced autohinting" mode for FreeType is, uh, maybe don't use it. It tends to look uneven.

**Comment by paride** [comment]
@madig Thanks. Yes Debian ships with slight hinting by default, and I agree the waterfalls look better for the OTF/CFF version. For this and other reasons (e.g. CFF natively represents the Bézier curves the font has been designed with) I decided to package the OTF version. The package is waiting in the Debian's new packages queue [1] since Septemper 18.

[1] https://ftp-master.debian.org/new.html
