### ISSUE TITLE
Method to always use slashed zero character in web app?

### ISSUE THREAD

**Issue by benpotter** [IBM/plex#204]
What's the best method for using Plex Sans and getting all zero characters to be replaced with the slashed zero version? I'm thinking this would require building a special version from source. Is there a better option? Ideally this could be accomplished with .scss

**Comment by benpotter** [comment]
Looked at `font-variant-numeric: slashed-zero;` as a potential solution and unfortunately the browser support is not sufficient for the requirements of this project. Are there other methods of forcing a slashed-zero? Open to any/all options like using Python to compile a custom font-family... other options?

**Comment by BoldMonday** [comment]
What about activating features with the following ccs syntax:
```
-moz-font-feature-settings: "ss03";
-webkit-font-feature-settings: "ss03";
font-feature-settings: "ss03";

-moz-font-feature-settings: "ss04";
-webkit-font-feature-settings: "ss04";
font-feature-settings: "ss04";
```

**Comment by benpotter** [comment]
@BoldMonday thanks for the snippets! I'll give these a try and report back as IE does have support for  font-feature-*

**Comment by tekatone** [comment]
Came across to this post and was able to make feature settings work on Chrome, Firefox, Opera, Edge but for the life of me I can't make it to work on Safari and mobile web browsers.

But on the other hand this website — https://beautifulwebtype.com/ibm-plex-sans/ — is working on every single browser including mobile browsers and I can't figure out how it has been done.

Would it be possible to have some guidance on this subject? Is there a JS related workaround? Can it be done only with CSS?

I'm loading the font from Google and here is what I have in my CSS (tried one by one also:

`
-webkit-font-feature-settings: "ss01", "ss02", "ss03", "ss04";
`
`font-feature-settings: "ss01", "ss02", "ss03", "ss04";`

Thanks.

**Comment by tekatone** [comment]
Anyone? @BoldMonday @mjabbink

**Comment by BoldMonday** [comment]
Sorry we are not web developers ourselves. But there should be plenty of guidance online how to make certain OpenType features work via css in browsers.

Remember that for the slashed zero you need to activate feature `ss03`.
For the dotted zero you need to activate feature `ss04`.

**Comment by mjabbink** [comment]
Maybe @vpicone can help?

**Comment by tekatone** [comment]
Thanks for the replies. Looking forward to hear from @vpicone — if possible.

I really love the default font but when I found out about `ss01` and `ss02` alternates I couldn't go back to default one :)

**Comment by tekatone** [comment]
An update and in case anyone else having this issue should load the font locally for `font-feature-settings` to work (I don't know why it's not working when loading it from Google).

This slides — https://typography-for-developers.now.sh/ — on @vpicone website helped me understand more clearly on how to do this.

Thanks.

**Comment by BoldMonday** [comment]
The fonts served by Google are probably stripped from all extras (including the alternate forms for `zero`) in order to save bandwidth. This is beyond our control.
