### ISSUE TITLE
text-overflow: ellipsis on IE11 with Carbon9

### ISSUE THREAD

**Issue by konghu** [IBM/plex#207]
I am experiencing an in IE11, where you use text-overflow: ellipsis, it's displaying squares instead of '...'

I have read about related defects(https://github.com/IBM/plex/issues/150), and found that this issue seemed to have been reported and resolved, but it seems to be a regression issue when we are using Carbon-components: 9.0.11.
If I revert Carbon to 8.10.0, the font is good.

I tried both plex version 1.0.2 and 1.1.6

![7cd3f6d0-ab93-11e8-8c0c-6a3782154ac2](https://user-images.githubusercontent.com/21697034/46757462-3882ed80-cc98-11e8-9f7a-4d4d5d9c5824.png)
 
Thanks!

**Comment by konghu** [comment]
Thanks for your reply! Yes, once I updated carbon to `9.29.0`, the font is displaying properly

**Comment by asudoh** [comment]
Great to hear that the problem is solved!
