### ISSUE TITLE
Arabic support?

### ISSUE THREAD

**Issue by nimrud** [IBM/plex#211]
Do you have a time-frame when will you support Arabic, if any?

**Comment by mjabbink** [comment]
We will have Arabic early January.

**Comment by mjabbink** [comment]
![img_1762](https://user-images.githubusercontent.com/32881239/47826919-4553a800-dd51-11e8-8f72-7d5ec155dbe7.jpeg)

**Comment by duhok1** [comment]
Just wondering ... Is Arabic support still coming?

**Comment by mjabbink** [comment]
Yes. Already have Opentype just waiting for final TrueType. You can see what the non-Latin scripts are here. Arabic the only thing missing in GitHub right now. Give it a week or two. 

https://fonts.adobe.com/foundries/ibm

—
Mike Abbink
Executive Creative Director, 
IBM Brand Experience & Design 
IBM Distinguished Designer

+1 917 291 7516 mobile
mjabbink@us.ibm.com
mike@mikeabbink.com

—
Sent via iPhone

**Comment by duhok1** [comment]
> Yes. Already have Opentype just waiting for final TrueType. You can see what the non-Latin scripts are here. Arabic the only thing missing in GitHub right now. **Give it a week or two.** https://fonts.adobe.com/foundries/ibm
>

Awesome, it looks great! ... Can't wait.

**Comment by mjabbink** [comment]
Actually, the open type will need an update as a small bug was found. All coming new files coming this week including TT.
