### ISSUE TITLE
Vertical position : intended or wrong ?

### ISSUE THREAD

**Issue by fthx** [IBM/plex#212]
Hi,

Running Ubuntu 18.10 GNOME, in Thunderbird (e.g.) : 

**Plex**

![image](https://user-images.githubusercontent.com/23138504/47897813-74fad100-de73-11e8-95a6-6e8ec6e7b5d7.png)

**Liberation 2** (to compare inside IBM ;-) )

![image](https://user-images.githubusercontent.com/23138504/47897895-e044a300-de73-11e8-87ad-0c430eebe160.png)

IMHO the vertical position of Plex font is not looking good. I don't know if it's only GNOME/Linux related.

**Comment by fthx** [comment]
(I realize that the distance between the "G" and the "m" of "Gmail" with Plex looks odd. If i have to open another bug if it's-a-bug-and-not-a-feature, I'll do.)

**Comment by mjabbink** [comment]
@BoldMonday can have a look. I se the spacing looks a hair open there.

**Comment by BoldMonday** [comment]
What version of Plex Sans (filetype, version number) is used here?

Is it an official version downloaded from this repo?

**Comment by fthx** [comment]
I downloaded from this repo.
Today, after your answer, I installed the deb package from Debian : 
https://packages.debian.org/sid/fonts-ibm-plex
That's an up-to-date version.

I get the same issue in TB. But I do not experience the same behaviour in GNOME Calendar (e.g.) : 
![image](https://user-images.githubusercontent.com/23138504/49178864-33b1f000-f351-11e8-84a4-6c679bfc70e6.png)
Nor in Synaptic : 
![image](https://user-images.githubusercontent.com/23138504/49178927-63f98e80-f351-11e8-9cb3-1e58c1140417.png)
So I really don't know what's wrong here. For sure Liberation2 fonts are rendered right in any app including TB.

**Comment by mjabbink** [comment]
I recommend using fonts from this repo

**Comment by fthx** [comment]
This bug is still here with 1.2.1 TTF from this repo.

**Comment by mjabbink** [comment]
@BoldMonday
