### ISSUE TITLE
Update to IBM Plex Sans: 3.1

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#213]
@alisonjoseph please update with the current files for Sans 3.1. Much thanks.

**Comment by mjabbink** [comment]
I sent link in Slack

**Comment by BoldMonday** [comment]
## [IBM PLEX SANS V3.1] - 2018-11-21
### Added
- OpenType layout feature "subs"
- meta table to all generated otf and ttf font files

### Removed
- Glyph /ibmlogo07 (0xEBE7)

### Changed
- OpenType layout feature "mark" includes support for combining mark positioning on accented glyphs
  Referenced in [issue 152](https://github.com/IBM/plex/issues/152)
- Synchronised vertical metrics settings between hhea and OS/2 table

### Fixed
- Errors in PS hint replacement in all files containing PostScript outlines

**Comment by mjabbink** [comment]
@sockol Please update with latest sans 3.1 and Devanagari.
