### ISSUE TITLE
A more distinctive 3 and Cyrillic Ze?

### ISSUE THREAD

**Issue by mm-2018** [IBM/plex#215]
I wonder if it would be possible to adapt the digit 3 in the IBM Plex Sans and Mono fonts to make it look less similar to Cyrillic letter Ze, or adapt said letter to make it look less similar to the digit. As far as I know, IBM Plex Serif is the only font family in the entire superfamily to be able to do this.

**Comment by BoldMonday** [comment]
Plex Serif has serifs and ball terminals, that allow for more options when designing a glyph like Ze.

In Sans and Mono these options are not available, hence letter Ze resembles more the numeral three. This is the case in pretty much every other sans serif design as well.

**Comment by mm-2018** [comment]
I understand that this is the case for many sans-serif designs. I have seen other typefaces that take this into account though, namely the PT Fonts and Anonymous Pro.

I like that IBM Plex Serif at least takes this into account (unlike, for instance Noto Serif and Liberation Serif, other OFL Unicode typefaces that I've seen as default typefaces in more recent versions of various GNU/Linux distributions), but I admit my impressions of that font family has been a bit mixed, especially on high pixel density displays. I appreciate your response anyway if this is not a design decision you are going to take on.
