### ISSUE TITLE
Some issue with framing characters

### ISSUE THREAD

**Issue by anhbakhia** [IBM/plex#220]
I'm sorry for my English. By "framing characters" I mean these:

```shell
╔═════════╗
║   abc   ║
╚═════════╝
```

First image is Source Code Pro Regular 50p:
![source-code-pro-regular-10](https://user-images.githubusercontent.com/45343222/50407960-ab6e2000-0814-11e9-9293-ae80665e7fb4.png)

Second one is IBM Plex Mono Regular 50p:
![ibm-plex-mono-regular-10](https://user-images.githubusercontent.com/45343222/50407964-c0e34a00-0814-11e9-8c96-2abf2b6bf371.png)

I've tried on some text editors and it's the same. Would you please check to see if it's a bug?

Thank you,

**Comment by BoldMonday** [comment]
Duplicate of issue #93

**Comment by anhbakhia** [comment]
@BoldMonday 

Thank you. I'm closing this issue.

Merry Christmas  :-)
