### ISSUE TITLE
Special Symbols / Features - documentation 

### ISSUE THREAD

**Issue by SieDa** [IBM/plex#221]
You have added a special symbol for the EyeBeeM  - I like that ;-)
 
It would be nice, to have the "Eye", "Bee", "I", "B", "M" as single Characters in the same style too to reflect the usage of EyeBeeM or reference the IBM in writing in this style.

In TeX that would be reflected may be as \ibmEye, \ibmBee, \ibmI, \ibmB, \ibmM and the yet existing \IBM. See https://ctan.org/pkg/plex-otf package documentation of H. Voß. 

May be this document can become a part of your package to document the updated features and their usage in different applications (TeX realted) and may be later in similar quality. 
Others may add similar documents in other environments to see how Plex works/supports Apple, Linux and Windows related client software and server environements e.g. for web integrations. 

IBM should support all special characters know from i, p, z host environemnts - looks funny, if your own applications can not work properly, if the Plex Font is choosen (e.g. 5250 Terminal fonts).

**Comment by mjabbink** [comment]
All new version have the rebus (eye, bee, M) removed.
