### ISSUE TITLE
Problem With The Relative Path Prefix

### ISSUE THREAD

**Issue by haydaralrikabi** [IBM/plex#223]
React apps complain that it cannot import the font because it is outside the 'src' directory.
A temporary fix is to edit the imported 'ibm-plex.scss' file and change the relative path prefix there as follows:
```$font-prefix: '' !default;```

**Comment by phillip-haydon** [comment]
This worked for me on a Vue app.

**Comment by vpicone** [comment]
You're meant to override the path prefix with your own sass variable. The `!default` tag means it defers to your value.

**Comment by phillip-haydon** [comment]
Why am I meant to? Why is it not optional?

**Comment by vpicone** [comment]
The src directory constraint is unique to create-react-app’s webpack config. You can throw the font files in your source directory and update the prefix appropriately to solve this issue. 

@haydaralrikabi is it cool if I close this?
