### ISSUE TITLE
IBM Plex Mono Designspace file missing instances

### ISSUE THREAD

**Issue by weiweihuanghuang** [IBM/plex#229]
as per the last issue i'm trying to generate some instances from the masters, the design space file has the following:

PlexusMono-Extralight Italic
PlexusMono-Extralight
PlexusMono-Light Italic
PlexusMono-Light
PlexusMono-Medium Italic
PlexusMono-Medium
PlexusMono-SemiBold Italic
PlexusMono-SemiBold
PlexusMono-Text Italic
PlexusMono-Text.ufo

but in the instances folder there is many more instances:

**IBM Plex Mono-Bold Italic
IBM Plex Mono-Bold**
IBM Plex Mono-ExtraLight Italic
IBM Plex Mono-ExtraLight
**IBM Plex Mono-Italic**
IBM Plex Mono-Light Italic
IBM Plex Mono-Light
IBM Plex Mono-Medium Italic
IBM Plex Mono-Medium
**IBM Plex Mono-Regular**
IBM Plex Mono-SemiBold Italic
IBM Plex Mono-SemiBold
IBM Plex Mono-Text Italic
IBM Plex Mono-Text
**IBM Plex Mono-Thin Italic
IBM Plex Mono-Thin**

I've boldened the missing ones from the designspace.

**Comment by BoldMonday** [comment]
The weights you marked in bold are the actual masters, not instances.

Looking at https://github.com/IBM/plex/blob/master/IBM-Plex-Mono/sources/masters/IBM%20Plex%20Mono%20Roman.designspace you can see those weights defined there.

BTW: What is `Plexus`?

**Comment by weiweihuanghuang** [comment]
Ohh of course! That makes sense. Ah 😅 Plexus is an edit I’m making of IBM Plexu :)
