### ISSUE TITLE
Chinese character support timeline?

### ISSUE THREAD

**Issue by matthewlyle** [IBM/plex#234]
I noticed on the website that Chinese support is coming "2019-2020". Are there more details about that or a roadmap I could check out to stay up-to-date on progress?

**Comment by mjabbink** [comment]
Korean will be Jul–Aug
Japanese end of 2020
Chinese end of 2021

**Comment by johnnyshields** [comment]
Looking forward to this. Will both ming/myeongjo/mincho and gothic variants be supported for each CJK charset?

**Comment by jerviscui** [comment]
Is it done?

**Comment by mjabbink** [comment]
There is a new delivery schedule for INM Plex® Sans TC and SC — Q4 2023.
