### ISSUE TITLE
Akamai CDN Hosting

### ISSUE THREAD

**Issue by photodow** [IBM/plex#235]
We're facing some [security errors](https://github.ibm.com/webstandards/digital-design/issues/441) with the current Plex CDN options we've seen in #106 on IBM.com. Akamai is the preferred and secure solution at the moment that serves IBM.com CDN solutions (it might would also be great to get IBM.com, products and more on the same plex CDN to benefit from caching and such). I was wondering if y'all have a plan to release to Akamai in the future and support it officially, if that's something y'all would do or if we should handle that, do y'all currently handle any automatic deployments here for any plex hosting solutions?

Anyway, just thought I would get the conversation started, and would love to get y'alls expertise on the discussion. We currently have an older version of Plex hosted on Akamai in production today, and would like to get that updated but want to make sure the right team is maintaining it.

#### Additional information
 - Here is a bug reported and short discussion on different CDN options mentioned above. https://github.ibm.com/webstandards/digital-design/issues/441

**Comment by vpicone** [comment]
Hey @photodow! Different hosting options for Plex are currently being discussed. The unpkg solution isn't meant to be used in production. 

As of now, the recommended solution is to self-host Plex and override the $font-prefix sass variable to indicate the path to where the font is located.

```
$font-prefix: './custom/path/to/font/files';
@import 'node_modules/@ibm/plex/scss/ibm-plex.scss';
```

**Comment by photodow** [comment]
Hey @vpicone, thanks for the response. Yeah, I'm aware of the recommendation, and the unpkg limitations. I've been asked to look at this at a broader scope, so individual teams on IBM.com don't have to host their own solution. I wanted to get y'alls input before doing anything to make sure we're aligned with y'all, but if y'all are already having these discussions I'd love to get involved if possible.
