### ISSUE TITLE
Serif family not displaying in browser

### ISSUE THREAD

**Issue by rubenprol** [IBM/plex#239]
I've installed the font via npm. Every family renders correctly but the Serif (it shows the default Times New Roman).

No erros shown in the console.

Using Chrome Version 73.0.3683.75 (Official Build) (64-bit).

**Comment by vpicone** [comment]
Just made a fresh project and was able to use the Serif without any issues.

Are you using the css that comes packaged with npm? 

Are you using the latest version from npm (1.3.0)?

**Comment by rubenprol** [comment]
It works perfectly. We've had problems with the webpack configuration but it's all fixed.

Sorry!
