### ISSUE TITLE
Arabic files are out of folder structure the downloading OTF

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#241]
@vpicone @alisonjoseph 
Can you remove the loose Arabic files from OTF folder. They should only be inside the Arabic folder. 

<img width="413" alt="Screen Shot 2019-03-24 at 1 10 02 PM" src="https://user-images.githubusercontent.com/32881239/54882977-53a47c80-4e36-11e9-977b-207f52f19710.png">

**Comment by alisonjoseph** [comment]
fixed! https://github.com/IBM/plex/releases/tag/v1.3.1

**Comment by mjabbink** [comment]
@alisonjoseph Nice!
