### ISSUE TITLE
Font not working on Farsi/Arabic text

### ISSUE THREAD

**Issue by theiliad** [IBM/plex#242]
Hi,
I'm loading the IBM Plex Sans font through google font **(photo on the right)**
![image](https://user-images.githubusercontent.com/14989804/55034479-e89ca680-4feb-11e9-832a-093d0841af11.png)

However, I believe that that's not the actual IBM Plex Sans font shape for Farsi text. I get different results on the https://www.ibm.com/plex/ website **(photo on the left)**.

I can confirm that the font is properly loaded, since my english text is rendered properly in the IBM Plex Sans font.

Any ideas here? What could possibly be going wrong?

**Comment by vpicone** [comment]
IBM Plex Sans is a different font entirely from IBM Plex Sans Arabic. If you try to use Arabic characters with just IBM Plex Sans on the page, it will resort to a fallback font.

Google Fonts does not yet have the Arabic font, but Adobe does: https://fonts.adobe.com/fonts/ibm-plex-arabic

**Comment by theiliad** [comment]
@vpicone Great, that makes a lot more sense now.

In terms of the availability of the font, Adobe is problematic since I'm going to use the font in the demo site for an open-source repo, and wouldn't want to expose an Adobe Project ID.

Is there another way to use the font without having to create an account somewhere?

**Comment by theiliad** [comment]
Might just include the actual files in the project...

**Comment by vpicone** [comment]
You can store host the font yourself, in your project, or put your Adobe Project ID as an environmental variable.

**Comment by theiliad** [comment]
There is no way to hide the Adobe Project ID, even if you use it through an env. var. one could easily find it on the frontend. Will go for hosting, thanks @vpicone

**Comment by vpicone** [comment]
@theiliad if that were the case wouldn't it be impossible to use adobe fonts professionally then?

**Comment by theiliad** [comment]
@vpicone Yes so you are able to only allow access to a Project ID for domains of your choosing, but that doesn't work in my case. We'd like users to be able to fork the repo, and run our demo site locally to test their contributions, therefore we'd have to allow `localhost` as a domain...
