### ISSUE TITLE
Add Plex Thai Looped to Plex github repo

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#244]
@vpicone It would be great to get this up as soon as possible. We’re waiting to include Thai Looped for an internal communication and push to IBMers with all non-Latins to employees via CIO. Much thanks!

You have link to files in Slack.

**Comment by BoldMonday** [comment]
@mjabbink What about Plex Sans Variable? We delivered these a few weeks ago.

**Comment by vpicone** [comment]
@BoldMonday I’ll be adding that as well. Was waiting until our Carbon X release was through.

**Comment by BoldMonday** [comment]
Great to hear @vpicone. Some other people out there are looking forward to see it released.

**Comment by SixFingeredAmish** [comment]
@vpicone Is this a temporary version of Thai Looped? Currently, it looks like an entirely different family from the loopless version

**Comment by mjabbink** [comment]
Looped and loopless are different animals. They have a great amount of sameness and different where they need to be. It is the final version.
