### ISSUE TITLE
Consider slashed zero as default in IBM Plex Mono

### ISSUE THREAD

**Issue by viniciusban** [IBM/plex#248]
I read issues #89 and #102  and I know "All IBM Plex fonts contain a slashed zero", but in practice, is there any terminal emulator capable of showing it?

Actually you didn't answered if you consider or not to bring slashed zero as default in IBM Plex Mono.

If you don't consider it, how about creating some blog post anywhere teaching how to activate the slashed zero in terminal emulators?

I use Ubuntu and MacOS and haven't found any terminal emulator capable of working with the "zero" feature or the stylistic sets, afaik.

Thanks in advance.

**Comment by BoldMonday** [comment]
In order to consider having slashed zero as default in IBM Plex Mono there has to be a compelling reason to do so. I am interested to hear your argument.

Currently the dotted zero in IBM Plex Mono already creates a very clear distinction with Latin uppercase letter `O`. And also cannot be confused with either Latin uppercase letter `Ø`, or the diameter symbol `⌀`.

**Comment by viniciusban** [comment]
Paul, your question made me think quite objectively about why I'd like to have the slashed zero as default.

You're correct about the Plex Mono's "clear distinction" with examples you gently gave. This is the extremely important rational and professional part.

I realized I'm fond of the slashed zero due to historical reasons, a bit of ignorance and personal preference.

Historically we have used slashed zero to differentiate it from uppercase "o".

I live in Brazil. Here we don't have the uppercase Ø letter (keys: option + shift + o pressed simultaneously in MacOS keyboard). I made a quick search about this point and I discovered other languages have it (https://en.wikipedia.org/wiki/Ø).

Undoubtedly slashed zero is very similar with "Ø" and dotted zero is a great approach to this situation.

The rational section ends here.

OTOH, I must admit I think slashed zero more comfortable and more beautiful than the dotted zero. This is not rock science, only a personal feeling from me, who uses terminal for about 10 hours almost every work day.

**Comment by BoldMonday** [comment]
Thanks for clarifying!

We try to accomodate requests for particular glyphs as best as we can. And personally I think slashed zero is a nice part of type history with strong connections to the early days of computing. That is why we included it in the first place, and why we try to make alternative glyphs like these as accessible as possible by including it into OpenType features.

However, that is the best we can do. If there are applications out there that do not support OpenType features then I think it is a question for the developers of those applications.

**Comment by mjabbink** [comment]
@viniciusban I like Slashed zero as well but we went with dot because that shape in particular is very important. It’s an "engineered" shape that is quite distinctive if you see it a bit larger. It’s not just some average dot or circle shape. It has Plexness!
