### ISSUE TITLE
Missing character (U+0009) 'CHARACTER TABULATION'

### ISSUE THREAD

**Issue by gamodulon** [IBM/plex#249]
Great job with the font.
Please add missing tab character.

**Comment by BoldMonday** [comment]
Do you have examples of use cases for this glyph?

**Comment by gamodulon** [comment]
It is a common ASCII character. It is used in programming languages' strings, parsing, formatting.
Sometimes supplementing tab character with spaces is not enough.
Is there a reason for it not to be added to the font family?

**Comment by moyogo** [comment]
U+0009 is already in IBM Plex fonts, except for IBM Plex Sans Variable fonts.

It is mapped to the same glyph as U+0020 space, which agrees with [pre-OpenType 1.8 recommendations](https://docs.microsoft.com/en-us/typography/opentype/otspec170/recom#additional-recommendations) that most fonts still follow in a similar manner.

**Comment by BoldMonday** [comment]
@gamudolon Please provide an example where IBM Plex is currently not working correctly due to the lack of said character.
