### ISSUE TITLE
Variable font built with fontmake?

### ISSUE THREAD

**Issue by vvug** [IBM/plex#253]
According to https://github.com/IBM/plex/tree/master/IBM-Plex-Sans-Variable/README.md (and to the actual `build.sh` script) the variable font can be built with fontmake! Does this mean that we can finally build Plex with a free toolchain? How is hinting handled? What about the other fonts?

**Comment by BoldMonday** [comment]
As described in de README, Plex Sans Var can indeed be compiled with fontmake The README also mentions that the pre-compiled versions contain several enhancements (such as hinting) that will not be included when you compile the font yourself.

For all other parts of the Plex family the status regarding hinting and a free toolchain has not changed.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
