### ISSUE TITLE
Please reinstate platform-specific recommendations in release notes

### ISSUE THREAD

**Issue by GrahamHannington** [IBM/plex#258]
I've pointed colleagues to the [latest release of IBM Plex](https://github.com/IBM/plex/releases/latest).

Immediate questions I've received are:

* "For Windows, should I install TrueType or OpenType?"
* "For macOS, should I install TrueType or OpenType?"

I notice that, for earlier releases—but not the last few releases—the release notes included the following statement:

> TrueType.zip is recommended for MacOS and Windows

Is that recommendation still true?

Either way, could you please reinstate such platform-specific recommendations in the release notes, or link from the release notes to such a statement in the readme (or elsewhere), or just insert that statement somewhere prominently in the readme?

## TrueType vs OpenType

When colleagues asked me which release `.zip` file to use, I did some Googling. In addition to that recommendation in old release notes, I found some related comments by @BoldMonday in GitHub issues:

* 17 April 2018 comment on issue #161: "In general, TrueType fonts are the recommended format for Windows." 
* 28 August 2018 comment on issue #198: "The IBM Plex TrueType fonts have been optimised for Windows ClearType rendering"

In general, to the extent that I understand the differences (I'm no expert on this subject), you should be able to install either `.otf` or `.ttf` font files on Windows 10.

However, for IBM Plex, based on those GitHub issues, I understand that there might be reasons to favor the `.ttf` files for Windows.

## Reasons for recommending one format over another?

Could you please clarify (perhaps in the readme) your reasons for recommending one font format over another for different platforms? Here, I'm not asking for a general description of differences between `.otf` and `.ttf` files: rather, I'm asking for differences specific to IBM Plex, such as, for example, font IDs in the IBM Plex `.otf` files exceeding the limit on a specific platform (if that is still an issue with IBM Plex).

## Naming of the release `.zip` files

The more I read on this subject, the more I suspect the IBM Plex release file name `OpenType.zip` might be misleading.

From the Wikipedia article on [TrueType](https://en.wikipedia.org/wiki/TrueType):

> A .ttf extension indicates a regular TrueType font or an OpenType font with TrueType outlines [...] An OpenType font with PostScript outlines must have an .otf extension.

In issue #198, another user, @twardoch, comments:

> both OTF and TTF fonts are OpenType. OTF are PostScript-flavored OpenType fonts and TTF are TrueType-flavored OpenType fonts.

Indeed, in the same issue, @BoldMonday characterizes the two versions not as "TrueType" and "OpenType", but as "TrueType (TTF)" and "_PostScript_ (OTF)".

Your thoughts?

**Comment by BoldMonday** [comment]
> Is that recommendation still true?
Yes, that recommendation still stands. Both for Windows and MacOS even though both platforms can technically handle both TTF and OTF fonts.

I agree that the recommendation should be mentioned in the release notes and README.

**Comment by GrahamHannington** [comment]
Excellent, thank you! Your call entirely, but might I be so 700-weight :wink: as to suggest
reinstating that brief statement in each set of release notes, with a link to a more
detailed explanation of the reasons for the recommendation (e.g. ClearType) in the readme?
