### ISSUE TITLE
[IBM Plex Mono] Make some characters more prominent

### ISSUE THREAD

**Issue by ghost** [IBM/plex#260]
Hello Developers,

For comparison, I use Input: <http://input.fontbureau.com/download/>

These characters in Input are more prominent than Plex Mono's:

```code
^`,~+-*#'"
```

May I ask if you could consider updating Plex Mono, to make those characters much more prominent, like in Input?

Thank you,

**Comment by AlsoScratch** [comment]
I think this can be closed, this user account no longer exists.
