### ISSUE TITLE
[Question] Can’t use IBM Plex Mono Italic on Windows, but it works on Mac

### ISSUE THREAD

**Issue by vuongggggg** [IBM/plex#261]
```json
{
  "editor.fontFamily": "'IBMPlexMono-Italic', 'Fira Code', sans-serif",
}
```

I would like to use IBM Plex Mono Italic on both Windows and Mac. It works on MacOS but can't works in Windows 10, then it shows the fall back font. Can anyone help me, please? Thanks.

**Comment by mjabbink** [comment]
have you installed TT or OT? If you choose OT is will certainly have issues in the Windows environment. I would use TT for Windows and OT for Mac but TT would work on Mac as well. I prefer OT for a few handy reasons.

**Comment by vuongggggg** [comment]
I used TTF for both, but all fonts just works on MacOS and for Windows it only worked on web browsers. Any regular fonts are working on Windows, but not Italic.

For Italic-problem, I'm using VSCode for now, is any special thing happens with this?

**Comment by mjabbink** [comment]
Hmm. @BoldMonday Any thoughts on this one?

**Comment by BoldMonday** [comment]
This question appears to be related to #288.

Please see if there is a way to specify "IBMPlexMono" as family and "italic" as font-style in the editor preferences.
