### ISSUE TITLE
IBM Plex Mono as a custom axis inside IBM Plex Sans Variable?

### ISSUE THREAD

**Issue by kgibb** [IBM/plex#262]
Hello, 

Our application uses four variants of IBM Plex Sans, light, text, medium, and bold. We also use IBM Plex Mono for some controls. Using IBM Plex Sans Variable has quartered the number of font requests and halved the throughput. However, we still have a dependency on IBM Plex Mono. Could Mono be added to the variable font as a custom axis?

Thanks

**Comment by BoldMonday** [comment]
That is an interesting thought. Although wouldn’t it also bloat the current Plex Sans Var font with an axis that not everyone will need?
Technically it is possible to add the Serif family as a custom axis as well. But I’m not sure that is a good idea.

I think it makes more sense to create separate variable versions for Plex Mono and Serif.

**Comment by twardoch** [comment]
I agree with @BoldMonday. Also, itemizing the designs to some extent is better for  continued development. If more glyphs are added to the Sans, it's great to have them in the fonts as soon as possible. But if also monospace versions need to be designed, that may delay the progress.  And it would be odd if only some glyphs in the sans+mono VF had monospaced glyphs. 

On the other hand, one can imagine that the monospace font could receive many more glyphs for scripts where in proportional sans, they might be better off in separate fonts. 

Monospaced fonts are simplified and don't require extensive OpenType features, so in theory, one can put monospaced glyphs for all Unicode writing systems except CJK into one font — while it might be difficult and uneconomical to put proportional glyphs for all writing systems into one.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
