### ISSUE TITLE
IBM Plex Sans weight 400 is bolder than it should in Firefox and IE

### ISSUE THREAD

**Issue by garcia323** [IBM/plex#263]
I downloaded Web.zip released July 15. I'm using it in IBM Content Navigator, which is built on Dojo. IBM Plex Sans weight 400 looks like it should in Chrome, however, it looks a lot bolder in Firefox and IE11. Firefox developer tools showed that the  IBM Plex Sans was being loaded from one of the IBMPlexSansText WOFF files, instead of the regular IBMPlexSans WOFF file. I removed all the rules in ibm-plex.min.css that used IBMPlexSansText WOFF files and now Firefox and IE11 load the IBMPlexSans WOFF files and display the text as expected.
Is this a known issue?
Is there a better way to address this issue? If not, are there potential side-effects of removing the IBMPlexSansText WOFF rules from ibm-plex.min.css?

**Comment by vpicone** [comment]
IBM Plex Sans Text is for font weight 450. Some browsers will pull your local version of plex. Sometimes it's helpful to uninstall Plex from your os when debugging this sort of browser behavior. One thing that sticks out to me is that Firefox should be loading from a woff2 file.

IDK what the dojo dev enviroment is like, but something might be wrong with the 400 weight Plex font on your system from the perspective of Firefox/IE

**Comment by garcia323** [comment]
Dojo wouldn't play a role in this CSS issue; it's just a JavaScript toolkit. I meant woff2, not woff. I removed IBM Plex fonts from my system and the issue is still present. Firefox loads ../IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Text-Latin1.woff2 for font-weight 400. Chrome loads the correct file (../IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Latin1.woff2).
Can you reproduce this?

**Comment by vpicone** [comment]
I can't. Does it change based on the content you're displaying? I suppose it could be a weird unicode thing but I'm not sure.

**Comment by garcia323** [comment]
It's the same for all content using font-weight 400. I scanned our CSS for 450 and confirmed we don't use that font-weight. One thing I noticed is that the fonts were loaded and displayed correctly when I removed ibm-plex.min.css to force the browser to load the fonts from Windows (this was before I removed IBM Plex from my system). So there's something in the font-face declarations in ibm-plex.min.css that Firefox and IE don't like. I don't know what else to try. Since we don't use font-weight 450, I'm going to remove them from ibm-plex.min.css.

**Comment by mjabbink** [comment]
Hmm? @BoldMonday?

**Comment by BoldMonday** [comment]
Different browsers may use different rasterizers therefore the rendering of type can differ.

Please provide screenshots in order to show whether this is a rendering issue, a font issue, or a css issue.

**Comment by mjabbink** [comment]
Hmm.

**Comment by twardoch** [comment]
@garcia323 Does the problem occur with the italics as well? Does it happen with the unminified css file as well?

**Comment by mjabbink** [comment]
@garcia323 Do you still have the issue? Any screen grabs and details will be helpful. Closing for now since it’s been so long and I’m assuming you sorted it out.
