### ISSUE TITLE
f+i ligature

### ISSUE THREAD

**Issue by bcroq** [IBM/plex#264]
The f+i ligature is sometime _strange_, a little too low.

Here are screenshots from https://fonts.google.com/specimen/IBM+Plex+Sans using Chrome on Ubuntu 18.04.

14px: ![Capture d’écran de 2019-07-19 11-54-26](https://user-images.githubusercontent.com/130780/61527554-05d30600-aa1d-11e9-9be1-4460f84a1e2b.png)

16px: ![Capture d’écran de 2019-07-19 12-02-27](https://user-images.githubusercontent.com/130780/61527645-3adf5880-aa1d-11e9-8ebe-1e5c7415197a.png)

18px: ![Capture d’écran de 2019-07-19 12-03-51](https://user-images.githubusercontent.com/130780/61527718-62362580-aa1d-11e9-8831-98875f6b3715.png)

Using Firefox on https://fonts.google.com/specimen/IBM+Plex+Sans I don't get this bug. In fact, it uses a different font family:

- `font-family: "IBM Plex Sans script=all rev=1"` is used on Firefox
- `font-family: "IBM Plex Sans script=all rev=2"` is used on Chome

If I force `rev=2` on Firefox, I get the bug. If I force `rev=1` on Chrome, I don't get the bug.

**Comment by BoldMonday** [comment]
This is related to #291. Please see explanation there why this cannot be controlled by the fonts.
