### ISSUE TITLE
Stylistic alternate for uppercase I without serifs

### ISSUE THREAD

**Issue by rekollekt** [IBM/plex#266]
Is there any chance for letter-I without bars as an alternate in sans?

**Comment by mjabbink** [comment]
Sorry but that is a matter of taste. The Slabs are a huge part of the concept and visual frame work and fabric of Plex DNA. Maybe an alternate in the distant future but considering the additional language support and other issues that might need resolving this becomes an extremely low priority. I will close this for now.

**Comment by AlsoScratch** [comment]
@mjabbink Why don't you add the "Low Priority" label back?
