### ISSUE TITLE
Some files in OpenType format are corrupted

### ISSUE THREAD

**Issue by insanetesterftw** [IBM/plex#268]
The files come from the latest release version 2.00. I'm using Windows 7.

- IBM Plex Sans Condensed ExtraLight
- IBM Plex Sans Condensed SemiBoldItalic
- IBM Plex Sans Condensed SemiBold
- IBM Plex Sans Condensed ExtraLightItalic

---

- IBM Plex Sans Thai Looped Medium
- IBM Plex Sans Thai Looped ExtraLight
- IBM Plex Sans Thai Looped SemiBold

Windows Font Viewer reports that they are not valid font files. Others font utilities fail to open the files. FontForge doesn't report any errors when opening, but reports some some problems when generating new files.

From my attempt using FontForge to generate a new file from the corrupted one. "IBM Plex Sans Condensed ExtraLight".

![image](https://user-images.githubusercontent.com/11148841/63204170-eadfca00-c08c-11e9-968d-b4afb6465e53.png)

Without modifying anything still produced a corrupted filed.

This might be related with issue: #161 

The TrueType version of the files are fine.

If the problem is the same as in issue #161 then the files were not properly regenerated.

**Comment by BoldMonday** [comment]
This is indeed the same issue as #161.

And as advised there: TrueType fonts are the preferred format for Windows. They have been tested and work fine.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
