### ISSUE TITLE
Add Plex Sans Devanagari update to repo

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#270]
Changed
• Added "Sans" to font family name: "IBM Plex Sans Devanagari"

Fixed
• Certain font info fields in SemiBold style were incorrectly named "Medium"
• Many unbalanced bezier handles in extreme points

**Comment by AlsoScratch** [comment]
What should I expect to see in this update?

**Comment by AlsoScratch** [comment]
Shouldn't you add "Sans" to all of them?

**Comment by mjabbink** [comment]
we are. Arabic, Thai still need this naming update as well.

**Comment by mjabbink** [comment]
@vpicone status/timing

**Comment by mjabbink** [comment]
@vpicone status on getting this issue

**Comment by mjabbink** [comment]
@vpicone @alisonjoseph This issue was created Aug 19. This needs to be tackled as soon as possible.

**Comment by vpicone** [comment]
Resolved

**Comment by mjabbink** [comment]
🙏
