### ISSUE TITLE
(enhancement) Font Book preview

### ISSUE THREAD

**Issue by AlsoScratch** [IBM/plex#271]
I apologize if this is beyond your control, but it would be nice to see a script specific preview on Font Book.
For example:
<img width="410" alt="Screenshot 2019-08-29 at 11 07 47 AM" src="https://user-images.githubusercontent.com/48752273/63907268-5fcbe000-ca4d-11e9-8439-0681003bfcc8.png">
Currently, all of the IBM Plex Sans font previews just show "_How razorback-jumping frogs can level six piqued gymnasts!_"

**Comment by mjabbink** [comment]
@BoldMonday presume this should close.
