### ISSUE TITLE
Plex Mono: missing characters U+263C and U+25CB

### ISSUE THREAD

**Issue by gnuvince** [IBM/plex#272]
The following two characters are used in the roguelike [Dungeon Crawl: Stone Soup](https://crawl.develz.org/) for representing fire:

- ☼: U+263C (WHITE SUN WITH RAYS)
- ○: U+25CB (WHITE CIRCLE)

These two characters are missing from Plex Mono. Are there plans to add them in a future release?

**Comment by mjabbink** [comment]
They are not missing. Those are added glyphs beyond extended Latin and Cyrillic that we have already. We will plan on adding additional Glyphs in 2021.
