### ISSUE TITLE
Non-uniform width between Plex Mono Text and Plex Mono Bold

### ISSUE THREAD

**Issue by vsalvino** [IBM/plex#278]
This is an odd issue I have noticed, which could be the fault of the editor, or of the font, I'm not sure.

For background, Visual Studio Code (vscode) renders markdown headings using bold variant of the font.

When using `IBM Plex Mono` in vscode to view markdown, the characters align as expected with any monospace font. However, when using `IBM Plex Mono Text`, characters between bold and regular lines do not align in a true monospace fashion. Figured it was worth noting as vscode supports variable or fixed with fonts, so it appears that some characters in IBM Plex Mono Text are not truly uniform in width.

With vscode settings:
```json
{
    "editor.fontFamily": "IBM Plex Mono Text",
    "editor.fontLigatures": false
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/13453401/66225275-1010b200-e6a6-11e9-8051-f280910eff7c.png)

With vscode settings:
```json
{
    "editor.fontFamily": "IBM Plex Mono",
    "editor.fontLigatures": false
}
```
Screenshot:
![image](https://user-images.githubusercontent.com/13453401/66225460-75fd3980-e6a6-11e9-8fb6-bb4b62c6ede3.png)

**Comment by BoldMonday** [comment]
@vsalvino If you compare both screenshots then you will see that the Bold differs greatly. It appears that VSCode is creating a synthetic (faux) bold with IBM Plex Mono Text and applies some extra spacing to it as well.
The Bold that is shown with IBM Plex Mono is the correct Bold style.

Only IBM Plex Mono (Regular) is linked to IBM Plex Mono Bold. All other styles (Light, Text, Medium, etc.) are not linked to Bold. Technically that is also not possible to achieve on a font level. Pairings can only be made between two individual styles of a typeface family.

**Comment by vsalvino** [comment]
Thanks for explaining. I did not realize that the "Text" version was a completely different family - assumed it was just another weight of the same family. The Regular version renders very poorly on my laptop (Widows 10, lower resolution screen), but the Text version is magnitudes better and more legible. If I plug in to a higher resolution monitor then both look very nice.

**Comment by vsalvino** [comment]
As a remedy for my own uses, I tinkered with Font Forge and was able to create an "IBM Plex Mono Text" family that has the Text, TextItalic, Bold, BoldItalic versions all linked together.

https://github.com/vsalvino/ibm-plex-mono-text

Thank you for creating this font and providing it freely... it is a real work of art; the italics are a treat.
