### ISSUE TITLE
Danish letter Å support Sans Plex fails

### ISSUE THREAD

**Issue by KJNC** [IBM/plex#279]
We're experiencing issues when using IBM Plex Sans with the danish letter Å.

It seems like the circle above the A is not included in the line height.

The following images have been created by changing the text with dev tools in chrome on the page https://www.ibm.com/plex/

Normal:
![image](https://user-images.githubusercontent.com/46371025/66312155-66812900-e910-11e9-99e7-d44e28431df3.png)

Selected text
![image](https://user-images.githubusercontent.com/44367338/66312117-4b161e00-e910-11e9-830d-2bbd618d4875.png)

Selected element in dev tools:
![image](https://user-images.githubusercontent.com/46371025/66312344-c7a8fc80-e910-11e9-8c05-3d9c9dd44be0.png)

This makes it really difficult to place the text in elements - for example input fields.

Hope this can be fixed.

**Comment by mjabbink** [comment]
Hmm. I could be totally wrong here but I believe this will be same issue with Georgia, Helvetica, Arial, Charter, SF, Roboto and so forth.

**Comment by mjabbink** [comment]
@BoldMonday Can you confirm if there is an issue here.

**Comment by BoldMonday** [comment]
This should be tested with the latest fonts where the settings for vertical metrics have been improved.

**Comment by KJNC** [comment]
It seems to still be an issue. Just tried with the latest release of IBM Plex Sans, and it seems like it's the same. 

In Internet Explorer however - it's even worse now:
Input field:
![image](https://user-images.githubusercontent.com/46371025/82449801-0fe5eb00-9aac-11ea-90ba-3d8184d1215a.png)

Input field when active/focus:
![image](https://user-images.githubusercontent.com/46371025/82449935-46bc0100-9aac-11ea-923e-b0c69efc3dc7.png)

Input field marked in IE DOM Explorer:
![image](https://user-images.githubusercontent.com/46371025/82449770-05c3ec80-9aac-11ea-8c10-310334c9fe83.png)


I tested with Georgia and Arial, and they were within the bounds of the line height - no issue there.

Georgia:
![image](https://user-images.githubusercontent.com/46371025/82450226-b7631d80-9aac-11ea-9d72-c85ea5e0bd11.png)

**Comment by mjabbink** [comment]
@KJNC The latest is not released just yet. We’re a bit backed up but it’s coming soon

**Comment by DKFDSdevelop** [comment]
@mjabbink - that sounds great! We'll look forward to it.

**Comment by KJNC** [comment]
@mjabbink  - that sounds great! We'll look forward to it :)

**Comment by johnnyshields** [comment]
Would it be possible to get a release candidate build so we can test this?

**Comment by johnnyshields** [comment]
FYI here's another example, Arial vs. Plex. You can see Arial vertically aligns cleanly with the midline of the icons; Plex is vertically too high.

![image](https://user-images.githubusercontent.com/27655/83336385-f6d00c00-a2ed-11ea-8165-313ce100eac0.png)

**Comment by johnnyshields** [comment]
Tested with 5.0.0 and the result is much better. I think this ticket can probably be closed.

**Comment by KJNC** [comment]
It seems to be fixed in 5.0.0. I'll close the issue.
