### ISSUE TITLE
Missing ¤ symbol in Mono?

### ISSUE THREAD

**Issue by AlsoScratch** [IBM/plex#280]
There is no `¤` (u+00a4) symbol in IBM Plex Mono. Will it be added in the future?

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!

**Comment by AlsoScratch** [comment]
I think this issue was closed by mistake. It should be reopened.

**Comment by BoldMonday** [comment]
The glyph in question has been added and will be in the next release.

**Comment by AlsoScratch** [comment]
About when might it be released?

**Comment by BoldMonday** [comment]
Can't give an exact date but pretty soon.

**Comment by AlsoScratch** [comment]
Will [these](https://github.com/IBM/plex/issues/84#issuecomment-539275751) be added to Sans, perhaps?

**Comment by BoldMonday** [comment]
Please stick to the topic. This is about Mono, not Sans.

**Comment by AlsoScratch** [comment]
This character is still missing in 5.0

**Comment by BoldMonday** [comment]
That is correct. The latest Mono update is a minor one removing an IBM logo from the character set and fixing vertical metrics.

**Comment by AlsoScratch** [comment]
When should I expect to receive it?

**Comment by BoldMonday** [comment]
Currency symbol has been added in Plex Mono v2.3 (part of [Release v6.0.0](https://github.com/IBM/plex/releases/)).
