### ISSUE TITLE
unable to download IBM/plex from npm registry 

### ISSUE THREAD

**Issue by jingx-xue** [IBM/plex#281]
when running npm install @ibm/plex
I get the error below:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@ibm/plex' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose npm-session 70976091dab750cd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@ibm%2fplex 891ms
8 silly fetchPackageMetaData error for @ibm/plex@latest 404 Not Found: @ibm/plex@latest
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 5539ms
11 verbose stack Error: 404 Not Found: @ibm/plex@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:810:20)
11 verbose stack     at tryOnImmediate (timers.js:768:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
12 verbose cwd C:\Git Repo\Development\dbastudio-ui
13 verbose Windows_NT 10.0.17763
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@ibm/plex"
15 verbose node v8.12.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @ibm/plex@latest
19 verbose exit [ 1, true ]`

**Comment by vpicone** [comment]
@jingx-xue I'm not able to replicate this problem. Do you mind trying again?

```
~/Desktop npm install @ibm/plex
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Desktop@1.0.0 No description
npm WARN Desktop@1.0.0 No repository field.

+ @ibm/plex@3.0.0
added 1 package and audited 1 package in 5.843s
found 0 vulnerabilities
````

**Comment by jingx-xue** [comment]
> @jingx-xue I'm not able to replicate this problem. Do you mind trying again? Package downloads successfully for me:
> 
> ```
> ~/Desktop npm install @ibm/plex
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN Desktop@1.0.0 No description
> npm WARN Desktop@1.0.0 No repository field.
> 
> + @ibm/plex@3.0.0
> added 1 package and audited 1 package in 5.843s
> found 0 vulnerabilities
> ```

Hi Vince, that may be a problem with having _auth information in .npmrc?
I found another package with similar issue https://github.com/facebook/create-react-app/issues/5389

**Comment by mjabbink** [comment]
@jingx-xue Let us know problem solved. Closing for now.

**Comment by jingxue95** [comment]
> @jingx-xue Let us know problem solved. Closing for now.

yes, is been resolved, thanks!
