### ISSUE TITLE
Kaf (ss06) and Fatha overlap each other in IBMPlexArabic

### ISSUE THREAD

**Issue by munzirtaha** [IBM/plex#284]
First, Thanks IBM, Wael and Khajak for the nice Arabic typeface.

Second, there are some issues with Tashkeel. one example is:
If I type <Kaf, Fatha, Alef> <0643, 064e, 0627>, it looks correct as shown here
![ka-correct](https://user-images.githubusercontent.com/2936425/68533148-51435400-032d-11ea-9210-91965835b5de.png)
However, if I enabled ss06 which changes letter kaf to an alternative style, the Fatha position goes wrong and almost disappears as shown here
![ka-wrong](https://user-images.githubusercontent.com/2936425/68533159-67e9ab00-032d-11ea-84bd-02c3a62ec6ca.png)

**Comment by mjabbink** [comment]
@munzirtaha We’re looking into this.

**Comment by munzirtaha** [comment]
Any update?

**Comment by BoldMonday** [comment]
@munzirtaha The error has been found and a fix is in the works. An update will be pushed soon.

**Comment by mjabbink** [comment]
@BoldMonday presume this is resolved in the latest update?

**Comment by BoldMonday** [comment]
@mjabbink Fixed in latest Hebrew update. Issue can be closed.

**Comment by munzirtaha** [comment]
I don't know what's "Hebrew update", but I checked the latest release and [commits](https://github.com/IBM/plex/commits/master) and couldn't find any fixes. How can I test this?

**Comment by BoldMonday** [comment]
We fixed the issue together with other things, and submitted new files to IBM. It's now up to them to get those files in the repo.

**Comment by mjabbink** [comment]
@munzirtaha The update has not quit been released. @vpicone is close to getting this all released this week I believe. https://github.com/IBM/plex/issues/370

**Comment by munzirtaha** [comment]
Thanks, though I prefer you leave this open till they accept the changes and there is a release that could be tested if that doesn't do any harm to you.

**Comment by BoldMonday** [comment]
Fixed in Plex Sans Arabic v1.2 (part of [Release v6.0.0](https://github.com/IBM/plex/releases/)).
