### ISSUE TITLE
Please sort *all* coverage-specific parts of IBM Plex as Sans/Serif/Mono

### ISSUE THREAD

**Issue by nim-nim** [IBM/plex#285]
Even though Sans/Serif/Mono are Western conventions, that do not exist in every locale, applications and font management frameworks do need to decide what to use when a user inserts an Arabic, Hebrew, Thai or whatever text run inside a block of western text that uses IBM Plex Sans, or IBM Plex Serif, or IBM Plex Mono.

If this mapping is not defined by default at the font project level, different applications and font management frameworks will make different mapping choices, resulting in interoperability problems.

Therefore, please ventilate *all* parts of Plex in Sans, Serif or Mono.

Providing several alternatives (as with Plex Sans Thai and Plex Sans Thai Looped), is perfectly fine, as long as the default one is clearly marked as such (here, Plex Sans Thai).

Un-mapped font blocks like Plex Arabic are *not* fine. Please mark clearly in its name if you intend this design for use as Sans, Serif or Mono Arabic block.

**Comment by BoldMonday** [comment]
An update to Plex Arabic with this change in naming has already been done and delivered to IBM.
@mjabbink @vpicone can you push this update?

**Comment by mjabbink** [comment]
Update complete. Thanks @vpicone

**Comment by nim-nim** [comment]
Thanks for the release!
