### ISSUE TITLE
The naming used by Variable fonts is inconsistent with the naming of the non-variable fonts

### ISSUE THREAD

**Issue by nim-nim** [IBM/plex#287]
The instance names of Plex variable use the
**weight width slope** convention

* for example, _ExtraLight Condensed Italic_

However, the standard way to write style names is 
**width weight slope** 

* ie Name ID 17, corrected in Name ID 22 if necessary, and reused in Name ID 4
* for example, _Narrow Bold Italic_ in  https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp
* or  _Condensed SemiBold Italic_ in  Name ID 4 of `IBMPlexSansCondensed-SemiBoldItalic.otf`

https://docs.microsoft.com/en-us/typography/opentype/spec/name  states
> Note, in particular, that variable fonts can include a large number of named instances, each of which will use a shared typographic family name (name ID 16) and will have a typographic subfamily name (equivalent to name ID 17). 

Therefore the instance subfamily naming is intended to follow the same conventions as ID 17, especially in the same font project.

Not following the same conventions will prevent transparent fallback to variable to non variable fonts in applications.

**Comment by twardoch** [comment]
There is no standard but the by far most widespread convention among font vendors is "weight width slope". It dates back to Adobe Type 1 fonts. I think if the conventions were made today, it world more likely be "width weight slope". But you find "Bold Condensed" way more often than you find "Condensed Bold". 

There are tens of thousands of fonts named this way. But I agree that if the variable fonts use the same family name as the static fonts, the predefined instances in the VF should use the same naming as the static styles. Whether width or weight comes first is a matter of preference, but it should be used consistency.

**Comment by BoldMonday** [comment]
The variable fonts do not use the same family name as the static fonts.
They are named **IBM Plex Sans Var**.

**Comment by nim-nim** [comment]
@BoldMonday you can change the family name in variable fonts all you want, you know and I know apps will end up mapping the variable family to the non variable family to handle transition to full variable fonts, so instance names should be consistent with non-variable style names to allow a smooth transition.

Even when there is no automated mapping, there is a human mapping, and gratuituous differences in naming are a time waster human side (even though, unlike machines, humans can function in fuzzy logic mode)

**Comment by nim-nim** [comment]
> There is no standard but the by far most widespread convention among font vendors is "weight width slope". It dates back to Adobe Type 1 fonts. I think if the conventions were made today, it world more likely be "width weight slope". But you find "Bold Condensed" way more often than you find "Condensed Bold".

The Plex project uses both conventions. It should settle on one. As you noted the modern way to do things is "weight width slope"

That's how all the examples in the OpenType spec are written
 https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp

Likewise, that{s how they are given in modern font creation tools
https://glyphsapp.com/tutorials/naming

Even Adobe did recommend just applying the rules in Microsoft's WWS whitepaper (that use this convention) if you didn't want to pay for its font creation suite
http://blogs.adobe.com/typblography/files/typblography/typotechnica2007/Font%20names.pdf

**Comment by BoldMonday** [comment]
The glyph coverage between the IBM Plex Sans variable and static fonts is different. That is why they have different family names.

They are not meant to be interchangable at this moment and any implementation that assumes they are is not following the very same specs which you are so keen to point to.

**Comment by nim-nim** [comment]
@BoldMonday The font management and substitution systems deployed in production today do not assume one to one interchangeability. Differences in glyph coverages are not specific to Plex.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
