### ISSUE TITLE
In Internet Explorer 11 truncated ellipsis do not render - they appear as squares - still exists

### ISSUE THREAD

**Issue by eshaseth** [IBM/plex#292]
In IE 11 version 11.914.17763.0, I still see ... as squares . I am using Korean setup.
How can I fix this issue?

I dont see this issue with IE 11.535.18362.0

**Comment by eshaseth** [comment]
@seejamescode could you please reopen and look into this issue
@joshblack , @BoldMonday please refer #110 and #160

**Comment by mjabbink** [comment]
If you're using Korean then this is not a Plex problem. We currently do not have Plex Korean.

In the next week or two we will indeed have IBM Plex Sans KR available here to download.

**Comment by johnnyshields** [comment]
Upgrading to Plex 5.0.0 fixed various issues we were having in IE11. Worth trying again.

**Comment by mjabbink** [comment]
@eshaseth We now have Plex Korean!

**Comment by mjabbink** [comment]
@eshaseth Are you still having these issues? We now have Plex Korean.
