### ISSUE TITLE
IBM Plex Mono 11 pt: i dot is off-center

### ISSUE THREAD

**Issue by uncinarynin** [IBM/plex#294]
![nicely](https://user-images.githubusercontent.com/52895942/71977362-defdcb80-3218-11ea-98df-eff6eb15cf78.png)

On Windows 10, IBM Plex Mono 11 pt looks like this. The dot of the i is off-center, right of the stem. At larger sizes it's centered (see 55 pt example) so I assume this is a hinting mistake? Would it be possible to correct this?

**Comment by BoldMonday** [comment]
Please specify exactly what application this screenshot has been taken from, what version and file format of IBM Plex Mono you are using here, and where the fonts originate from.

**Comment by vpicone** [comment]
Hey, we're going back and closing stale issues. Please feel free to reach out if you think this was closed in error!
