### ISSUE TITLE
Mono - FreeTypeError: invalid face handle

### ISSUE THREAD

**Issue by Strykar** [IBM/plex#298]
My terminal, kitty, will throw this when I specify IBM Plex Mono as the Italic and Bold Italic font to use.
```
~ kitty --session=~/.session1
fast_data_types.FreeTypeError:
Failed to set char size for non-scalable font, with error: invalid face handle
```
The Mono font itself exhibits no visual issues in spite of this message in the terminal.

**Comment by BoldMonday** [comment]
Judging by the error it sounds as an implementation problem.
Did you file this issue with the developers of Kitty?

**Comment by Strykar** [comment]
@BoldMonday I'll do that thank you.

**Comment by Strykar** [comment]
Closing this until I investigate to confirm where the issue lies.
