### ISSUE TITLE
Underline fails to skip descenders in Safari when Greek split import is present

### ISSUE THREAD

**Issue by qinyiyao** [IBM/plex#299]
Open this [CodePen](https://codepen.io/qinyiyao/pen/povmqxw) in Safari to see this:

Screenshot from Safari (13.0.4): 

<img width="344" alt="Screen Shot 2020-01-29 at 6 51 10 PM" src="https://user-images.githubusercontent.com/6311717/73416005-61cdef80-42c8-11ea-8fb3-7031c9e76d1b.png">

Chrome (79.0.3945.130) will skip the underline correctly under new versions.

To see the correct underlining behavior in Safari, remove the Greek split import or comment out its `unicode-range`. You can also comment out the whole import and use Google Fonts instead, which does not have the same splitting technique and will display the underline skipping effect correctly.

**Test Note:**

1. Safari may not load local fonts under its [Tracking Prevention Policy](https://webkit.org/tracking-prevention-policy/). Use Unpkg and Google Fonts for testing.
2. Empty Safari's cache(⌥⌘E) to keep the stylesheet fresh. 

**Temporary Fixes:**

-  Get rid of the Greek split.
-  Use Google Fonts.

**Comment by BoldMonday** [comment]
I am not an expert on css but I notice the first part of your css imports the complete Plex Sans font and then you continue to import the split fonts under the exact same name. That is not how the split fonts are supposed to work.
```
@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/complete/woff2/IBMPlexSans-Regular.woff2")
      format("woff2"),
    url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/complete/woff/IBMPlexSans-Regular.woff")
      format("woff");
}
```
Either you import the `complete` font and then all languages are included in one file. Or you import the `split` fonts in order to let the browser determine which smaller chunk to load for a particular language.

**Comment by BoldMonday** [comment]
Even stranger is that your css imports `IBMPlexSans-Regular-Cyrillic.woff2` five times in a row but with different definitions for unicode ranges.

```
@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0400-045F, U+0472-0473, U+0490-049D, U+04A0-04A5, U+04AA-04AB,
    U+04AE-04B3, U+04B6-04BB, U+04C0-04C2, U+04CF-04D9, U+04DC-04DF, U+04E2-04E9,
    U+04EE-04F5, U+04F8-04F9;
}

@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0E3F, U+2032-2033, U+2070, U+2075-2079, U+2080-2081, U+2083,
    U+2085-2089, U+2113, U+2116, U+2126, U+212E, U+2150-2151, U+2153-215E,
    U+2190-2199, U+21A9-21AA, U+21B0-21B3, U+21B6-21B7, U+21BA-21BB, U+21C4,
    U+21C6, U+2202, U+2206, U+220F, U+2211, U+221A, U+221E, U+222B, U+2248,
    U+2260, U+2264-2265, U+25CA, U+2713, U+274C, U+2B0E-2B11, U+EBE1-EBE7,
    U+ECE0, U+EFCC;
}

@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}

@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF,
    U+2C60-2C7F, U+A720-A7FF, U+FB01-FB02;
}

@font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0000, U+000D, U+0020-007E, U+00A0-00A3, U+00A4-00FF, U+0131,
    U+0152-0153, U+02C6, U+02DA, U+02DC, U+2013-2014, U+2018-201A, U+201C-201E,
    U+2020-2022, U+2026, U+2030, U+2039-203A, U+2044, U+2074, U+20AC, U+2122,
    U+2212, U+FB01-FB02;
}
```

**Comment by qinyiyao** [comment]
Oops that was a copy-and-paste mistake. I've fixed it now. [Codepen](https://codepen.io/qinyiyao/pen/povmqxw)

The problem still exists even if the complete set is disabled.

As for opting for either complete set or split set, in the [README](https://github.com/IBM/plex/blob/master/README.md): "Devs using the css files should keep the directory structure as-is so that the font files will be found." I'm assuming that's for browser [fallback](https://caniuse.com/#feat=font-unicode-range) support. 

Also Plex Sans is the only family that splits Greek. Serif and Sans Condensed do not. Not sure why.

On a trivial note, I attempted to open the font in question `IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Greek.woff2` in RoboFont but failed, except that after opening some other files, I tried to open it again and this time it mysteriously worked.

**Comment by BoldMonday** [comment]
I see the same bug in Safari 13 when trying your css example.
After doing a few tests it appears that the underline bug is related to the order in which the split fonts are imported.

**Comment by BoldMonday** [comment]
If I import the `complete` font (and not the split ones) then there is no problem at all.
This works:
```
/* Complete font */
 @font-face {
  font-family: "IBM Plex Sans";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/complete/woff2/IBMPlexSans-Regular.woff2")
      format("woff2"),
    url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/complete/woff/IBMPlexSans-Regular.woff")
      format("woff");
} 
```
This refutes the solution  _Use Google Fonts_ you proposed above.

**Comment by BoldMonday** [comment]
If I import the `split` fonts in a different order than your example then there is also no problem in Safari 13.
This works too:
```
@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Greek.woff2")
    format("woff2");
    unicode-range:  U+0384-038A, U+038C, U+038E-03A1, U+03A3-03CE;
}

@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Cyrillic.woff2")
    format("woff2");
  unicode-range: U+0400-045F, U+0472-0473, U+0490-049D, U+04A0-04A5, U+04AA-04AB,
    U+04AE-04B3, U+04B6-04BB, U+04C0-04C2, U+04CF-04D9, U+04DC-04DF, U+04E2-04E9,
    U+04EE-04F5, U+04F8-04F9;
}

@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Pi.woff2")
    format("woff2");
  unicode-range: U+0E3F, U+2032-2033, U+2070, U+2075-2079, U+2080-2081, U+2083,
    U+2085-2089, U+2113, U+2116, U+2126, U+212E, U+2150-2151, U+2153-215E,
    U+2190-2199, U+21A9-21AA, U+21B0-21B3, U+21B6-21B7, U+21BA-21BB, U+21C4,
    U+21C6, U+2202, U+2206, U+220F, U+2211, U+221A, U+221E, U+222B, U+2248,
    U+2260, U+2264-2265, U+25CA, U+2713, U+274C, U+2B0E-2B11, U+EBE1-EBE7,
    U+ECE0, U+EFCC;
}

@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Latin3.woff2")
    format("woff2");
  unicode-range: U+0102-0103, U+1EA0-1EF9, U+20AB;
}

@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Latin2.woff2")
    format("woff2");
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF,
    U+2C60-2C7F, U+A720-A7FF, U+FB01-FB02;
}

@font-face {
  font-family: "IBM Plex Split";
  font-style: normal;
  font-weight: 400;
  src: url("https://unpkg.com/@ibm/plex/IBM-Plex-Sans/fonts/split/woff2/IBMPlexSans-Regular-Latin1.woff2")
    format("woff2");
  unicode-range: U+0000, U+000D, U+0020-007E, U+00A0-00A3, U+00A4-00FF, U+0131,
    U+0152-0153, U+02C6, U+02DA, U+02DC, U+2013-2014, U+2018-201A, U+201C-201E,
    U+2020-2022, U+2026, U+2030, U+2039-203A, U+2044, U+2074, U+20AC, U+2122,
    U+2212, U+FB01-FB02;
}
```
This refutes the solution _Get rid of the Greek split_ you proposed above.

**Comment by BoldMonday** [comment]
All in all I can only conclude that the order of import for split fonts matters for certain browsers when it comes to using this underline method in css. The font files themselves are fine.

**Comment by BoldMonday** [comment]
As to your observation why only IBM Plex Sans contains a Greek split fonts: that is because language coverage is not the same across the full IBM Plex family.
Plex Sans Condensed also does not include Cyrillic, for example.

**Comment by qinyiyao** [comment]
That's perfect. The order came directly from the source CSS. Hope the fixed order goes into next release if it doesn't interfere with other things.

**Comment by BoldMonday** [comment]
Pinging @vpicone
