### ISSUE TITLE
Number tweaks, spacing, and other styles

### ISSUE THREAD

**Issue by dlewand691** [IBM/plex#301]
Working with numbers, the spacing feels a bit awkward and too loose. It could be a personal preference, too. Between the 4/5, around the 6, 8 & 9 seem the most obvious. See the comparison between Plex, Plex Text and Microsoft's Charter:

**Plex:**
![CleanShot 2020-02-12 at 10 35 18@2x](https://user-images.githubusercontent.com/1159913/74351475-267df700-4d85-11ea-9f46-14246f8ce34e.jpg)

**Plex Text:**
![CleanShot 2020-02-12 at 11 01 28@2x](https://user-images.githubusercontent.com/1159913/74352841-1b2bcb00-4d87-11ea-868a-530f5969d1ed.jpg)

**Charter:**
![CleanShot 2020-02-12 at 10 59 26@2x](https://user-images.githubusercontent.com/1159913/74352710-e881d280-4d86-11ea-8aa1-f3e43a933dd7.jpg)

Also, the arm of the 1 feels like it could be slightly shorter to balance better proportionally with the base. 

Regarding numbers as a whole, what are the thoughts around creating the other styles such as proportional oldstyle, tabular oldstyle, small-caps numerals, etc.? Having these styles will really flesh out the font to be a more complete family and usable in any media. Examples of what I'm referring to can be seen here:

https://localfonts.eu/typography-basics/glossary-of-terms/

Thanks and keep up the fantastic work, absolutely love the font.

**Comment by mjabbink** [comment]
@dlewand691 

Plex maintains the same monospacing across all eight weights.



<img width="1293" alt="Screen Shot 2020-03-08 at 8 55 10 PM" src="https://user-images.githubusercontent.com/32881239/76176528-205e1900-617f-11ea-98e5-6633751b8404.png">

**Comment by mjabbink** [comment]
The thin weight might be a bit open overall but that is the decision one makes to maintain a nice proportion and spacing between (and across) all glyphs and weights.
