### ISSUE TITLE
Some font names get trimmed in Windows Office applications

### ISSUE THREAD

**Issue by BoldMonday** [IBM/plex#302]
Font names of `IBM Plex Sans Condensed ExtraLight` and `IBM Plex Sans Condensed SemiBold` are trimmed in the font menus of MS Office on Windows.

When documents using these fonts are opened on Office for Mac then they are substituted by something else.

<img width="855" alt="word 365 win10 font menu" src="https://user-images.githubusercontent.com/13793769/74443786-0da03f00-4e74-11ea-9e11-c8796a25c207.png">

<img width="980" alt="word 2011 mac" src="https://user-images.githubusercontent.com/13793769/74443791-0f6a0280-4e74-11ea-93e0-672515a5cfa7.png">

**Cause:** Font names sorted according to the RIBBI standard on Windows are not allowed to be longer than 31 characters

**Remedy:** Shorten all font names in IBM Plex Sans Condensed family by replacing `Condensed` with `Cond`.

**Comment by mjabbink** [comment]
I think your remedy works as a good solution. Have we looked at how the below tackle this issue?

Neue Helvetica® Std 27 Condensed UltraLight
Segoe UI Condensed ExtraLight
—————————————————————
IBM Plex Sans Condensed ExtraLight
IBM Plex Sans Cond ExtraLight

**Comment by mjabbink** [comment]
I don’t get the samples above set in Plex Mono? Is that also a problem?

**Comment by BoldMonday** [comment]
> I think your remedy works as a good solution. Have we looked at how the below tackle this issue?
> Neue Helvetica® Std 27 Condensed UltraLight
> Segoe UI Condensed ExtraLight

`Segoe UI Condensed ExtraLight` is fine – the name is 29 characters long. Still below the limit of 31.

`Neue Helvetica® Std 27 Condensed UltraLight` is shown as `HelveticaNeueLT Std UltLt` (25 characters) on Windows. Information found on:
https://www.linotype.com/1264100/neue-helvetica-25-ultra-light-product.html

**Comment by BoldMonday** [comment]
> I don’t get the samples above set in Plex Mono? Is that also a problem?

I don’t know what makes MS Word decide to use Plex Mono as a substitute font in my example.
But any substitution is not desirable.

**Comment by AlsoScratch** [comment]
Maybe consider making condensed and uncondensed separate families?

**Comment by twardoch** [comment]
Word for Mac has the by far worst font support of all GUI apps on any system. It's so bad that Microsoft added to one of the earlier versions a Readme note: Microsoft Word for Mac does not support 3rd party fonts. 

The recent versions got a bit better but only a bit. Word for Mac users bizarre heuristics and an absurd mixture of different font listing methods. In sone UI items, they're listed like on Windows, in some, they're listed sort of like on a Mac. 

I spent days on several font projects trying to make them work with Word for Mac. In a few situations, I have up. Semibolds disappearing from the font menu, no style linking except between weights 400 and 700, and lots of other things. These problems are as decade old. It's amazing how they're still there. 

I'm jest saying: it's hard for a small team to cater for not just bugs, but for a complete lack of predictability of a particular app.

**Comment by AlsoScratch** [comment]
MS Word for Windows and Character Map for Windows don't do font weights justice. They don't see beyond bold and not bold.

**Comment by BoldMonday** [comment]
As @twardoch rightfully explained – the heuristics in Word for Mac for sorting the font menu are inexplicable in certain cases. It is not following the naming defined in the fonts themselves either from name table ID 1/2, nor from ID 16/17.

**Comment by BoldMonday** [comment]
@AlsoScratch The issue here is about OTF fonts on Word for Windows.
If you have different issues to report please open a new topic.

**Comment by AlsoScratch** [comment]
> Maybe consider making condensed and uncondensed separate families?

Have you considered this?

**Comment by BoldMonday** [comment]
Fixed in Plex Sans Condensed v1.2.
