### ISSUE TITLE
Add font-display: swap

### ISSUE THREAD

**Issue by dlewand691** [IBM/plex#304]
Recommend that `font-display: swap` be added to the font files.

**Comment by BoldMonday** [comment]
Please elaborate.

**Comment by dlewand691** [comment]
To improve font loading performance and reduce FOUT (flash of unsettled text), it is recommended to add this property.

**Comment by vpicone** [comment]
@dlewand691 we'd likely want to let developers chose. Google fonts does this through a url query param. 

I agree `swap` is a sensible default, but some projects might prefer the browser defaults or `fallback`.

**Comment by dlewand691** [comment]
Sure, but font-feature-values has almost no supporting browsers and adoption time is unknown. What about adding it as a variable, that way you can easily choose how you'd like to define, it at all?

**Comment by vpicone** [comment]
@dlewand691 that makes sense to me, and just have it default to `font-display: auto;`?

**Comment by dlewand691** [comment]
@vpicone Sure that'd work!

**Comment by mjabbink** [comment]
Can I close?

**Comment by Georgegriff** [comment]
What was the resolution here? How can i stop flash of unstyled text?

**Comment by vpicone** [comment]
@Georgegriff you can use font loading libraries, or regular javascript to detect for on-load events. You can also use the Plex style sheets as a template to create your own (with font display values).

The CSS working group is looking to allow font-display rules outside of font face definitions and we'd like to defer to that method if possible. I'm monitoring that progress.

**Comment by abdonrd** [comment]
@vpicone do you have any update on this? Thank you!

**Comment by ansmlc** [comment]
@vpicone Any updates on this? Thanks!
