### ISSUE TITLE
Condensed fonts not properly sorted in Word for Mac

### ISSUE THREAD

**Issue by AlsoScratch** [IBM/plex#306]
<img width="670" alt="Screenshot 2020-04-07 at 1 38 47 PM" src="https://user-images.githubusercontent.com/48752273/78647492-41846780-78ed-11ea-8c4e-f634927c643e.png">
<img width="672" alt="Screenshot 2020-04-07 at 1 39 47 PM" src="https://user-images.githubusercontent.com/48752273/78647504-447f5800-78ed-11ea-8615-4d9b3a561867.png">
I believe this can be solved by making Condensed and uncondensed separate families.

**Comment by BoldMonday** [comment]
The naming in the fonts is already set to seperate Condensed and normal width styles. This can be observed in macOS FontBook and Adobe applications, for example.

This appears to be a bug in the font sorting heuristics in Word for Mac, as explained in https://github.com/IBM/plex/issues/302#issuecomment-610218774

**Comment by BoldMonday** [comment]
Latest version of Plex Sans Condensed is sorted correctly in Word for Mac:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/13793769/84372998-40690280-abdc-11ea-8658-2ca98f106e29.png">

The issue can be closed.
