### ISSUE TITLE
Add IBM Plex KR and latest updates to Plex Sans, Mono, Serif, and Condensed

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#311]

**Comment by mjabbink** [comment]
We have new updates for
— IBM Plex Sans
— IBM Plex Mono
— IBM Plex Condensed

All new
— IBM Plex Sans KR

**Comment by BoldMonday** [comment]
And a minor update to IBM Plex Serif.

**Comment by vpicone** [comment]
@BoldMonday the box folder has the most up to date for all of these correct?

**Comment by BoldMonday** [comment]
@vpicone I sent you and Mike an email on 29 April with links to all the updated files in Box

**Comment by viznov** [comment]
Please share with us.

**Comment by elfhazard** [comment]
I am very excited. I want to meet Korean fonts quickly.

**Comment by mjabbink** [comment]
@vpicone Super priority

**Comment by vpicone** [comment]
@mjabbink im on vacation, will take it first thing next week.

**Comment by mjabbink** [comment]
@vpicone enjoy! I totally forgot you were out.

**Comment by johnnyshields** [comment]
Looking forward to getting Korean soon, thank you Plex team!

**Comment by elfhazard** [comment]
What is the problem with the release? According to Twitter, it should already have been released last week, so I'm curious.

**Comment by viznov** [comment]
> 
> 
> What is the problem with the release? According to Twitter, it should already have been released last week, so I'm curious.

The problem is simple, just nobody cares.

**Comment by mjabbink** [comment]
@viznov We care more than you can fathom.

**Comment by viznov** [comment]
> 
> 
> @viznov We care more than you can fathom.

I see.

**Comment by johnnyshields** [comment]
Any approximate revised ETA? We are really looking forward to this.

**Comment by mjabbink** [comment]
@johnnyshields After a lot of hard work and problem solving to sort out this huge release @vpicone released today.

**Comment by johnnyshields** [comment]
Thank you, I've already tested 5.0.0 and pushed to production in my app! Looks great.
