### ISSUE TITLE
Add IBm Sans Plex CJK font

### ISSUE THREAD

**Issue by charles-github1** [IBM/plex#312]
Please add Sans CJK font , need it for generating pdf

**Comment by mjabbink** [comment]
We are developing this now. Korean available in the next week or two and Japanese early 2021. Chinese will be end of 2022.

**Comment by eisoch** [comment]
Who are the font designers for the CJK ones? 🤔


On 05/10/2020 12:03, Mike Abbink wrote:

We are developing this now. Korean available in the next week or two and Japanese early 2021. Chinese will be end of 2022.
