### ISSUE TITLE
Add zero-width space

### ISSUE THREAD

**Issue by AlsoScratch** [IBM/plex#318]
Sorry forgot to mention in #317 but U+200B (zero-width space) is useful for strings like "Yes/No/Maybe" if you want each word to separate into new lines.

**Comment by BoldMonday** [comment]
The fact that the glyph in question does not exist in the font does not by definition mean that it will not be rendered. There are environments that use fallback fonts in this case, or applications such as Adobe InDesign are able to synthesize these kinds of spaces by themselves.

**Comment by johnnyshields** [comment]
Without use of fallback, how does it appear in plex? As tofu?

**Comment by BoldMonday** [comment]
Probably. Without fallback *any glyph* that is non-existent should be displayed with the .notdef character (AKA “tofu”).

**Comment by johnnyshields** [comment]
Would be worthwhile to properly handle all the ZWJ / ZWNJ characters maybe as part of the Math Symbols project?

**Comment by BoldMonday** [comment]
> Would be worthwhile to properly handle all the ZWJ / ZWNJ characters maybe as part of the Math Symbols project?
That could be a consideration.

FWIW – ZWJ and ZWNJ are currently included in Plex Sans Thai (Looped) and Plex Sans Devanagari.

**Comment by AlsoScratch** [comment]
> Perhaps. But when I use a zero width space with Plex in a macOS application such as TextEdit then I see no problem.

I can't trust every application to use a fallback font... but those that do shouldn't matter, probably.

**Comment by mjabbink** [comment]
Could be consideration for Plex Math but tabled for now.

**Comment by tay1orjones** [comment]
Hey there! [v6.1.0](https://github.com/IBM/plex/releases/tag/v6.1.0) was just released that references this issue. 

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/468) to provide feedback or voice concerns. Thanks!

**Comment by tay1orjones** [comment]
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!
