### ISSUE TITLE
IBM Plex Sans Mono KR

### ISSUE THREAD

**Issue by hwooo** [IBM/plex#319]
IBM Plex Sans KR font is very useful, it's not a monospace font. Is there any plan to release Plex Sans Mono KR?

**Comment by johnnyshields** [comment]
Do the hangul glyphs themselves render with same horizontal width?

**Comment by hwooo** [comment]
If you mean IBM Plex Sans KR, no, it's doesn't.

**Comment by mjabbink** [comment]
The KR glyphs themselves are all in the same width.
