### ISSUE TITLE
Add an OpenType alternative to the uppercase Q

### ISSUE THREAD

**Issue by tomcalabrese** [IBM/plex#320]
Hello!

I've spent a couple weeks researching different typefaces for the non-profit I work at with the goal of finding a typeface that is as accessible as possible for the students and teachers we serve. The things I like about IBM Plex Sans the most is that it supports many languages, it differentiates between `i, l, 1`. However, the main drawback for our organization is that our name is Quill and the `Q` for IBM Plex Sans is not the most legible. It would be amazing if there was an alternate to the uppercase q in the open type features that has the tail of the q cross the circle. 

Thank you for creating a wonderful typeface!

![Artboard](https://user-images.githubusercontent.com/8131465/84808599-e3ec5580-afd6-11ea-8f6b-20f7b7e14313.png)

<img width="883" alt="Screen Shot 2020-06-16 at 1 39 42 PM" src="https://user-images.githubusercontent.com/8131465/84808612-e9e23680-afd6-11ea-982f-f2854b1b2d58.png">

**Comment by mjabbink** [comment]
It may not be the most legible but I believe it’s very very legible. From left to right: Plex, Apple SF, Myriad, Source Sans, Arial, Roboto

—————


<img width="906" alt="Screen Shot 2020-06-18 at 6 53 01 PM" src="https://user-images.githubusercontent.com/32881239/85082618-1e035600-b195-11ea-8651-8a31eea3ce9d.png">

**Comment by mjabbink** [comment]
<img width="1036" alt="Screen Shot 2020-06-18 at 6 57 34 PM" src="https://user-images.githubusercontent.com/32881239/85082801-9a963480-b195-11ea-983a-1b184059549a.png">
