### ISSUE TITLE
Condensed monospace

### ISSUE THREAD

**Issue by moconnor1234** [IBM/plex#321]
Are there plans to produce a condensed version of IBM Plex Mono at some point?

**Comment by SerLinkzero** [comment]
A 0.5 em wide variation will be great as this ensures perfect alignment with CJK characters.

**Comment by mjabbink** [comment]
NOt in our near future given Plex CJK development, Plex Tamil and Plex Math in our horizon. Closing for now but added to a growing list of considerations.
