### ISSUE TITLE
Possible to make tilde easier to distinguish from hyphen?

### ISSUE THREAD

**Issue by qvacua** [IBM/plex#322]
Plex Mono Regular 13pt is my default fixed-width font on macOS. Oftentimes I wished that the tilde `~` would be more "wavy" such it is more easily distinguishable from the hyphen `-` (see also the attached comparison between Iosevka and Plex). I may be the only one who wants this and if so, please ignore :)

<img width="182" alt="Screenshot 2020-06-19 at 12 32 40" src="https://user-images.githubusercontent.com/460034/85124015-8439b880-b229-11ea-92f7-48420b98b8d0.png">

**Comment by mjabbink** [comment]
This could be a nice enhancement @BoldMonday when we do another update to Plex Mono. Let’s discuss.

**Comment by mjabbink** [comment]
@BoldMonday I think this is something we can get into the mix in the coming weeks.

**Comment by BoldMonday** [comment]
Yes. This will be in the next update for Plex Mono.

**Comment by BoldMonday** [comment]
Current status for `asciitilde` (old version top, new version below)

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/13793769/109943387-6fc51f80-7cd5-11eb-913e-6da3fd3d8447.png">
Update to the fonts will be submitted somewhere in the coming weeks.

**Comment by mjabbink** [comment]
Big improvement.

**Comment by qvacua** [comment]
Very nice!

**Comment by krish-r** [comment]
Hello, 
Sorry for commenting in a closed bug, is this enhancement going to be a part of future release? Because Release 5.2.1 (Plex Mono version 2.1) still contains the older form of `~`.

**Comment by BoldMonday** [comment]
Improved tilde is part of Plex Mono version 2.2 and these files have been delivered to IBM already.
As external contractor I cannot comment on when they will be merged with this repository though.

**Comment by mjabbink** [comment]
@vpicone I though the Plex Mono update was already released? If not can we please get that expedited in the upcoming releases you’re working on. The Mono has been needing these updates for quite some time.

**Comment by mjabbink** [comment]
@krish-r — This should cover it but let us know. https://github.com/IBM/plex/releases/tag/v6.0.0-next.6

**Comment by krish-r** [comment]
Thanks @mjabbink. I installed the mono font from your release, but I still don't see any change. (The font version is also 2.1).

![image](https://user-images.githubusercontent.com/54745129/128972605-01755503-586f-4ab9-b548-213eb96b70b9.png)

**Comment by mjabbink** [comment]
FYI @vpicone @BoldMonday

**Comment by BoldMonday** [comment]
@mjabbink The pre-release linked above still contains v2.1 of Plex Mono.

**Comment by mjabbink** [comment]
@vpicone See above. Can we get the latest Mono included in the pre-release. @BoldMonday assuming it’s v2.2 of Plex Mono

**Comment by mjabbink** [comment]
oh nice! I was thinking that was coming so soon. @vpicone I think for this a delay is ok so we can include v2.3.

**Comment by BoldMonday** [comment]
Improved `asciitilde` is now available in Plex Mono v2.3 (part of [Release v6.0.0](https://github.com/IBM/plex/releases/)).
