### ISSUE TITLE
IBM Plex Sans KR not grouped into familiy

### ISSUE THREAD

**Issue by Quiple** [IBM/plex#326]
![주석 2020-06-28 225604](https://user-images.githubusercontent.com/11014257/85949577-8f5fb780-b992-11ea-82de-10bdd43f8250.png)
Only Regular and Bold are grouped into familiy, and the rest of the weights are separated.

**Comment by BoldMonday** [comment]
Certain platforms only allow families to be grouped in a limited way: Regular, Italic, Bold, and Bold Italic. On those platforms IBM Plex Sans KR Regular and Bold are grouped.

On other platforms such as macOS all weights are grouped together.

**Comment by Quiple** [comment]
> Certain platforms only allow families to be grouped in a limited way: Regular, Italic, Bold, and Bold Italic. On those platforms IBM Plex Sans KR Regular and Bold are grouped.
> 
> On other platforms such as macOS all weights are grouped together.

![주석 2020-06-29 030616](https://user-images.githubusercontent.com/11014257/85954869-88966c00-b9b5-11ea-8b5f-8c1fbb4cbcf7.png)
Other IBM Plex fonts are grouped properly. I wonder why only KR fonts cause this problem.

**Comment by BoldMonday** [comment]
Can you supply more specifics: from what application and platform are the screenshots in question?

**Comment by Quiple** [comment]
> Can you supply more specifics: from what application and platform are the screenshots in question?

I'm using Windows 10. These screenshots are from `C:\Windows\Fonts`.

**Comment by BoldMonday** [comment]
Thank you. We'll investigate.

**Comment by BoldMonday** [comment]
Confirmed. Apparently the fonts in question contain incorrect ID 21/22 entries in the `name` table.
These entries are not necessary and can be removed completely.

**Comment by Quiple** [comment]
Thanks for your handling!

**Comment by BoldMonday** [comment]
FYI – a new Plex update has been released yesterday and the problem in questions should be solved now.
This issue can be closed.
