### ISSUE TITLE
IBM Plex Sans KR missing css and scss

### ISSUE THREAD

**Issue by esd-ches** [IBM/plex#327]
I installed IBM Plex via "npm install @ibm/plex", but unfortunately the scss folder does not include a folder "sans-kr", nor does the css file include a font-face with the corresponding font-family definition.

![image](https://user-images.githubusercontent.com/15119524/86007905-5ec26100-ba18-11ea-84e1-41000d0a4703.png)

**Comment by vpicone** [comment]
Korean has far more font files/unicode ranges than the other languages. This is a work in progress and should be resolved soon.

**Comment by esd-ches** [comment]
Thanks alot for the quick response. I am very much looking forward to the update.

**Comment by hwoongkang** [comment]
I am really looking forward to this update. 👀

**Comment by vpicone** [comment]
@hwoongkang its shipped!
