### ISSUE TITLE
Support for ligatures

### ISSUE THREAD

**Issue by 0xflotus** [IBM/plex#328]
Is there any support for ligatures planned?

**Comment by BoldMonday** [comment]
Plex Sans Arabic has a multitude of ligatures. :)

Please elaborate what kind of ligatures you are referring to.

**Comment by 0xflotus** [comment]
Ah yes I didn't recognized, there are a ton of possible ligatures. I thought of `fi`, `->`, `<-`, `=>`, `<=`, ´<=>´, etc. eg.

**Comment by BoldMonday** [comment]
Adding so called "programming ligatures" has already been discussed in https://github.com/IBM/plex/issues/63.

This issue can be closed.
