### ISSUE TITLE
[Korean]: hinted files missing thin weight

### ISSUE THREAD

**Issue by vpicone** [IBM/plex#332]
- [hinted](https://github.com/IBM/plex/tree/master/IBM-Plex-Sans-KR/fonts/complete/woff2/hinted)

- [unhinted](https://github.com/IBM/plex/tree/master/IBM-Plex-Sans-KR/fonts/complete/woff2/unhinted)

**Comment by BoldMonday** [comment]
AFAIK it has been a conscious decision by @mjabbink and Sandoll not to hint the Thin weight.

**Comment by mjabbink** [comment]
The sizes that perform well and are legible in the thin weight do not require any hinting.

**Comment by vpicone** [comment]
@mjabbink @mjabbink when someones grabbing all the font files to load into a website or install on their device, they pick between 'hinted' and 'unhinted'. If they go to the 'hinted' directory now and grab all the files, it will be missing the thin weight.

If hinting doesn't make a difference for the Thin weight, can we just put the unhinted, Thin font file in the hinted source directory so it's not missing from that group?

**Comment by mjabbink** [comment]
I see. Then you can include the unhinted Thin with the hinted files.

**Comment by mjabbink** [comment]
It would be a waste of time and a lot of money to hint the thin weights in CJK. Thin weights should never be used at the sizes that would require hinting. The ideal size ranges for thin to be legible do not require hinting. The best solution is to do the above approach to include the Thin non-hinted inside the Hinted folder.

**Comment by vpicone** [comment]
@BoldMonday to follow up, like Mike mentioned I'm going to commit the `unhinted`, `Thin` files to the `hinted` directories so they both have the full range of font weights. I'm not sure if you want to do the same in dropbox or make a note for future Korean updates?

I think this is the right move both for generating styles programmatically and for providing all the expected font files for a given directory.
