### ISSUE TITLE
[Arabic] Possible to disable the included logographs?

### ISSUE THREAD

**Issue by barmadrid** [IBM/plex#336]
It seems that certain Arabic words are written (rendered) as logograph, for example the word محمد (Muhammad) below:

![Screenshot from 2020-08-17 15-19-24](https://user-images.githubusercontent.com/61072940/90435723-678cf600-e09d-11ea-9b73-5c40cbb6eeca.png)

Compared to normal (non logograph) version as in Noto Sans Arabic:

![Screenshot from 2020-08-17 15-19-50](https://user-images.githubusercontent.com/61072940/90435803-8d19ff80-e09d-11ea-98d2-b5c5a5daad22.png)

Can we disable this at build/run time?

**Comment by BoldMonday** [comment]
The inclusion of the `Muhammad` glyph was a conscious decision by the designers of Plex Sans Arabic. There are no options to control the behaviour of glyph substitutions during build/run time and I’m not sure there will be.

**Comment by johnnyshields** [comment]
is it possible to disable the logographs with a zero-width joiner char?

**Comment by waelmorcos** [comment]
We have an update coming soon that should make this ligature optional. 
In the meantime you can add a Madda anywhere in the word and the ligature would be dis-activated.

**Comment by barmadrid** [comment]
Wonderful news @waelmorcos Thank you!

**Comment by johnnyshields** [comment]
Will non-logograph be default?

**Comment by waelmorcos** [comment]
Yes

**Comment by mjabbink** [comment]
thanks @waelmorcos

**Comment by mjabbink** [comment]
@waelmorcos @BoldMonday should this issue close?

**Comment by BoldMonday** [comment]
@mjabbink Fixed in latest Arabic update. Issue can be closed.

**Comment by BoldMonday** [comment]
Fixed in Plex Sans Arabic v1.2 (part of [Release v6.0.0](https://github.com/IBM/plex/releases/)).
