### ISSUE TITLE
IBM Plex Variable in indesign: when dragging slider font is swapping style

### ISSUE THREAD

**Issue by RafalBuchner** [IBM/plex#337]
I've been testing some stuff with IBM plex Variable in InDesign, and I realised that when I select any italic style and starting to drag the weight axis slider, it swaps back to the roman style, at given slider's axis value.

I had no such issue with adobe variable fonts.

**Comment by tristan957** [comment]
@BoldMonday looking forward to the next IBM Plex Sans Var update. Thanks :)

**Comment by tay1orjones** [comment]
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!
