### ISSUE TITLE
Curly quotes are nearly indistinguishable in Plex Mono.

### ISSUE THREAD

**Issue by runrin** [IBM/plex#342]
I have small a perl script that changes typewriter quotes to curly quotes for typesetting purposes. It was very difficult to verify that the script worked correctly in my terminal because the left and right curly quotes are so similar. I ended up needing to use a different font to be certain no mistakes had been made.

I am not sure if this causes issues for others, as curly quotes are rarely used in programming, but for my workflow (graphics, typesetting) it is an issue.

**Comment by mjabbink** [comment]
@runrin The quotes and apostrophes were a deliberate design choice. As you can see below in a few examples of other typeface designs that have also included a less “curly” approach. Plex Mono is primarily used for coding where the straight quotes are typically used but for typesetting we opted for the less curly approach like you see in Verdana and Apple SF.


<img width="790" alt="Screen Shot 2020-09-29 at 3 27 18 AM" src="https://user-images.githubusercontent.com/32881239/94532773-e7ad8c00-0203-11eb-8cca-37133b0342b9.png">

**Comment by mjabbink** [comment]
We will consider the option to create more contrast between them but closing for now.
