### ISSUE TITLE
Problems with Figma

### ISSUE THREAD

**Issue by pattpakdee** [IBM/plex#348]
Glyphs are overlapped when used in certain sizes and weights.  As far as I have tested, this problem is encountered only in Figma.  The fonts display well in other apps such as pages and Adobe apps.

<img width="625" alt="Screen Shot 2563-11-02 at 10 23 38" src="https://user-images.githubusercontent.com/21189362/97827311-77a88f00-1cf6-11eb-9b91-818723cd1546.png">

**Comment by BoldMonday** [comment]
Did you raise this issue with Figma?

**Comment by mjabbink** [comment]
And is the same issue happening with other Thai script fonts?
