### ISSUE TITLE
Broken rendering of Cyrillic in new version on Windows

### ISSUE THREAD

**Issue by Strannikus** [IBM/plex#349]
Hello! There are some issues with IBM Plex Serif (Regular, Bold and both italics) in comparison of more early releases of main font weight in Windows font viewer. It seems other software treating these fonts Ok. No issues with the rest font styles.
<details>
 <summary>How it looks like</summary>

![2020-11-08_211022](https://user-images.githubusercontent.com/26332718/98479077-29205680-2208-11eb-8bb2-0aabad1b55ff.png)
![2020-11-08_211023](https://user-images.githubusercontent.com/26332718/98479076-27ef2980-2208-11eb-93bb-442badcce125.png)
</details>

At least in [latest 5.1.3 release](https://github.com/IBM/plex/releases/tag/v5.1.3).

**Comment by BoldMonday** [comment]
Thank you for the report. Two questions:
1. Does this issue happen with the TrueType (TTF) versions of Plex Serif too?
2. Can you provide more details about the operating system?

**Comment by Strannikus** [comment]
Thank you for this extremely nice font family! :^)

1. Yes. But it shows different senseless letters. And also only with this mentioned above group. Light, Thin, Medium — no issues. Something happens between v2.1—2.6 releases.
2. Windows 10 x64 build 17763.1553
<details>
 <summary>pics</summary>

![2020-11-09_214723](https://user-images.githubusercontent.com/26332718/98587526-52f67d80-22db-11eb-91a6-7048cf1a96c2.png)

</details>

**Comment by BoldMonday** [comment]
I suspect that the issue you are experiencing is a font caching problem.
Removing the Windows global font cache at  `\Windows\System32\FNTCACHE.DAT` might be a remedy in that case.

Unfortunately I am not able to reproduce the issue on the Windows 10 installation here. A quick check of the unicode mapping in the fonts in question also did not show any errors.
The major differences between version 2.1 and 2.6 are a change in metrics, and the removal a number of private glyphs containing IBM logos.

<img width="2231" alt="image" src="https://user-images.githubusercontent.com/13793769/98662272-d6e64f00-2347-11eb-8c43-54c1347189a0.png">

**Comment by Strannikus** [comment]
It seems problem is in something else. I deleted `fntcache.dat` file and rebooted the system, but nothing happened. I have to mention all these fonts are not installed in system and just located in my private font collection folder — I just press click to open.

It's really strange, the problem touches only 4 fonts but has no affection on other including Plex Sans family. Probably this is Cyrillic subset issue only (but notice: ttf and otf files show different signs in a pangram «съешь еще этих французских булок да выпей чаю»).

**Comment by BoldMonday** [comment]
I still suspect this is a caching issue with Windows Font Viewer because technically I can find no differences between the Regular/Italic/Bold/Bold Italic styles and the other styles in IBM Plex Serif.

**Comment by mjabbink** [comment]
Should this close @BoldMonday?

**Comment by BoldMonday** [comment]
@mjabbink I think yes. We're unable to replicate the issue and therefore I suspect the issue is caused by something else than the font.
