### ISSUE TITLE
Missing overline character

### ISSUE THREAD

**Issue by kauesena** [IBM/plex#351]
In IBM plex mono, the overline character ( ‾, U+2054) seems to be missing though underline _ is present. That is a useful character for fake-underlining in plain text files.

**Comment by mjabbink** [comment]
@BoldMonday any thoughts on this?

**Comment by BoldMonday** [comment]
We'll add it to the list of future improvements.
I assume the original poster refers to character U+203E. Character U+2054 is ⁔.
