### ISSUE TITLE
[Plex] Update image in Plex mini site - Gallery page

### ISSUE THREAD

**Issue by SimonaTimofeiMarin** [IBM/plex#352]
Hi!
The screenshot below is with the existing image and needs to be replaced with the second one.

<img width="753" alt="Screen Shot 2020-12-03 at 6 40 23 PM" src="https://user-images.githubusercontent.com/66475221/101060061-a638b480-3597-11eb-9d52-78363c33c073.png">

![IBM_D_ Posters_All _R05-Plex mini-site gallery page](https://user-images.githubusercontent.com/66475221/101060081-ab95ff00-3597-11eb-97ef-58291252045f.jpg)

A box link for the updated image:
https://ibm.box.com/s/6rovjdyyuntl8h01hukvauo9o7h1wunl

Thank you!

**Comment by Palke** [comment]
PR open: https://github.ibm.com/brand/plex/pull/68/files

@SimonaTimofeiMarin

**Comment by SimonaTimofeiMarin** [comment]
An updated Box link for the new image.
https://ibm.box.com/s/ii2i8at40ktax800b67faejk0kojotrj
Thank you!

**Comment by SimonaTimofeiMarin** [comment]
Hi, @vpicone, 
I've updated the Box link. The previous one expired.
https://ibm.box.com/s/ii2i8at40ktax800b67faejk0kojotrj
Thank you!

**Comment by Palke** [comment]
Hi @SimonaTimofeiMarin is the image same as the one from previous link? If yes, it was already updated and will be promoted soon. Thanks.

**Comment by SimonaTimofeiMarin** [comment]
Hi @Palke @vpicone,
Is the same image.
Thank you!

**Comment by mjabbink** [comment]
@vpicone Let’s add this to next sprint

**Comment by mjabbink** [comment]
@vpicone ☝️

**Comment by Katie-A-IBM** [comment]
@vpicone Hey Vince, Can you do this quickly, so we can close out? I would be most grateful. Or @Palke Do you have access to do this?
fyi @alisonjoseph

**Comment by Palke** [comment]
> https://github.ibm.com/brand/plex/pull/68

Hi @Katie-A-IBM this has been already addressed in the PR from the previous comment. I had done the update and PR in Plex site repository as this one is for the font.

Can be closed! :)

**Comment by Katie-A-IBM** [comment]
@Palke Thank you.
@mjabbink This was completed using a different issue.
See here 
https://www.ibm.com/plex/gallery/

**Comment by Katie-A-IBM** [comment]
@SimonaTimofeiMarin I'm not allowed to close this issue. Would you please close? Thanks
