### ISSUE TITLE
IBM Plex Sans Regular font doesn’t work on iOS

### ISSUE THREAD

**Issue by presscorp** [IBM/plex#356]
IBM Plex Sans 'Regular' doesn't properly applied on iOS when using in UI. Seems like iOS can't correctly read the file. At runtime font is successfully loaded but iOS displays default system font instead. I tried different (applicable for iOS) font file extensions from different sources including Google Fonts and original IBM website. The rest of the font styles (Light, Thin, Bold, Semibold, ...) are correctly displayed.

**Comment by mgan59** [comment]
I'm having a similar issue, but the `Light` at `font-weight: 100` not working on iOS, but works on desktop chrome... 🤷‍♂️

**Comment by mjabbink** [comment]
Hmm. I cannot reproduce this so we’ll need more details to explore further. Several thousand people are using Plex on iOS daily and we have not heard this issue come up.

— Did you download from IBM Plex Github repo?
— What version of Plex are you using?
— Which file type are you using? Opentype or TrueType?
— What OS version
— Which software?

Please download from here: https://github.com/IBM/plex/releases/tag/v5.1.3

**Comment by daveharig** [comment]
I can't get any IBMPlexSans to display in Xcode13/iOS12.  Tried OTF and TTF downloads directly from GitHub repo.  Double checked file name and put two other sets of eyes on it.  We're all stumped.  All other fonts work in this same project.  Something is defiantly wrong with this font family.

**Comment by daveharig** [comment]
Nearly the same issue. IBMPlexSans, GitHub Downloaded on 3/22/2022. Regular and SemiBold, Size 15-19, OTF, Xcode13, iOS12.  The fonts render identically.  Have tried TTF also, no change.  "IBMPlexSans won't render on _____"  is an alarming common Google search.

**Comment by BoldMonday** [comment]
@daveharig Can you provide a step-by-step procedure how to replicate the issue?
Does the issue also occur on the current version of iOS (15)?

**Comment by presscorp** [comment]
> Nearly the same issue. IBMPlexSans, GitHub Downloaded on 3/22/2022. Regular and SemiBold, Size 15-19, OTF, Xcode13, iOS12.  The fonts render identically.  Have tried TTF also, no change.  "IBMPlexSans won't render on _____"  is an alarming common Google search. 
> 
> 
> 
> 
> 
> 
> 
> 

I actually fixed it by using correct font name during the file read. Earlier I used "IBMPlexSans-Regular" name, then I changed it to "IBMPlexSans". Worked!

**Comment by mgan59** [comment]
hehehe I had to come back here and read the comments again.  And now I remember, my problem was the linking using a google-font loader.  Which I fixed at the time, but knew others would end up here from a google-search, so why I left my initial comments.  Think it can be marked fixed.  And for those landing here experience this issue and using a google-font loader, just _triple_ check how you're linking it in your `<head><link ... /></head>`

**Comment by daveharig** [comment]
@BoldMonday  Steps --> https://www.loom.com/share/2067f860f0df4e2da2152805bf1867d6

**Comment by daveharig** [comment]
@BoldMonday Steps --> https://www.loom.com/share/25fcc4156c764da2897d660ae6651901

**Comment by daveharig** [comment]
> > Nearly the same issue. IBMPlexSans, GitHub Downloaded on 3/22/2022. Regular and SemiBold, Size 15-19, OTF, Xcode13, iOS12.  The fonts render identically.  Have tried TTF also, no change.  "IBMPlexSans won't render on _____"  is an alarming common Google search.
> 
> I actually fixed it by using correct font name during the file read. Earlier I used "IBMPlexSans-Regular" name, then I changed it to "IBMPlexSans". Worked!


I have tried every permutation of file name, OTF, TTF, new project, different Xcode environment, downloads from GitHub and Google.  Regular and SemiBold render identical.  https://www.loom.com/share/25fcc4156c764da2897d660ae6651901

**Comment by BoldMonday** [comment]
@daveharig Thanks for the recording!
Try to use the following names in your code when using IBM Plex Sans:
```
IBMPlexSans-Thin.otf               "IBMPlexSans-Thin"
IBMPlexSans-ThinItalic.otf         "IBMPlexSans-ThinItalic"
IBMPlexSans-ExtraLight.otf         "IBMPlexSans-ExtLt"
IBMPlexSans-ExtraLightItalic.otf   "IBMPlexSans-ExtLtItalic"
IBMPlexSans-Light.otf              "IBMPlexSans-Light"
IBMPlexSans-LightItalic.otf        "IBMPlexSans-LightItalic"
IBMPlexSans-Regular.otf            "IBMPlexSans"
IBMPlexSans-Italic.otf             "IBMPlexSans-Italic"
IBMPlexSans-Text.otf               "IBMPlexSans-Text"
IBMPlexSans-TextItalic.otf         "IBMPlexSans-TextItalic"
IBMPlexSans-Medium.otf             "IBMPlexSans-Medm"
IBMPlexSans-MediumItalic.otf       "IBMPlexSans-MedmItalic"
IBMPlexSans-SemiBold.otf           "IBMPlexSans-SmBld"
IBMPlexSans-SemiBoldItalic.otf     "IBMPlexSans-SmBldItalic"
IBMPlexSans-Bold.otf               "IBMPlexSans-Bold"
IBMPlexSans-BoldItalic.otf         "IBMPlexSans-BoldItalic"
```

**Comment by daveharig** [comment]
@mjabbink That works!   Is it customary to have the font names carry like this?

**Comment by daveharig** [comment]
> > Nearly the same issue. IBMPlexSans, GitHub Downloaded on 3/22/2022. Regular and SemiBold, Size 15-19, OTF, Xcode13, iOS12.  The fonts render identically.  Have tried TTF also, no change.  "IBMPlexSans won't render on _____"  is an alarming common Google search.
> 
> I actually fixed it by using correct font name during the file read. Earlier I used "IBMPlexSans-Regular" name, then I changed it to "IBMPlexSans". Worked!

Thanks.  Regular was working for me even with "IBMPlexSans-Regular" name I did not think we had the same issue.  Turns out you need the cheat codes above to use this font.

**Comment by daveharig** [comment]
@BoldMonday Thank you!  I learned something new.  Would you guys ever consider a consistent naming convention and nomenclature?

**Comment by BoldMonday** [comment]
@daveharig There is a technical reason why the naming has been done this way. Changing it would break certain interoperability.

**Comment by daveharig** [comment]
Makes sense.  Thank you again.

**Comment by kenmcd** [comment]
> @daveharig There is a technical reason why the naming has been done this way. Changing it would break certain interoperability.

Could you please elaborate on that a bit?
I am well aware of how the PostScript name is used in PDFs, etc.
But specifically I wonder why sometimes the Regular is missing any suffix.
Such as just "IBMPlexSans" for the regular weight.
I have seen this in some other fonts (e.g. ArialMT) and wondered why.
Thanks.
