### ISSUE TITLE
Hair space (U+200A) not supported

### ISSUE THREAD

**Issue by jfrech** [IBM/plex#361]
IBM Plex Sans Condensed Regular does not support unicode code point `U+200A`, the hair space:

```
% fc-query --format='%{charset}\n' =(curl -fsSL https://github.com/IBM/plex/raw/master/IBM-Plex-Sans-Condensed/fonts/complete/ttf/IBMPlexSansCondensed-Regular.ttf) | grep -o ' 1ea0-1ef9 2013-2014 '
 1ea0-1ef9 2013-2014 
```

I would appreciate not to have to include another font in my font stack to know for certain which hair space is displayed.

**Comment by mjabbink** [comment]
@BoldMonday WE should include this in the next release.

**Comment by tay1orjones** [comment]
Hey there! [v6.1.0](https://github.com/IBM/plex/releases/tag/v6.1.0) was just released that references this issue. 

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/468) to provide feedback or voice concerns. Thanks!

**Comment by tay1orjones** [comment]
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!
