### ISSUE TITLE
TTF internal font names.

### ISSUE THREAD

**Issue by wfcloherty** [IBM/plex#365]
The Bold and Regular weight True Type Fonts have the font family name as the font name. Example, 'IBM Plex Mono Bold' has the font name 'IBM Plex Mono.  The other fonts in the font family have the weight in the font name.  Example, 'IBM Plex Mono Thin' has the font name 'IBM Plex Mono Thin'. This issue is in at least the Mono, Serif, Sans-Serif, & Sans-Serif Condensed font families in both normal and italic forms. 

I used the system font viewer of Windows 10 Home, Version 20H2, to examine the internal font names of release 5.1.3 of the fonts.

**Comment by BoldMonday** [comment]
Yes, this is on purpose and also the case for _IBM Plex Mono Italic_ and _IBM Plex Mono Bold Italic_.

It is done for the purpose of [style-linking](https://www.adobe.com/support/techdocs/328508.html).
