### ISSUE TITLE
Too low "i" dot with bold font in certain sizes.

### ISSUE THREAD

**Issue by ro-i** [IBM/plex#368]
Hi :)

I really like your font and installed it on my Linux System (Fedora 34) using the latest release of the TrueType files (https://github.com/IBM/plex/releases/download/v5.1.3/TrueType.zip).
There is, however, one tiny issue: in certain sizes the "i" dot of the bold font seems to be placed too low and is no longer clearly visible:
![Screenshot from 2021-05-13 18-28-01](https://user-images.githubusercontent.com/50044286/118156628-decb9c80-b419-11eb-8f4b-03971d8acb16.png)

Is this something you could fix, or do you think it is a problem with my font rendering?

Thanks :heart:

**Comment by BoldMonday** [comment]
There have been several discussions about the best setting for font rendering on Linux.
A lot of these things are beyond control of the Plex fonts themselves.
Please have a look at https://github.com/IBM/plex/issues/103 and https://github.com/IBM/plex/issues/198.
