### ISSUE TITLE
Incorrect display of U+01D9 and U+01DA

### ISSUE THREAD

**Issue by reuniclus** [IBM/plex#369]
The characters “Ǚ” (U+01D9) and “ǚ” (U+01DA) display incorrectly, with the caron diacritic moved to the right

![image](https://user-images.githubusercontent.com/12959056/118378739-668ce480-b59b-11eb-9985-20bca9e49086.png)

**Comment by kenmcd** [comment]
01D9 does not exist in IBM Plex Mono or IBM Plex Serif.
So what ever is display is being created by the application.

01D9 does exist in IBM Plex Sans, and it appears correctly for me in the font editors and LibreOffice.

**Comment by mjabbink** [comment]
IBM Plex Sans

<img width="229" alt="Screen Shot 2021-06-02 at 10 08 51 AM" src="https://user-images.githubusercontent.com/32881239/120505559-b08f0c00-c38a-11eb-85d9-d4fd96e5553f.png">

**Comment by mjabbink** [comment]
@BoldMonday Let me know if I should reopen.
