### ISSUE TITLE
Some of the Devanagari OTF files seem to be corrupt

### ISSUE THREAD

**Issue by ducksick** [IBM/plex#374]
I haven’t yet tried previewing the other language-specific OTF files, but when i double-click on

IBMPlexSansDevanagari-ExtraLight.otf
IBMPlexSansDevanagari-SemiBold.otf

I get an error message that they are »not a valid font file«. I run Windows 7 x64. The other weights open fine without issues.
![Screenshot_4](https://user-images.githubusercontent.com/84545753/120879669-5af27380-c5c5-11eb-820c-192f3fef6ff8.png)

**Comment by BoldMonday** [comment]
Indeed there is an error in some of the font info fields of those files.
It has been fixed and updated files will be released soon.

FWIW: the Plex Sans Devanagari TTF fonts should work correctly.

**Comment by ducksick** [comment]
yes, the TTF files are fine. thanks for the quick response!

**Comment by mjabbink** [comment]
@BoldMonday I believe this is addressed in the release @vpicone is currently working on.

**Comment by BoldMonday** [comment]
@mjabbink Yes. Fixed files have been delivered.

**Comment by cameosis** [comment]
the OTF files are still corrupt.

**Comment by BoldMonday** [comment]
The issue has been fixed in IBM Plex Sans Devanagari v1.2. But the files in this repository might not have been updated yet.

**Comment by mjabbink** [comment]
@vpicone
