### ISSUE TITLE
The "f" and "l" in IBM Plex Serif will be connected together in one word

### ISSUE THREAD

**Issue by 132112maker** [IBM/plex#378]

**Comment by mjabbink** [comment]
@132112maker That is called a “ligatures” if it’s the default it means you have that setting turned on in preferences in whatever software you’re using.

<img width="763" alt="Screen Shot 2021-06-29 at 1 13 23 PM" src="https://user-images.githubusercontent.com/32881239/123853072-a35e3200-d8e2-11eb-8e89-4f6d2a176fb9.png">
