### ISSUE TITLE
[Plex Mono] Polish diacritical marks not displaying correctly

### ISSUE THREAD

**Issue by martin-kaczmarek** [IBM/plex#381]
I've ran into an issue with the way letters with Polish diacritical marks are rendered. Screenshots from Chrome on MacOS attached. Looks fine in Google Fonts. 

Is this a know issue? Can anyone please advise?

![image (3)](https://user-images.githubusercontent.com/48365811/124720567-92c44200-df08-11eb-8aec-afa42f919495.png)
![image (2)](https://user-images.githubusercontent.com/48365811/124720568-935cd880-df08-11eb-913e-fab2252123cb.png)
![image (1)](https://user-images.githubusercontent.com/48365811/124720571-935cd880-df08-11eb-9ae5-e84dab82d446.png)
![image](https://user-images.githubusercontent.com/48365811/124720572-93f56f00-df08-11eb-945b-e4c73fe8963f.png)

**Comment by BoldMonday** [comment]
This should not be a problem because Plex Mono contains all glyphs for Polish.

What fonts are you using exactly? Is it possible you are using the split web fonts?
