### ISSUE TITLE
IBM Plex Sans JP: Seeing tofu for "Medm" and "Thin" variants

### ISSUE THREAD

**Issue by johnnyshields** [IBM/plex#386]
Firstly congrats on the release, well timed with the Tokyo Olympics!

Please check both "Medm" and "Thin". This is from MS Word on Windows using the OTFs from the 5.2.1 distro. Haven't tested TTFs.

![image](https://user-images.githubusercontent.com/27655/126857502-54e68ca7-1139-427d-a1cc-5a051928b3e0.png)

**Comment by BoldMonday** [comment]
Strange, we're unable to replicate the issue here.

Can you provide additional information about what version of Word and Windows you're using?
Does this happen with the other weights too?
Do you see similar behaviour in other applications, e.g. Wordpad?

**Comment by johnnyshields** [comment]
- Wordpad works fine.
- Word still having issues. Using Windows 10 and Word from Office 16.
- Weights besides "Thin" and "Medm" are fine.
- Test string is literally anything in Japanese, it's all tofu. テスト漢字です for example.
- I've installed all Plex fonts.

**Comment by BoldMonday** [comment]
@sandoll-inc: can you please have a look?

**Comment by sandoll-inc** [comment]
We can not reproduce your error environment. Could you send us the word file that has a problem and the JP font file that is currently installed?  You can send it to this email address. info@sandoll.co.kr

**Comment by johnnyshields** [comment]
OK, thank you. I will try re-installing and see if issue is fixed...

**Comment by Wangchingold** [comment]
let me know if I did anything in the workflow mess up
