### ISSUE TITLE
IBM Plex Sans JP v5.2.1 - vertical metrics in OTF files off

### ISSUE THREAD

**Issue by kenmcd** [IBM/plex#389]
The vertical metrics in the IBM Plex Sans JP v5.2.1 OTF files are quite a bit different than the settings in the TTF files. 
For example the line gap is set to 1,000.
In the TTF files the settings appear to be an adjusted version of the original IBM Plex Sans settings (as expected).
But the OTF files are very different and appear to have some issues with the settings.

**Comment by BoldMonday** [comment]
@mjabbink This was pointed out during QA to Sandoll and they insisted on setting it this way.

**Comment by kenmcd** [comment]
OK. So it was done on purpose.
But for educational purposes I would like to know their reasoning if that info is available.
Thanks.

**Comment by BoldMonday** [comment]
This is part of the correspondence with Sandoll:

> For Japanese fonts, generally, CFF/Opentype are set for Adobe and TrueType/Opentype are set for MS, distinctively.
> If possible, we recommend matching the vertical metrics of Plex Japanese to the usual Japanese font, matching the purpose of the font format. Otherwise people may think that the font is difficult to handle because the line spacing will change whenever you change the font.
> Below are cases of typical settings for Japanese font and sample fonts for vertical metrics for each application.
> 
> For Adobe compatibility
> Applications that use CFF/Opentype format JP fonts are mainly Adobe products. Therefore CFF/Opentype typically follows Kozuka Mincho(Adobe bundle font)'s vertical metrics settings as below.
> – OS/2-TypoAscender 880, OS/2-TypoDescender -120, OS/2-TypoLineGap 1000
> – hhea-ascender 880, hhea-descender -120, hhea-linegap 1000
> – OS/2-WinAscent, OS/2-WinDescent = font BBox value
> For compatibility of applications for MacOS, iOS
> Same as above, but set typo/hhea linegap to 500. Hiragino (MacOS bundle font) follows it.
> – OS/2-TypoAscender 880, OS/2-TypoDescender -120, OS/2-TypoLineGap 500
> – hhea-ascender 880, hhea-descender -120, hhea-linegap 500
> – OS/2-WinAscent, OS/2-WinDescent = font BBox value
>
> For compatibility of applications for Windows compatibility
> Applications that use TrueType/Opentype format JP fonts are mainly MS products, and set the hhea table and win table the same. Meiryo(Windows bundle font) follows it.
> – OS/2-TypoAscender + OS/2-TypoDescender + OS/2-TypoLineGap = hhea-ascender + hhea-descender + hhea-linegap = OS/2-WinAscent + OS/2-WinDescent

**Comment by kenmcd** [comment]
So the choice was made to focus on the Adobe compatibility settings.
Thanks for the info.
