### ISSUE TITLE
Postscript and CFF names do not match

### ISSUE THREAD

**Issue by kaydeearts** [IBM/plex#400]
I tested IBM Plex Sans JP Hinted fonts and found a [FontBakery](https://github.com/googlefonts/fontbakery) error for 4 fonts.

**The following fonts:**

- IBMPlexSansJP-ExtraLight.otf
- IBMPlexSansJP-Medium.otf
- IBMPlexSansJP-Regular.otf
- IBMPlexSansJP-SemiBold.otf

Have the same **postscript_vs_cff** errors:

**com.adobe.fonts/check/name/postscript_vs_cff with (('font[1]', 'IBMPlexSansJP-ExtraLight.otf'),)**
   CFF table FontName must match name table ID 6 (PostScript name).
 * FAIL: Name table PostScript name 'IBMPlexSansJP-ExtLt' does not match CFF table FontName 'IBMPlexSansJP-ExtraLight'.
 * FAIL: Name table PostScript name 'IBMPlexSansJP-ExtLt' does not match CFF table FontName 'IBMPlexSansJP-ExtraLight'.

   Result: FAIL

**com.adobe.fonts/check/name/postscript_vs_cff with (('font[3]', 'IBMPlexSansJP-Medium.otf'),)**
   CFF table FontName must match name table ID 6 (PostScript name).
 * FAIL: Name table PostScript name 'IBMPlexSansJP-Medm' does not match CFF table FontName 'IBMPlexSansJP-Medium'.
 * FAIL: Name table PostScript name 'IBMPlexSansJP-Medm' does not match CFF table FontName 'IBMPlexSansJP-Medium'.

   Result: FAIL

**com.adobe.fonts/check/name/postscript_vs_cff with (('font[4]', 'IBMPlexSansJP-Regular.otf'),)**
   CFF table FontName must match name table ID 6 (PostScript name).
 * FAIL: Name table PostScript name 'IBMPlexSansJP' does not match CFF table FontName 'IBMPlexSansJP-Regular'.
 * FAIL: Name table PostScript name 'IBMPlexSansJP' does not match CFF table FontName 'IBMPlexSansJP-Regular'.

   Result: FAIL

**com.adobe.fonts/check/name/postscript_vs_cff with (('font[5]', 'IBMPlexSansJP-SemiBold.otf'),)**
   CFF table FontName must match name table ID 6 (PostScript name).
 * FAIL: Name table PostScript name 'IBMPlexSansJP-SmBld' does not match CFF table FontName 'IBMPlexSansJP-SemiBold'.
 * FAIL: Name table PostScript name 'IBMPlexSansJP-SmBld' does not match CFF table FontName 'IBMPlexSansJP-SemiBold'.

   Result: FAIL
 
The PostScript name entries in the font’s ‘name’ table should match the FontName string in the ‘CFF ’ table.
The ‘CFF ’ table has a lot of information that is duplicated in other tables. This information should be consistent across tables, because there’s no guarantee which table an app will get the data from.

[Test source code here.](https://github.com/googlefonts/fontbakery/blob/a9fc45fb563350fa806107f3afd878db63eb03c5/Lib/fontbakery/profiles/name.py#L343-L373)

**Comment by BoldMonday** [comment]
@kaydeearts FYI - a hotfix has been sent by email to Ariadne.

If you find other problems with the files please report them here. Otherwise feel free to close the issue. Thanks!

**Comment by kaydeearts** [comment]
Hi @BoldMonday , thank you for the fix!
