### ISSUE TITLE
Feature Request: IBM Plex Mono - Stylistic Set/Character Variant for # symbol

### ISSUE THREAD

**Issue by krish-r** [IBM/plex#401]
Hello, 

I found a similar discussion in an earlier issues #205.

If possible, can you please create a Stylistic Set/Character Variant for the hash sign (`#`) in IBM Plex Mono font?

IBM Plex Mono:
![image](https://user-images.githubusercontent.com/54745129/132200383-86027527-2cc0-481c-bd59-9c3b369eb096.png)
![image](https://user-images.githubusercontent.com/54745129/132203608-a68f2ebe-cbb6-4861-a3fe-efc456a80fb2.png)

Consolas:
![image](https://user-images.githubusercontent.com/54745129/132200421-023b9c0c-1aaa-4a9b-929a-9ae0d80eafe8.png)
![image](https://user-images.githubusercontent.com/54745129/132203657-935ab44e-b44d-43bf-b7d5-2aab0c95e976.png)

Thanks

**Comment by mjabbink** [comment]
To make sure I follow the issue. Is it because of the open center and a pattern that may be visible as result? spacing wise the glyphs fit nicely inside 600 unit widths.

<img width="480" alt="Screen Shot 2022-01-20 at 11 26 24 PM" src="https://user-images.githubusercontent.com/32881239/150471233-af1419f5-ce56-4bda-87ba-23234ea183c4.png">

**Comment by krish-r** [comment]
Yeah exactly. 

Due to the open center, when there are multiple `#` signs, it looks a different pattern `||=||` (like an italicized ligature made of || and =) making it a little harder to recognize at first glance. Especially in markdowns as mentioned in another comment - https://github.com/IBM/plex/issues/205#issuecomment-1017438246, and also in other languages where `#` is used for comments.

Please feel free to close this as duplicate, if you would like to continue the discussion on the original issue.

**Comment by mjabbink** [comment]
A number of our Plex users have brought this up. It’s an easy thing to add as an alternate option in a future update. 

@BoldMonday — another item to add to the list!

**Comment by bakkot** [comment]
Any progress on this? We're adopting this font for [the JavaScript specification](https://tc39.es/ecma262/) and this is the only significant painpoint.

**Comment by BoldMonday** [comment]
An update for Plex Mono is scheduled for later this year.

It will include a reworked version of the `#` symbol as stylistic alternate.

**Comment by subnut** [comment]
Which stylistic set toggles this behaviour?

**Comment by marlun** [comment]
Can I build this somewhere without having to set it all up on my own machine?

**Comment by BoldMonday** [comment]
> Can I build this somewhere without having to set it all up on my own machine?

The latest release contains all generated fonts ready to install. No need to build anything yourself.

**Comment by marlun** [comment]
With the different stylistic toggles? Because I want it with the above style changes for #? I couldn't see that.

**Comment by BoldMonday** [comment]
No. In that case you have to modify the fonts yourself.
