### ISSUE TITLE
IBM Plex Sans JP: Glyph (uni95B9) is broken

### ISSUE THREAD

**Issue by mochisue** [IBM/plex#404]
The text in the attached image is displayed with TextEdit.app on a Mac.
The font weight is ExtraLight.

I checked the other weights and they probably did not have the same point structure, so the interpolation did not work.

This character (U+95B9) is defined in the JIS X 0208 character set, and is also available in Shift-JIS, so it is very important in Japanese.

<img width="794" alt="uni95B9" src="https://user-images.githubusercontent.com/89791341/134771199-c0724b71-e8fe-40d9-8bc9-346bbe2bc8b5.png">

**Comment by kenmcd** [comment]
There is a different start point in the Thin master.
![95B9-Interpolation-Issue 2021-09-25_14-31-35](https://user-images.githubusercontent.com/844920/134786488-382a1df8-d34c-41dc-a8d5-06fd86848c01.gif)

**Comment by aaronbell** [comment]
@BoldMonday Is there an ETA for when these interpolation issues will get sorted?

**Comment by BoldMonday** [comment]
@aaronbell no ETA from our side yet as this should be fixed by @sandoll-inc.

**Comment by mjabbink** [comment]
@BoldMonday I believe the latest from Sandoll will solve this. Correct me if I’m wrong.

**Comment by BoldMonday** [comment]
@mjabbink this has been corrected and we delivered updated files early December.

**Comment by BoldMonday** [comment]
Fixed in https://github.com/IBM/plex/releases/tag/v6.0.1
