### ISSUE TITLE
Sans JP v5.2.1 asterisk.rotat Interpolation Issue

### ISSUE THREAD

**Issue by kenmcd** [IBM/plex#405]
There is a different start point in the Bold master.

![Sans-JP-asterisk rotat-Intepolation Issue 2021-09-25_14-39-29](https://user-images.githubusercontent.com/844920/134786686-8207ac97-aeec-42ae-a272-1eb696323a63.gif)

**Comment by BoldMonday** [comment]
cc @sandoll-inc
