### ISSUE TITLE
Unable to disable Arabic ligatures in CSS with Plex Sans from Google Fonts

### ISSUE THREAD

**Issue by shadysamir** [IBM/plex#409]
I am using Plex Sans Arabic from Google fonts. I would like to disable ligatures. I tried the following CSS rules but it makes no difference:

```css
font-feature-settings: "liga" 0;
font-variant-ligatures: none;
```

**Comment by BoldMonday** [comment]
Arabic ligatures are part of the Required Ligatures feature with the tag `rlig`.

https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-rlig

**Comment by shadysamir** [comment]
Perfect. Using rule:
```css
font-feature-settings: "rlig" 0;
```
disabled ligatures. Thanks

**Comment by shadysamir** [comment]
Of course disabling that renders لا and essential ligatures in an undesirable way. Will need to figure out different solutions. But the issue itself is addressed. Remains closed.

**Comment by BoldMonday** [comment]
AFAIK the `rlig` feature only contains essential ligatures for Arabic.
Which ligatures are not essential to you?

**Comment by shadysamir** [comment]
I would like the font to be rendered like this:  
![image](https://user-images.githubusercontent.com/532005/139848738-6361e4ba-6da1-4ca9-bf75-388dd2b68c02.png)  
not like this:  
![image](https://user-images.githubusercontent.com/532005/139848844-69636359-066f-45e9-ac7f-e6d1f77ee2ce.png)

I would at least consider محمد unessential, while لما is debatable, but لا is definitely essential

**Comment by BoldMonday** [comment]
I can’t comment on that since these are the decisions made by the designers of Plex Sans Arabic.
But it’s possible that the latest version of the fonts hosted in this repository are a little different.
