### ISSUE TITLE
Sans & Mono, probably hinting: "б" bowl taller than "o" at 24, 28 ppem

### ISSUE THREAD

**Issue by ortoslon** [IBM/plex#410]
The bowl of "б" is correctly slightly smaller than "o" in the outlines yet is rendered taller at some sizes.

https://github.com/IBM/plex/blob/04c26256b9fb5cf19dfc33623d71588fb125cf60/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Regular.ttf in Chrome 95 on Win10:

![image](https://user-images.githubusercontent.com/79928123/140325090-5c648f0a-6f2a-4328-8cc2-4c43e294da4c.png)
![image](https://user-images.githubusercontent.com/79928123/140325104-8e002bc5-a48b-4a14-be0d-bb77a23b52c7.png)

https://github.com/IBM/plex/blob/04c26256b9fb5cf19dfc33623d71588fb125cf60/IBM-Plex-Mono/fonts/complete/ttf/IBMPlexMono-Regular.ttf:
![image](https://user-images.githubusercontent.com/79928123/140402177-b7f39fdb-5b9c-4b85-937f-c789b075651d.png)

**Comment by mjabbink** [comment]
@BoldMonday  Hinting issue I presume?

**Comment by ortoslon** [comment]
Seems fixed in Sans https://github.com/IBM/plex/blob/003b8b0a6f56acd78e8fa78ddf471f71412e18b4/IBM-Plex-Sans/fonts/complete/ttf/IBMPlexSans-Regular.ttf. Mono wasn't updated since then.
