### ISSUE TITLE
Extra-bold 800, Black 900, and Ultra 1000 weights for Plex

### ISSUE THREAD

**Issue by MattMayuga** [IBM/plex#411]
Thanks for the IBM Plex fonts! So far, it's a very versatile font for anything.

Here's one thing I would like to look forward to for the IBM Plex fonts. Adding the weights Extra-bold 800, Black 900, and Ultra 1000 can add to the versatile characteristics of the font, and these can be used for headlines, display, and among other things. If these get added in the next updates, it would be interesting.

**Comment by BoldMonday** [comment]
I agree that would be nice. But there are no plans to create additional weights for the moment.

**Comment by mjabbink** [comment]
Given, more immediate needs this will likely be vary far in our future if at all.
