### ISSUE TITLE
IBM Plex Mono: Alternative lowercase 'g'

### ISSUE THREAD

**Issue by aaronmbos** [IBM/plex#412]
I really enjoy using IBM Plex Mono in my text editors and terminals. One aspect of the typeface that has always stuck out to me is the lowercase 'g', in particular the "double-decker" style. In terms of fitting in with the rest of the characters, it feels like a lowercase `g` with a flat descender (similar to that of the lowercase `j`) may be more cohesive. I know this is also a matter of personal preference, but just wanted to see if this had ever been thought about.

**Comment by BoldMonday** [comment]
Luckily this is already catered for. The Plex family contains alternates for several characters including lowercase a and g.
They can be accessed by using the OpenType features `ss01` (stylistic set 1) and `ss02` (stylistic set 2).

Check out https://www.ibm.com/plex/specs/ for a complete overview of all fonts.
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/13793769/143766023-e990457d-13cc-4811-a833-211b92e834e4.png">

**Comment by aaronmbos** [comment]
Awesome, thank you!!
