### ISSUE TITLE
IBM Plex Sans JP: Opentype font is bigger line space than truetype font

### ISSUE THREAD

**Issue by sat-o** [IBM/plex#415]
Opentype font is bigger line space than truetype font. This occurs on JP font only.
Followings are Mac Font Book screen shots.
IBM Plex Sans JP Opentype font
![Screen Shot 2021-12-08 at 11 53 17](https://user-images.githubusercontent.com/66708143/145140277-1b8041fe-e675-4863-a25c-9ece9059362a.png)

IBM Plex Sans JP Truetype font
![Screen Shot 2021-12-08 at 11 54 46](https://user-images.githubusercontent.com/66708143/145140346-ba000e53-7f6e-4b0f-8dbf-5919effad9dd.png)

**Comment by BoldMonday** [comment]
This is intentional and is explained in #388, in particular [this comment](https://github.com/IBM/plex/issues/388#issuecomment-890870630).

**Comment by sat-o** [comment]
I understand.
