### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by kamekku14** [IBM/plex#416]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/@ibm/plex) but it fails because the package is over 50 MB. Are there any files that could be removed to reduce the package size?

**Comment by jimaek** [comment]
You can still load the files individually https://cdn.jsdelivr.net/gh/ibm/plex@6.0.0/IBM-Plex-Sans-Devanagari/fonts/complete/woff2/IBMPlexSansDevanagari-Bold.woff2
We just can't build the index due to the large size.

**Comment by mjabbink** [comment]
FYI @vpicone

**Comment by tay1orjones** [comment]
Duplicate of https://github.com/IBM/plex/issues/453

**Comment by tay1orjones** [comment]
I've made an RFC to propose a fix here: https://github.com/IBM/plex/discussions/452
