### ISSUE TITLE
Add Italic to IBM Plex Sans Thai and IBM Plex Sans Thai Looped

### ISSUE THREAD

**Issue by karn18** [IBM/plex#417]
It would be great if you add italic to both fonts

**Comment by BoldMonday** [comment]
The concept of an italic style — as companion to a Roman upright style — is alien to many of the scripts that IBM Plex is supporting: Hebrew, Arabic, Devanagari, Hangul, Japanese, and Thai. It was a conscious decision by the IBM Plex team not to enforce Latin-centric principles to scripts where they do not belong to. Therefore all the aforementioned scripts do not have an italic style in Plex.

Italic is in essence a style that belongs to the Latin script (and for some of its offsprings such as Cyrillic). I am very curious why such a style would be desirable to add to Thai.
