### ISSUE TITLE
Wrong glyph of U+08A4 in IBM Plex Sans Arabic

### ISSUE THREAD

**Issue by Etewilak** [IBM/plex#429]
The glyph of U+08A4 in IBM Plex Plex Sans Arabic is wrong.
![image](https://user-images.githubusercontent.com/55674356/153751235-9f238d44-b403-4e45-a5b2-cad1bc60862d.png)
The correct glyph is as follows:
![image](https://user-images.githubusercontent.com/55674356/153751247-2cfbb00e-c296-4154-b22e-97ad08938341.png)

**Comment by BoldMonday** [comment]
Thank you for reporting.

We’ll check with the original designers of Plex Arabic and submit a fix.

**Comment by BoldMonday** [comment]
Fixed in https://github.com/IBM/plex/releases/tag/v6.0.1
