### ISSUE TITLE
Add Bulgarian Cyrillic glyphs

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#448]
Transferring from this issue https://github.com/IBM/plex/issues/370#issuecomment-1145752379

The Bulgarian Minister of e-Government Bozhidar Bojanov has launched an initiative for Bulgarian institutions to use fonts that support Bulgarian Cyrillic. Source: https://www.facebook.com/bozhidar.bozhanov/posts/pfbid036YFX1SuEjFv4Mzg4WGfdnmCSG6yKT5f4wBokqjZigxCER6tkFdmrxzsD6xeedLBzl

The IBM Plex font is widely used in the Bulgarian web and I suggest you add support for the Bulgarian Cyrillic Script so that everyone can take advantage of it. You can read more about the loclBGR glyphs with examples and info on this article - https://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/. More detailed information can be found here - https://www.fontfabric.com/blog/rounded-bulgarian-cyrillic-narrative-and-comparison/.

I will be more than grateful if you consider my proposal!

![](https://user-images.githubusercontent.com/4932709/171821605-723566cf-c9a8-49c2-8362-7b0683fcadc1.png)

**Comment by BoldMonday** [comment]
Agreed. This will be nice to add.

**Comment by mjabbink** [comment]
WIP. Design completely and moving into production.

**Comment by BoldMonday** [comment]
Here’s a preview of the upcoming Plex Sans extension for Bulgarian Cyrillic forms.
Designed in close collaboration with Bulgarian type designer Lora Shtirkova.

![image](https://user-images.githubusercontent.com/13793769/226864186-d0c75eab-35af-4646-9f17-c3d5a5a34244.png)

**Comment by XenBG** [comment]
@BoldMonday @mjabbink

The Bulgarian Cyrillic looks stunning! Laura has done a great job. I can't wait to try it in a production environment. Is there any time frame when this version is expected to be available? Please, keep me in touch tagging me here. Thanks in advance!
