### ISSUE TITLE
How do I use slashed zero in Plex Mono ttf font?

### ISSUE THREAD

**Issue by felixxing** [IBM/plex#455]
Title speaks for itself.
I have no idea how this work, hope someone could help me.

**Comment by kenmcd** [comment]
The OpenType features change this.
Use either Slashed Zero (`zero`) or Stylistic Set 3 (`ss03`).
Which feature is available depends on the application you are using.

**Comment by felixxing** [comment]
> The OpenType features change this. Use either Slashed Zero (`zero`) or Stylistic Set 3 (`ss03`). Which feature is available depends on the application you are using.

Are there anyway to build a true type from open type while some feature is enable?
