### ISSUE TITLE
Plex Sans JP on Windows DirectWrite looks blurry

### ISSUE THREAD

**Issue by Hackgets** [IBM/plex#460]
Plex Sans JP on Windows DirectWrite looks blurry. The baseline also seems a little high. It is difficult to use this font now as small as Noto Sans JP, although this is probably due to the ugly font rendering in Windows.

Environments in the following screenshots.

- Windows 10 Home 21H2 Build 19044.1826
- Firefox 103.0.1
![スクリーンショット 2022-08-03 122908](https://user-images.githubusercontent.com/102782728/182518703-b9c477e2-9489-4217-bbe4-962a01296200.png)

**Comment by johnnyshields** [comment]
This is probably a duplicate with https://github.com/IBM/plex/issues/388
