### ISSUE TITLE
Evaluate performance of original vs split files (WOFF and WOFF2)

### ISSUE THREAD

**Issue by ptaunton** [IBM/plex#47]
The current stored files for the web fonts (WOFF and WOFF2) are split into smaller locale-specific parts. While this is OK for sites that can guarantee they only see characters from one or other of the splits, in all likelihood they will now need to download more than one font file to render a page. For example, non-latin or glyph-based languages will often have latin characters on screen as well (acronyms, formal words, user-entered text etc.).

We would like to have the option of including a single whole font file and ask that this be provided alongside the split editions. For size comparison, the current full size of Plex at 48KB (WOFF) is comparable or better than other very popular font files such as material icons (56KB WOFF) and font awesome (80KB WOFF) so does not represent a particular size penalty.

**Comment by seejamescode** [comment]
Hey @ptaunton, thanks for creating the issue so we can figure out the best solution! I have rephrased the title to make sure we decide which is the best option. If one is more performant than the other, we want that to be the one issue for all. Either:
- The font splits stay as is
- We rearrange the splits
- We switch back to single files

**Comment by seejamescode** [comment]
Evaluation of impact for single files:

The last full woff2 files I received were 38kb each. Based on our guidelines, 1-14 files would be loaded on a screen. The impact at best would be...
![screen shot 2017-10-31 at 9 35 19 am](https://user-images.githubusercontent.com/7519029/32229476-e65f49fa-be1e-11e7-9b41-ac41f45af362.png)

**Comment by seejamescode** [comment]
**Impact for current splits**

The average woff2 file was 13kb. Based on our guidelines, 1-56 files would be loaded on a screen. The impact at best would be...
![screen shot 2017-10-31 at 9 39 49 am](https://user-images.githubusercontent.com/7519029/32229773-a2243844-be1f-11e7-8c75-8968654153eb.png)

**Comment by seejamescode** [comment]
So now I know that the most performant options are:
- Loading 14 files or less? The current file splits
- Loading more than 14 files? The single files

So now the most helpful thing would be for us to think of a way to systematically collect data on how many files screens are usually loading. Any ideas how to conduct that study?

**Comment by seejamescode** [comment]
@joshblack has some initial benchmark tests for this situation in #51 

This will also be important with future releases of Cyrillic and Greek

**Comment by seejamescode** [comment]
Whole font files are included in v1.0.0.
