### ISSUE TITLE
Extra spaces when using Greek font

### ISSUE THREAD

**Issue by rrolls** [IBM/plex#479]
Very briefly, our app uses Apache FOP with IBM Plex to generate PDF 'datasheets' for IBM products in multiple languages.  It has been brought to our attention that the Greek datasheets have additional spaces around certain characters.  The datasheets look good when viewed in HTML but have these extra spaces in the PDF.   For example:
![GreekSpaces](https://user-images.githubusercontent.com/5213028/191477438-54bfe136-9ea3-4eb4-ae59-ad49551d3ab9.png)

Same sentence when viewed in HTML:
![image](https://user-images.githubusercontent.com/5213028/191477924-6db9e1c7-5029-4660-8301-8297b19585aa.png)

I would like help in understanding & fixing this issue, please.

**Comment by kenmcd** [comment]
Could you provide the files?
The characters look different in the two samples - they may be different fonts.
And it would be good to look at exactly what is embedded in the PDF (fonts, characters, spaces, etc.).
My guess is it is probably not a font issue but an application issue.

**Comment by BoldMonday** [comment]
In fact both samples do not appear to use Plex at all.
Look closely at the word **IBM** and you’ll notice it does not have the serifs on capital I, nor does it have the raised middle part in capital M.

**Comment by rrolls** [comment]
Here's the PDF
[SAASDSRPDF-2022-09-13.pdf](https://github.com/IBM/plex/files/9617816/SAASDSRPDF-2022-09-13.pdf)

**Comment by kenmcd** [comment]
> Here's the PDF [SAASDSRPDF-2022-09-13.pdf](https://github.com/IBM/plex/files/9617816/SAASDSRPDF-2022-09-13.pdf)

Most of the text is NotoSansMono-Regular. (quite odd)
The oddly spaced characters are IBMPlexSansJP - so it looks like it is picking up the Japanese full width spacing for those Greek characters.

So this does appear to be an application issue.
