### ISSUE TITLE
Our app uses Apache FOP with IBM Plex to generate PDF 'datasheets' for IBM products in multiple languages. For the Greek lang datasheets we have additional "#" around certain characters. The datasheets look good when viewed in HTML but have these extra # in the PDF. 

### ISSUE THREAD

**Issue by doonvipul** [IBM/plex#482]
Our app uses Apache FOP with IBM Plex to generate PDF 'datasheets' for IBM products in multiple languages. For the Greek lang datasheets we have additional "#" around certain characters. The datasheets look good when viewed in HTML but have these extra # in the PDF. 

For Example 

![image](https://user-images.githubusercontent.com/51817470/193544398-3284e263-8df5-4867-8c92-ed2af0deca41.png)

PDF Properties is showing the korean Font embedded in pdf 

![image](https://user-images.githubusercontent.com/51817470/193544290-de734d30-b39d-472f-bf1c-0e79da5b35ae.png)

**Comment by BoldMonday** [comment]
This sounds like a software/implementation issue and not a problem with the Plex fonts themselves.

Neither Plex Sans KR nor Plex Sans JP should be used for setting Greek text.
