### ISSUE TITLE
Which IBM Plex font is used for supporting Greek language

### ISSUE THREAD

**Issue by doonvipul** [IBM/plex#483]
Which IBM Plex font is used for supporting Greek language

**Comment by BoldMonday** [comment]
**IBM Plex Sans** (without any suffix) supports extended Latin, extended Cyrillic, and monotonic Greek.
All other members of the Plex Sans family are specifically to support Hebrew, Arabic, Devanagari, Thai, Korean (KR) and Japanese (JP).
