### ISSUE TITLE
Please consider removing the small stroke on the side of the ß in IBM Plex Mono

### ISSUE THREAD

**Issue by th-bu** [IBM/plex#486]
At the moment the ss05-ß in the Mono font has a small stroke on the left:

![grafik](https://user-images.githubusercontent.com/2885473/194725203-3c65f227-2e81-4e6f-a3fd-a3b3285dea7e.png)

This is not a feature of the ß in the german alphabet. I guess it's there for spacing reasons but it just looks very weird.

**Comment by BoldMonday** [comment]
One simply cannot claim that the horizontal bar cannot be a feature of the letter `ß`.

There is a big variety how the letter `ß` can be designed and what letters it tries to refer to. In this case of Plex Mono it has been designed as a ligature between the letter long s `ſ` and the letter short s `s`. The long s traditionally has a horizontal bar on the left and therefore that bar has been preserved in our design.

There are plenty of typefaces that contain a similar construction, including the most successful German typeface of all times – Paul Renner’s Futura. Please see the word **Handgießer** below.

![image](https://user-images.githubusercontent.com/13793769/194757042-ac6e9ea1-e951-49d3-816e-efd37c72b48a.png)

**Comment by twardoch** [comment]
The ß form used in Plex Sans is slightly antiquated, but it has a long history in German writing and typemaking.
