### ISSUE TITLE
Position and size of full-width exclamation mark is not in harmony with the Japanese characters.

### ISSUE THREAD

**Issue by Hackgets** [IBM/plex#487]
Position and size of IBM Plex Sans JP's FULLWIDTH EXCLAMATION MARK (U+FF01) is not in harmony with the Japanese characters. Comparisons with other Japanese fonts are shown below.
<img width="600" alt="excomp" src="https://user-images.githubusercontent.com/102782728/196361381-8cea6305-f6e5-45a3-b7f4-88fc862f314b.png">

**Comment by mjabbink** [comment]
The team that did Noto also designed Plex JP. I also do not agree.
