### ISSUE TITLE
Request of characters: needed in mathematics, geometry, etc.

### ISSUE THREAD

**Issue by pereelmagne** [IBM/plex#493]
‴ U+2034 TRIPLE PRIME «Punctuation, Other»
⁗ U+2057 QUADRUPLE PRIME «Punctuation, Other»
‰ U+2030 PER MILLE SIGN «Punctuation, Other»
‱ U+2031 PER TEN THOUSAND SIGN «Punctuation, Other»

**Comment by mjabbink** [comment]
These will be included in Plex Math
