### ISSUE TITLE
Plex Mono suggestions

### ISSUE THREAD

**Issue by Morpheus2077** [IBM/plex#499]
1. Improve hinting

2. OpenType feature variant for `r` and `f`

3. I think the ```- ` ®``` is so small

4. Reduce underline thickness

6. Add basic Powerline glyphs

7. Request of characters:
U+2105 ℅
U+2117 ℗
U+21D0 ⇐
U+21D1 ⇑
U+21D2 ⇒
U+21D3 ⇓
U+220E ∎
U+2218 ∘
U+2219 ∙
U+221F ∟
U+2229 ∩
U+2261 ≡
U+2302 ⌂
U+2310 ⌐
U+2318 ⌘
U+2320 ⌠
U+2321 ⌡
U+25A0 ■
U+25A1 □
U+25AA ▪
U+25AB ▫
U+25AC ▬
U+25B2 ▲
U+25B3 △
U+25B4 ▴
U+25B5 ▵
U+25B6 ▶
U+25B7 ▷
U+25B8 ▸
U+25B9 ▹
U+25BA ►
U+25BB ▻
U+25BC ▼
U+25BD ▽
U+25BE ▾
U+25BF ▿
U+25C0 ◀
U+25C1 ◁
U+25C2 ◂
U+25C3 ◃
U+25C4 ◄
U+25C5 ◅
U+25C6 ◆
U+25C7 ◇
U+25C8 ◈
U+25C9 ◉
U+25CB ○
U+25CC ◌
U+25CE ◎
U+25CF ●
U+25D9 ◙
U+25EF ◯
U+2605 ★
U+2606 ☆
U+2610 ☐
U+2611 ☑
U+2612 ☒
U+2613 ☓
U+263A ☺
U+263B ☻
U+263C ☼
U+2640 ♀
U+2642 ♂
U+2660 ♠
U+2661 ♡
U+2662 ♢
U+2663 ♣
U+2664 ♤
U+2665 ♥
U+2666 ♦
U+2667 ♧
U+2669 ♩
U+266A ♪
U+266B ♫
U+266C ♬
U+26A0 ⚠
U+26A1 ⚡
U+2714 ✔
U+2715 ✕
U+2716 ✖
U+2717 ✗
U+2718 ✘
U+2764 ❤
U+2B58 ⭘

**Comment by BoldMonday** [comment]
Without proper motivation, examples, and/or use cases this is not very constructive feedback.

For example -- all fonts in this repository contain manual hinting. Perhaps they do not render perfectly in your environment but can you prove that it is a hinting issue and not a rasterizer issue?
