### ISSUE TITLE
Quotation marks in plex-mono

### ISSUE THREAD

**Issue by TheJoffrey** [IBM/plex#514]
Hello, quotation marks using Plex Mono are the following:
```
”
```

They should be:
```
"
```

Very annoying when using for code. Thank you!

**Comment by BoldMonday** [comment]
The standard single and double quotes in IBM Plex Mono are straight forms.
Not sure what is the culprit in your case, but it is not the font.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/13793769/225393647-0cc22dc8-9b8d-407b-aec0-357137ccc970.png">

**Comment by TheJoffrey** [comment]
The issue doesn't occur when importing the font locally or using other fonts. Please try this code, I think you will understand:

```
\documentclass{article}
\usepackage{plex-mono}

\begin{document}
\begin{verbatim}
	"My citation"
\end{verbatim}
	
\end{document}
```

**Comment by akulisch** [comment]
@TheJoffrey In all TeX variations `"` will be replaced with `”` per default. https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Quote-marks

You will need to find a solution to instead produce the straight quotes, which depends on whether you are using LaTeX, XeLaTex, or LuaTeX, and on which packages you are using. This question is best placed in a TeX-centric forum like, e.g., https://tex.stackexchange.com/, since it has nothing to do with the font you are using, and thus is not a Plex problem.

**Comment by TheJoffrey** [comment]
As I said it only happens using the plex-mono package, and not when importing font using fontspec. So it does look like a Plex package issue.
________________________________
De : Adrian Kulisch ***@***.***>
Envoyé : Friday, March 17, 2023 12:24:52 PM
À : IBM/plex ***@***.***>
Cc : Joffrey Viémon ***@***.***>; Mention ***@***.***>
Objet : Re: [IBM/plex] Quotation marks in plex-mono (Issue #514)


@TheJoffrey<https://github.com/TheJoffrey> In all TeX variations " will be replaced with ” per default. https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Quote-marks

You will need to find a solution to instead produce the straight quotes, which depends on whether you are using LaTeX, XeLaTex, or LuaTeX, and on which packages you are using. This question is best placed in a TeX-centric forum like, e.g., https://tex.stackexchange.com/, since it has nothing to do with the font you are using, and thus is not a Plex problem.

**Comment by BoldMonday** [comment]
What package are you referring to?

**Comment by BoldMonday** [comment]
@TheJoffrey What plex-mono package are you referring you? And what is fontspec?
Are you using the Plex Mono fonts from this repository?
As @akulisch already noted: your problem might be somewhere downstream.

Please explain as elaborately as possible your use case, the environment you’re using (OS, applications, etc.) and how you are accessing the fonts in question. Thanks!

> As I said it only happens using the plex-mono package, and not when importing font using fontspec. So it does look like a Plex package issue.

**Comment by TheJoffrey** [comment]
I am using the plex-mono package. I compared the result with the fontspec package that allows the user to redefine fonts with XeLateX compiler. I've got the same issue locally (macOS, Texifier or MacTex) and on Overleaf.

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Paul van der Laan ***@***.***>
Envoyé : Saturday, March 18, 2023 1:46:14 PM
À : IBM/plex ***@***.***>
Cc : Joffrey Viémon ***@***.***>; Mention ***@***.***>
Objet : Re: [IBM/plex] Quotation marks in plex-mono (Issue #514)


@TheJoffrey<https://github.com/TheJoffrey> What plex-mono package are you referring you? And what is fontspec?
Are you using the Plex Mono fonts from this repository?
As @akulisch<https://github.com/akulisch> already noted: your problem might be somewhere downstream.

Please explain as elaborately as possible your use case, the environment you’re using (OS, applications, etc.) and how you are accessing the fonts in question. Thanks!

As I said it only happens using the plex-mono package, and not when importing font using fontspec. So it does look like a Plex package issue.

**Comment by BoldMonday** [comment]
@TheJoffrey This is still not specific enough to understand the issue I’m afraid. We are font developers, not package managers or LateX users.
Please describe step by step – and as elaborate as possible – how to replicate the problem you’re describing.

**Comment by BoldMonday** [comment]
A search for `\usepackage{plex-mono}` led me to the following repository:
https://ctan.org/tex-archive/fonts/plex (Note that this is not an IBM affiliated repository.)

The README of that repository contains the following:
```
This is the README for the plex package, version 2022-09-23.

[...]

The nomap option to plex-mono will suppress the tex-text
mapping of TeX "smart quotes" and other ligatures into
unicode glyphs for xeLaTeX and luaLaTeX.

[...]
```
There is the answer to this issue.
