### ISSUE TITLE
IBM Plex Mono: '0' taller or shorter than other digits

### ISSUE THREAD

**Issue by efission** [IBM/plex#515]
I've been attempting to switch over to IBM Plex Mono in various applications where I need a monospaced font. In some apps, everything looks fine, but in others, the top of the '0' character seems misaligned with the other digits.

On Windows, you can see this in Notepad (this is IBM Plex Mono 9pt):

<img width="174" alt="image" src="https://user-images.githubusercontent.com/12264425/228632822-d335b2db-597c-416e-97ab-aa772210f882.png">

Exactly which point sizes are affected seems to depend on the display scaling; but even at 100% display scaling, it is affected at some point sizes. Generally it happens at smaller point sizes, eg 7–11pt. Usually if one size looks good, going up or down 1pt will show the issue.

Apps which seem to be affected:

- cygwin terminal
- gVim / neovim
- Notepad
- WordPad

I have example images of some of these, if anyone would find it helpful.

Apps which don't seem to be affected:

- Chrome / Firefox
- MS Word
- PowerShell ISE
- xterm (cygwin + Xming)

I am using the latest OpenType release zip from github, IBM Plex Mono Regular version 2.3. My system is Windows 10. (macOS doesn't seem affected; and I haven't tried Linux or BSD yet, but I could, if needed.)

**Comment by BoldMonday** [comment]
Thank you for the detailed report. We'll have a look what might be the cause of this misbehaviour in screen rendering. The PostScript format is very limited in this respect though, so it might be a rasterizer issue. The PostScript rasterizer in Windows is old and not very sophisticated.

I recommend to install the TrueType versions instead. They are much better suited for rendering on screen and we have put great care in optimising the fonts for this purpose.

**Comment by efission** [comment]
And thank you for the quick reply! After years of choosing OpenType fonts for DTP on macOS, it didn't even occur to me to try the TrueType fonts.

You're quite right, the TrueType versions render superbly at all point sizes. I haven't run through the full list of apps yet, but every test I ran so far was a success.

This also fixes another issue I was having, where I couldn't select IBM Plex Mono in Windows Console apps (eg, the PowerShell console). After switching to TrueType fonts, it became available in the font list. Many thanks!
