### ISSUE TITLE
KASRA is rendered as FATHA in ALLAH (اللهِ) ligature

### ISSUE THREAD

**Issue by munzirtaha** [IBM/plex#525]
IBM Plex Sans Arabic renders KASRA in ALLAH ligature (U+0627U+0644U+0644U+0647U+0650) over the ARABIC LETTER HEH. It should come under the letter.
![allah](https://github.com/IBM/plex/assets/2936425/f2fb31df-aa16-4fce-a091-1b0db881951b)

**Comment by BoldMonday** [comment]
I'm able to replicate the issue. Perhaps we should deactivate the ALLAH ligature altogether in the `rlig` feature. That would allow correct mark positioning.

**Comment by mjabbink** [comment]
From Wael Morcos (one of the designers of Plex Arabic) —  I agree with @BoldMonday’s suggestion to deactivate the  =ALLAH ligature altogether in the rlig feature.

**Comment by TheMikeyRoss** [comment]
Hi 👋

Any update on this one?
