### ISSUE TITLE
[website] change all mentions of "Plex Condensed" to "Plex Sans Condensed"

### ISSUE THREAD

**Issue by julesatgthb** [IBM/plex#527]
Hello...

First, many thanks for the font - I've been using it for 2 years.
Now, millions of characters later, I stumbled on this (and on my own ignorance):

a) There's the IBM Plex Sans Cond that everyone keeps talking about, and using - present company included, but
b) There's an IBM Plex Condensed advertised on IBM's website: [https://www.ibm.com/plex/concept/](https://www.ibm.com/plex/concept/)

Initially, I though this was the naming / abbreviation issue.
However, the difference between the fonts is substantial - take a look at the infamous 'g'.
Can anyone look into this and shed some light, please?
Or am I mixing up the golf balls? :)

Many thanks,
J.

**Comment by BoldMonday** [comment]
There is only one condensed version of IBM Plex Sans which -- depending on your operating system or application -- might show up either as “IBM Plex Sans Cond” or ”IBM Plex Sans Condensed” in font menus.

I’m not sure what image of a “g” you are referring to but the fonts in question contain two versions: the double-storey g is the default form, and there is a single-storey g as stylistic alternate.
<img width="203" alt="image" src="https://github.com/IBM/plex/assets/13793769/88529780-012c-4591-808d-9525380153d7">

**Comment by julesatgthb** [comment]
Dear Paul / BoldMonday,

Thank you for emboldening my Sunday!
...And liberating the world from Helvetica - we, the World, thank you.
Perhaps you could add Roboto next to your hit list, please...? :)

I'm aware of the abbreviation of 'condensed' to 'cond' in, say, Word's font menu.
However, what I have on my end is IBM Plex **Sans** Cond, with the double-decker '𝗀' only.
Yet, on IBM's website - in the specs menu from where you took your image - there's
- the Sans (without the cond) and with '𝗀' and 'g'
- the Condensed (without the sans) with just the 'g'

...Which got me asking, did I break the font? Known to happen...
...Or maybe it's a Windows / Word nonsense - I do use Open, not TrueType...
For example, when I type ¼, Word maps it to IBM Plex Mono, not Cond - which, nonetheless, I prefer, with that beautiful interrupted slash. Yet, word does this with either True or Open type, and the font files, say, IBMPlexSans-Regular.ttf, Mono-Regular.ttf, or SansCondensed-Regular.ttf, neither shows me two gs, just the one '𝗀', in U+0067, as one would expect...

Still, ignore me - I'm happy with the fractions in the same way I'm happy with '𝗀' - there's no need for that 'g' - not at all, I was just - o. m. ⎵ .  - maybe I'm using the wrong font files...?
Anyhow... Many thanks!
Truly appreciate you taking the time.
Enjoy your weekend, or what's left of it.
J.

PS - Talking about fractions, this would be liberating too: ⅒ 
...And, while we're at it...  ℚ  ℝ  ℤ  ℕ  𝑛  𝑥  𝑦  𝑧  ⎴  ≪  ≫  ∈  ∋  ∧  ∨  ∴  ≲  ≳  ◁  ⬧  & Co. ➊... Ⓐ...
...But more importantly U+1F384

**Comment by kenmcd** [comment]
IBM Plex Sans Condensed - Regular (v1.3/v1.003)
from Release v6.3.0 - https://github.com/IBM/plex/issues/527

Alternate `g` is accessed via `ss02` or `salt` (or `aalt`) 

![2023-06-11_12-12-27](https://github.com/IBM/plex/assets/844920/56897ce3-c1d8-4768-91ee-c51c30fd1919)

You can also "freeze" those features into your own custom version using either:
- OpenType Feature Freezer - https://github.com/twardoch/fonttools-opentype-feature-freezer
- FontFreeze - https://github.com/MuTsunTsai/fontfreeze

**Comment by BoldMonday** [comment]
Ah, I see there is typo on the Plex website!

All the drop down menus on https://ibm.com/plex/ are listing 
“IBM Plex Condensed” whereas there should be “IBM Plex **Sans** Condensed”.

@mjabbink: can this be fixed?

<img width="933" alt="image" src="https://github.com/IBM/plex/assets/13793769/521f14dc-5f37-4b68-a320-46c6ca632f07">

**Comment by julesatgthb** [comment]
@BoldMonday - Yep, that's the menu that got me disturbing your weekend.

@kenmcd - brilliant stuff! Many, many thanks! Every day is a school day.
I'm on FontFreeze, having a blast. I'll be here for days. The pleasure of remapping font tables - genius.
The OT Feature Freezer is 404ing me to font off...

Anyhow, thank you all. Appreciate you looking into this - truly do.
J.

**Comment by mjabbink** [comment]
Thanks for finding this and I will make an issue to fix but this will probably take some time due to resources and priorities.

@julesatgthb The condensed should have both g’s and the double-decker is default and the single story an alternate.

**Comment by julesatgthb** [comment]
Dear Mike (et al.), 

No worries; none at all. I'm already thankful for you taking the time.
It's all good, really. I was just taken aback a bit, thinking I'd broken another font.
The truth is I love the double-decker. This other 'g' is just a misguided 'a' - like the 'Is' who think their 'ls'...?
Anyhow...

Thank you.
_You can close this._

**Comment by BoldMonday** [comment]
Let's keep this issue open until the website has been updated.

**Comment by BoldMonday** [comment]
@Shot2 Your comments seem unrelated to the issue discussed here.
Feel free to open a new issue where you describe in detail the problem. Please include screenshots too.

**Comment by mjabbink** [comment]
Issues should be resolved on the Plex website.
