### ISSUE TITLE
OpenType.zip is the same for releases 6.3.0 and 6.2.0

### ISSUE THREAD

**Issue by romildo** [IBM/plex#529]
The files https://github.com/IBM/plex/releases/download/v6.3.0/OpenType.zip and https://github.com/IBM/plex/releases/download/v6.2.0/OpenType.zip have the same content.

Is this a mistake in the 6.3.0 release process?

**Comment by BoldMonday** [comment]
The [6.3.0 release notes](https://github.com/IBM/plex/releases/tag/v6.3.0) mention only an update to Plex Sans Var.

These variable fonts don't come in OpenType format so therefore there has been no change on that side.
