### ISSUE TITLE
Arabic: glyph spacing issue in PDFs

### ISSUE THREAD

**Issue by TheMikeyRoss** [IBM/plex#542]
Hi 👋

I'm using IBM Plex Sans Arabic in [@react-pdf/renderer](https://github.com/diegomura/react-pdf) and I noticed a spacing issue in the Arabic font, specifically in two glyphs: 
- U+feae (Arabic Letter [Reh](https://symbl.cc/en/FEAE/) Final Form) - [File](https://github.com/IBM/plex/blob/a1a84378d19f8a86fde19e228574550281e48b3b/IBM-Plex-Sans-Arabic/sources/masters/IBM%20Plex%20Sans%20Arabic-Regular.ufo/glyphs/reh-ar.fina.glif#L4)
- U+feb0 (Arabic Letter [Zain](https://symbl.cc/en/FEB0/) Final Form) - [File](https://github.com/IBM/plex/blob/a1a84378d19f8a86fde19e228574550281e48b3b/IBM-Plex-Sans-Arabic/sources/masters/IBM%20Plex%20Sans%20Arabic-Regular.ufo/glyphs/zain-ar.fina.glif#L4)

He's a [link](https://react-pdf-repl.vercel.app/?gz_code=eJzFk8Fu2kAQhu88xci9EMllE1BpoYCapo1Co6ZOoET0Ui1mbFa1vdbuUEMRh-bILY9SngbyNB0HEdILPaX1yf69_8w3vz0qTrUhmEEXJ-SCJ0N0oacwc-Gd9scxJqye6oRgDoHRMThvDEqfnqfDQBhMhmjQOK8LhfxMyWCoLKEpzgoAgYxVNK2D0377EbwIJ9CRiYVjIwfKd1w-YY3Pr0dEqa0LEXAFWwotSVJ-ydexsEIN4pSdlo3y3ie-H5XFZVa5-HJF197lyfgsxupLet__3J5UzkeH3tlV7aLa9z59rZ10e7b34XzStSWigBvOD5gTJ_cDDzGQ44igeADNFhQZprGdFyxNI2zOZpATne6dAubzFnvZnScHVv3ApnNcdTYiy3mU24eNkgf9Z4sOu-pQfuVCLE2okq5O6_DCBV9H2nDnZ0dBeVCpOS5ESJxuJ5W-SsI6HD6031zrm9VyvVgtH0s_V7_Wi_XNg9QQOcDOJQR0R8gcUaQzrgqZNt8sBCrBnecpmRlwH1xfj8GXCVhEkEAqmYLlWggDpAwx4QIgkyE8rvLEuOvF39LcEIZIFgYqDNH8V9r9X_96xFhtMJhGOTQx_moJ2jAjZIpGnPrdLSj61z8Gw9_d7oFviN1uNUS-fvl9Q2zXuFXgdf8Nzdl_dg&modules=true) to a reproduction of the issue

**Comment by BoldMonday** [comment]
You expect me to click on a link that looks like this? No thank you.

```https://react-pdf-repl.vercel.app/?gz_code=eJzFk8Fu2kAQhu88xci9EMllE1BpoYCapo1Co6ZOoET0Ui1mbFa1vdbuUEMRh-bILY9SngbyNB0HEdILPaX1yf69_8w3vz0qTrUhmEEXJ-SCJ0N0oacwc-Gd9scxJqye6oRgDoHRMThvDEqfnqfDQBhMhmjQOK8LhfxMyWCoLKEpzgoAgYxVNK2D0377EbwIJ9CRiYVjIwfKd1w-YY3Pr0dEqa0LEXAFWwotSVJ-ydexsEIN4pSdlo3y3ie-H5XFZVa5-HJF197lyfgsxupLet__3J5UzkeH3tlV7aLa9z59rZ10e7b34XzStSWigBvOD5gTJ_cDDzGQ44igeADNFhQZprGdFyxNI2zOZpATne6dAubzFnvZnScHVv3ApnNcdTYiy3mU24eNkgf9Z4sOu-pQfuVCLE2okq5O6_DCBV9H2nDnZ0dBeVCpOS5ESJxuJ5W-SsI6HD6031zrm9VyvVgtH0s_V7_Wi_XNg9QQOcDOJQR0R8gcUaQzrgqZNt8sBCrBnecpmRlwH1xfj8GXCVhEkEAqmYLlWggDpAwx4QIgkyE8rvLEuOvF39LcEIZIFgYqDNH8V9r9X_96xFhtMJhGOTQx_moJ2jAjZIpGnPrdLSj61z8Gw9_d7oFviN1uNUS-fvl9Q2zXuFXgdf8Nzdl_dg&modules=true```

**Comment by TheMikeyRoss** [comment]
That link is generated from this [tool](https://github.com/jeetiss/react-pdf-repl) Which is based on [this](https://react-pdf.org/repl) but with extra debugging tools.
 
You can see how the links are generated since the code is opensource for both tools.
react-pdf.org/repl = https://github.com/diegomura/react-pdf-site/blob/master/pages/repl.js
react-pdf-repl = https://github.com/jeetiss/react-pdf-repl


If you don't trust react-pdf-repl.vercel.app and you want a reproducable code using the repl tool of react-pdf.org then here you go [here](https://react-pdf.org/repl?code=1887b07602e07404e0a6073025819c27180280de0280013e019808602d9200d809e0173e011009201080b2f800a95c007be019449814f80208c12008c900630600680be143167d06002c204000e296807a4345c04145011a1210e545920ca19486914b2ba7af14c27e499b286006e008c004c86008a00ee00cc0072005a004a1000ea9c9100c200ae00126470006c00ec1000a2009a00aa4cbcb100d29a000c9c79c9009cf145959c00f200fa1d59002a006a286300520dbc23163a448ab800be009400dcb8db0e2210f8237068598ebae07090f800bcf8986bd7007cb7caf8003c002220b239859768d43c2bb61b0c433301c8543a231581c6e1f104be713f8e40c7c0ac560f179bd3824041c0544800179c0ae0c311141898c2352de63241c1a2549a732de875e3edfe80e06832002225c1e8610007029f064120c190601188174f4002b28a1c94100c034006210910c2525887514f81e0e830025d091644830021e8cd34462b12cc0109820098c1005260ce877330082608046305763b3d8457a18d910264b38c074d3e34c94157452d087c34555006b511112d7040eb2f81c8800249dcd32f3f9829158a2552995cbf08afc32b551aad4eaf506a37a060a6f36266d76f0cb3f0be9cf0743039a6472a201c837842a383e248f85b181a82a336c9f15238041a20bb010ff0c20009be07d23d0ca80b5c90496207ce279745e2c965a6b0aa5480556ac626bb5bafd5450ec4d0dd7b7c16d745c76f4fd11c433cca0c2123119a375dcd7c4f1731f0190103c4602c2773dc2e43c4f33c2f3ccaf42c815bccc07c057c18567cab37d650fc1b2fc9b5fc5b003db1dd3b6ec2d2b4fb482734217d7f560b1c7348cd268c0f261f07813c343971439d7c15533d93240204d08f7c10044b07c1b4e4cd30ccb3323d90a26f1e5ef32de88ac5f6ac58bad3f6fd9b7fcdb203789027b413c0fec44d13f4f1307378e0f64a0e0ce90640760c713c49960d3e6f97e30d704d9b6648e0734204e1de601600b98f0c1305790e6394e7392e4301e0ca800) (it also generates a long hash)

If you're still scared of the link here's a screenshot:
![image](https://github.com/IBM/plex/assets/97709651/0a2ad1be-b43d-4149-9e0b-292f509da9ce)


If you don't care about the code here's an annotated screenshot of the glyph issue visualized:
![image](https://github.com/IBM/plex/assets/97709651/0e566748-35e1-4c38-b113-0f3d5c92924d)

**Comment by TheMikeyRoss** [comment]
If you want to reproduce the issue live

## Option 1
go to https://react-pdf-repl.vercel.app/ and replace the default code with the one below
```jsx
import { Text, Page, View, Document, Font } from "@react-pdf/renderer";

Font.register({
  family: "IBM Plex Sans Arabic",
  src: "https://fonts.gstatic.com/s/ibmplexsansarabic/v12/Qw3NZRtWPQCuHme67tEYUIx3Kh0PHR9N6YPO_9CTVsVJKxTs.ttf",
});

export default () => (
  <Document style={{ fontFamily: "IBM Plex Sans Arabic" }}>
    <Page size="A6">
      <View>
           <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          قزيز
          فريق
        </Text>
        // The following works fine
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فر
        </Text>
        // You can see a tiny space between ف and ر
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فري
        </Text>
        // The space gets bigger between ف and ر
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فريق
        </Text>
        // When I replace the ز or ر with a ڑ it works fine
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
           فڑيق
        </Text>
      </View>
    </Page>
  </Document>
);
```

## Option 2
go to https://react-pdf.org/repl and replace the default code with the following:
```jsx
Font.register({
  family: "IBM Plex Sans Arabic",
  src: "https://fonts.gstatic.com/s/ibmplexsansarabic/v12/Qw3NZRtWPQCuHme67tEYUIx3Kh0PHR9N6YPO_9CTVsVJKxTs.ttf",
});


const TestComponent = () => (
   <Document style={{ fontFamily: "IBM Plex Sans Arabic" }}>
    <Page size="A6">
      <View>
           <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          قزيز
          فريق
        </Text>
        // The following works fine
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فر
        </Text>
        // You can see a tiny space between ف and ر
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فري
        </Text>
        // The space gets bigger between ف and ر
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
          فريق
        </Text>
        // When I replace the ز or ر with a ڑ it works fine
        <Text style={{ fontSize: 28, marginTop: 5, color: "#1f2b39", letterSpacing: 0 }}>
           فڑيق
        </Text>
      </View>
    </Page>
  </Document>
);

ReactPDF.render(<TestComponent />);

```

**Comment by BoldMonday** [comment]
I'm unable to replicate the issue, and I suspect the issue is caused by the layout engine in your environment.

I see strange things happening with the placement of marks in the examples above, for example.
Are you sure that all the OpenType features are applied correctly in this environment? 
Are you a native reader of the Arabic script?

When testing the same text in an environment that is guaranteed to use correct text shaping (Harfbuzz) and application of OpenType features I get the following (correct) results:

<img width="708" alt="image" src="https://github.com/IBM/plex/assets/13793769/5f171afa-fa18-4a37-a0d9-5c8e51e6476a">

Please note that you are using an older version (v1.2) of Plex Sans Arabic from Google fonts.
I advise to use the latest version from this repository and test again. If the problem persists I recommend to file an issue with the developer of react-pdf.

**Comment by BoldMonday** [comment]
Looking further into this I can confirm there is one missing kerning pair at the red marked glyph.
I will make a note about it for the next update.

<img width="952" alt="image" src="https://github.com/IBM/plex/assets/13793769/0cea9b97-2597-4ac4-a641-03d2a9b8b822">

**Comment by TheMikeyRoss** [comment]
> I advise to use the latest version from this repository and test again. If the problem persists I recommend to file an issue with the developer of react-pdf.

Oh ok , If I may ask how were you to check the version of the font?

I ran the following command to get the ttf:
```
curl "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic&family=Readex+Pro&display=swap"
```

and I got the following response:
```
@font-face {
  font-family: 'IBM Plex Sans Arabic';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/ibmplexsansarabic/v12/Qw3CZRtWPQCuHme67tEYUIx3Kh0PHR9N6bs6.ttf) format('truetype');
}
```

And when I use that ttf link to download the file and check the details of the file I see the following:
![image](https://github.com/IBM/plex/assets/97709651/fc01c2eb-68be-4b41-a122-a5b646e13cf6)

**Comment by TheMikeyRoss** [comment]
Finally I just verified that the issue is in fact not with IBM Plex Sans Arabic but actually in @react-pdf/renderer 

I used a different font "cairo" and the same spacing-between-glyphs issue happens 
![image](https://github.com/IBM/plex/assets/97709651/1274f188-7d69-4071-b2dc-4639f9c6d795)

I'm not sure if I should close this issue or if you want to keep it open for your comment [here](https://github.com/IBM/plex/issues/542#issuecomment-1778883042)

Thank you @BoldMonday

**Comment by BoldMonday** [comment]
File info is the correct way to check version number, and indeed these are v1.1 fonts.
I was looking at the Google fonts url and noticed a `/v12/` part which I wrongfully assumed was related to the version number.

**Comment by BoldMonday** [comment]
Let's keep the issue open until the missing kerning pair has been added.
