### ISSUE TITLE
ISSUES WITH ARABIC FONT - 1 LETTER

### ISSUE THREAD

**Issue by farahelmasri** [IBM/plex#550]
hello,

the arabic letter K needs to be adjusted to follow the same curve as L in red.

otherwise it looks like its a broken letter or the end of it is cut

![Kaf](https://github.com/IBM/plex/assets/154777706/4fa49362-36d4-40e7-9d49-820bef35ef7a)

can you please fix this?

**Comment by BoldMonday** [comment]
I'm not able to replicate this.

Can you post the Arabic text as selectable text?
That way it will be easy to copy and paste.

**Comment by BoldMonday** [comment]
Yes, I can see it now.

However, I the same difference can be observed in multiple other commercially available typefaces:
<img width="368" alt="image" src="https://github.com/IBM/plex/assets/13793769/794cf9fa-9f8e-4504-9214-ff76c03d3d79">
<img width="349" alt="image" src="https://github.com/IBM/plex/assets/13793769/5a5382a9-4e75-4c62-b876-3d0f8f447b74">
<img width="378" alt="image" src="https://github.com/IBM/plex/assets/13793769/db1b9ed7-6573-4b65-865d-a8f5912397d6">
<img width="341" alt="image" src="https://github.com/IBM/plex/assets/13793769/3f6e2e74-19d9-46f2-b249-91fa5d323186">

Therefore I conclude that this has been a deliberate stylistic choice by the designers of Plex Sans Arabic.

**Comment by farahelmasri** [comment]
would you be able to recommend other fonts that dont have this stylistic choice?

**Comment by BoldMonday** [comment]
That is beyond my expertise I’m afraid.
