### ISSUE TITLE
Strange placement of the "tonos" above lowercase Greek eta in the Serif variant

### ISSUE THREAD

**Issue by sykde** [IBM/plex#551]
In IBM Plex Serif, various diacritical marks above the lowercase Greek eta are placed unnaturally far to the left. Specifically, this problem seems to affect:
- Greek lowercase letter eta with tonos (```U+03AE```, ```ή```)
- Greek lowercase letter and eta (```U+03B7```, ```η```) with combining diacritical marks (e.g. ```U+0300, U+0301, U+0303```)

This might have been intentional, as the tonos is also slightly offset to the left in the letter alpha tonos (```U+03AC```, ```ά```), but unlike alpha tonos, in the case of eta tonos this feature is not persistent across other IBM Plex typefaces. _Personal bias: It also looks strange..._
![image](https://github.com/IBM/plex/assets/76517722/8689a239-eac2-4372-bd6a-0dc84bacb093)

In IBM Plex Sans, the tonos in eta tonos appears in the "normal" spot, near the middle of the letter's width.
![image](https://github.com/IBM/plex/assets/76517722/6dbb2765-56c2-4c02-a036-fe95a6661027)

The fonts affected seem to be all the variants of IBM Plex Serif. For the tests, only TTF files were used: ```IBMPlexSerif-*.ttf``` (Version 3.0.0, sfnt Revision 3, Release v6.3.0).
All tests were done in Windows 10/11, in Microsoft Word (Verson 2311, Build 17029.20068) and in FontForge (20230101).

**Comment by BoldMonday** [comment]
The placement of tonos to the left on eta in Plex Serif is intentional, and was advised by Irene Vlachou who consulted on the Greek design. Granted, Plex Sans has a slightly different approach. We might fix that in a future update.

Occassions where `eta` will be combined with Latin diacritics such as `U+0303` are unknown to us, and therefore not considered.

**Comment by sykde** [comment]
Since this was confirmed to be an intentional feature, I will be closing the issue. Thanks for the clarification!
