### ISSUE TITLE
Put latest version of Plex Sans Condensed (v1.4) in repo

### ISSUE THREAD

**Issue by BoldMonday** [IBM/plex#557]
@stephharrington1 @Dan-Pastrolin-IBM @leonardo-costa-IBM @Lingaraj-13 @Palke

Contrary to the release notes of https://github.com/IBM/plex/releases/tag/v6.1.0 (August 2022) this repository still contains v1.3 of Plex Sans Condensed.

**Comment by mjabbink** [comment]
@stephharrington1 @Dan-Pastrolin-IBM @leonardo-costa-IBM @Lingaraj-13 @Palke 
Condensed is used in Carbon charts so this should be addresses as soon as possible.

FYI @tay1orjones @jeffchew

**Comment by BoldMonday** [comment]
Fixed with https://github.com/IBM/plex/releases/tag/v6.4.0
