### ISSUE TITLE
The character  “↳” (U+21B3) is not present in Google Fonts' IBM Plex Mono Regular

### ISSUE THREAD

**Issue by kauesena** [IBM/plex#572]
When the font family IBM Plex Mono is imported from Google Fonts, the character `↳` (U+21B3) is available in every face **but** in the regular one. You can see this by inserting it in the preview text field. The following link should work to see that.
https://fonts.google.com/specimen/IBM+Plex+Mono?preview.text=%E2%86%B3
![image](https://github.com/IBM/plex/assets/30255100/9c39f3db-3dff-406d-8e69-e4d76e423ffe)

**Comment by BoldMonday** [comment]
We always recommend to use the IBM Plex Mono fonts from the [releases](https://github.com/IBM/plex/releases) of this repository. These fonts do contain the symbol in question.

We have no control over copies of IBM Plex from other sources unfortunately.
You might consider filing an issue at https://github.com/google/fonts.
