### ISSUE TITLE
Modifier letter apostrophe is hard to see

### ISSUE THREAD

**Issue by flashymittens** [IBM/plex#575]
ʼ U+02BC Modifier letter apostrophe, IMO, is hard to see, unlike, say, right single quotation mark.

![An example](https://github.com/IBM/plex/assets/120594150/99a9612c-f630-4dcf-88e8-0559bf019fc4)

In the picture above are used:

1. U+0027 apostrophe.
2. U+2019 right single quotation mark.
3. U+02BC modifier letter apostrophe (once at the end of a word and once again inside of a word).

Noto fonts are used for comparison, although I think those simply use the same glyph as a right single quotation mark, which is probably fine, but I’m not an expert on that.

Would be nice to have the character more readable, if possible.

**Comment by BoldMonday** [comment]
The glyph in question is used as the diacritic in glyphs `dcaron` `lcaron` `tcaron` and `Lcaron`.
AFAIK that’s the main purpose and in that context the weight and proportions are correct.

<img width="1169" alt="image" src="https://github.com/IBM/plex/assets/13793769/2a1b6e0f-38be-4d48-bd60-3af7593ec9c0">

**Comment by BoldMonday** [comment]
Check the unicode block in question and you will see that many modifier letters are diacritics. For example there is U+02CA MODIFIER LETTER ACUTE ACCENT. Yes, they can be typed on their own and have their own spacing. But in many fonts their purpose is to act as building blocks for accented glyphs. Certainly that is the whole purpose of the glyph in question in IBM Plex.

**Comment by BoldMonday** [comment]
We are talking about two different things here. :)

It is not about **typing** the character in question as a font user. (Because that is what combining diacritics are for.)
It is about using the shape of the character in question as a **reusable element** when creating accented characters as a font designer.
