### ISSUE TITLE
The contour problem of Sans TC: 经 U+7ECF

### ISSUE THREAD

**Issue by Des-Magmeta** [IBM/plex#576]
As the title mentioned, there's a contour problem of "丶" in the character 经(U+7ECF).

Try to upload a screenshot:
![Screenshot_20240608_180455.jpg](https://github.com/IBM/plex/assets/125174106/93a69aaf-3628-4dce-a17c-b55198c96bbf)

**Comment by lxgw** [comment]
Perhaps it's just a design feature of this font. See "ㅈ" and "ㅅ" in IBM Plex Sans KR.

**Comment by mjabbink** [comment]
That is an intentional detail. Similar to the detail in Korean as well.


<img width="1365" alt="Screenshot 2024-06-11 at 5 39 32 PM" src="https://github.com/IBM/plex/assets/32881239/1232dd49-5c04-4826-a9eb-f52519f6cb6c">
