### ISSUE TITLE
Character U+71F9 燹 has shapeshifters

### ISSUE THREAD

**Issue by Aaron-212** [IBM/plex#580]
Issue shown in the following image.
<img width="724" alt="image" src="https://github.com/IBM/plex/assets/38318044/04be3313-fa25-421b-ae5c-895729da2e2b">

I'm using IBM Plex Sans JP 6.4.1

**Comment by Sandoll-DS** [comment]
We have identified this issue you raised, and it will be fixed in the next update.
<img width="1062" alt="fixed-U+71F9" src="https://github.com/user-attachments/assets/41428b4e-0409-492e-9dcd-6b9a6488f318">
