### ISSUE TITLE
Update Plex repo Read me text

### ISSUE THREAD

**Issue by mjabbink** [IBM/plex#584]
https://github.com/IBM/plex

When we release Plex Chinese TC and Plex Math, please update the **Read Me** text in the copy below.

—————

Meet the IBM Plex® typeface, our corporate typeface family. It’s global, it’s versatile and it’s distinctly IBM.

We designed the IBM Plex typeface carefully to meet our needs as a global tech company and express who we are as IBMers. It took two years and a lot of work to get here, but today, we have a signature typeface we’re proud of and excited to share with the world. Discover more about our development of the [IBM Plex typeface](https://www.ibm.com/plex/).

The IBM Plex typeface is an open-source project available for download and various uses following the Open Font License (OFL). The IBM Plex family comes in Sans, Serif, Mono, and Sans Condensed, all with Roman and true italics. Plex has been designed to work well in user interface (UI) environments and other mediums. This project provides all source files and multiple formats to support most typographical situations. Currently, IBM Plex Sans supports extended Latin, Arabic, Chinese (Traditional), Cyrillic, Devanagari, Greek, Hebrew, Japanese, Korean, and Thai. The Chinese SC (Simplified) version will be available in Q4 2024.

Additionally, we have introduced IBM Plex® Math. This highly anticipated release includes over 5,000 new glyphs, covering a wide range of mathematical symbols such as alphanumeric, double-struck, Fraktur, operators, script, icons, arrows, Greek letters, phonetics, technical and geometric shapes — making it one of the most complete math fonts available today. IBM Plex Math provides a fresh and comprehensive alternative to STIX and Microsoft’s Cambria. Its compatibility with IBM Plex Serif Regular makes it an ideal choice for IBM researchers and mathematicians.

We hope you enjoy using the IBM Plex typeface!

**Comment by BoldMonday** [comment]
> > Additionally, we have introduced IBM Plex® Math. This highly anticipated release includes over **6,000** new glyphs, 

Missing one zero. ;)

**Comment by mjabbink** [comment]
Good catch @BoldMonday I fixed that detail in the copy above

**Comment by mjabbink** [comment]
@Lingaraj-13 As soon as Plex TC and Math are published to the repo that can be updated. Cheers.

**Comment by mjabbink** [comment]
updated to **5,000 new glyphs**

**Comment by mjabbink** [comment]
@Lingaraj-13 I found a typo in my text, so I updated it again. I think it’s good to go now.

**Comment by Palke** [comment]
@mjabbink hi Mike, I have updated the copy in my PR: https://github.com/IBM/plex/pull/589/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by mattrosno** [comment]
Just an FYI @Palke, the main readme table doesn't include a link to the variable font. Is that intentional?

**Comment by Palke** [comment]
@mattrosno not really, good catch. I will update it. Thanks!
