### ISSUE TITLE
Unwanted `.DS_Store` in the release files.

### ISSUE THREAD

**Issue by BobH-Official** [IBM/plex#593]
It has unwanted `.DS_Store` in the release files.

![圖片](https://github.com/user-attachments/assets/e54d3659-4d58-49ac-89a5-b4a4e27cb4a7)

Should it be removed next time?

(As far as I know, a tool called [Keka](/www.keka.io) could zip folders without `.DS_Store`.)

**Comment by mrfragger** [comment]
> (As far as I know, a tool called [Keka](/www.keka.io) could zip folders without `.DS_Store`.)

zip -r somedir.zip . -x "*.DS_Store"
