### ISSUE TITLE
Request to implement ffi and ffl ligatures

### ISSUE THREAD

**Issue by teddympq** [IBM/plex#611]
A humble request to add ffi and ffl ligatures 🙏 (and possibly ff and ft too, especially for words like fifth, fifteen)
![image](https://github.com/user-attachments/assets/d2fdf5b6-0691-401d-9665-72a0575eb948)

**Comment by BoldMonday** [comment]
Plex Serif has been designed in such a way that ligatures are not needed. But the `fi` and `fl` ligatures are included for reasons of compatibility with legacy character set encodings (“Macintosh Roman”, to be precise).
We do not intend to include any additional ligatures.

I agree that the example above does not look pretty and there is a small bug in the current fonts that automatically activates these `fi` and `fl` ligatures. We will disable that feature in a future update.

<img width="689" alt="image" src="https://github.com/user-attachments/assets/31508c4b-2f12-47d2-8e1e-55e78363f5e6">
