### ISSUE TITLE
Sans SC hinted doesn't read well on low DPI screen

### ISSUE THREAD

**Issue by sommio** [IBM/plex#617]
- freetype2 2.13.3

The strokes on the IBM Plex Sans SC look too thin, I wish it was a little more crisp and sharp

IBM Plex Sans SC (hinted)
![截图 2024-12-07 06-56-56](https://github.com/user-attachments/assets/6fb8ff3b-396d-4c71-be6b-d12824718e5e)
Sarasa Gothic SC (same size&style)
![截图 2024-12-07 06-57-42](https://github.com/user-attachments/assets/49dc21de-9fd3-4b8d-a18f-4c98583bd184)

**Comment by BoldMonday** [comment]
1. Freetype ignores all hinting information within a font so there is no reason to expect a better rendering than the unhinted version. Perhaps it might render the OTF version better. It is hard to predict and I advise you to try.
2. Plex has a large range of weights. If Regular looks too light then use one of the heavier weights, such as Text.

**Comment by sommio** [comment]
> Freetype ignores all hinting information within a font so there is no reason to expect a better rendering than the unhinted version.

I have read that [freetype2's hinting is cleartype-like](https://freetype.org/freetype2/docs/hinting/subpixel-hinting.html), and I use full-hinting, which I assume doesn't ignore native hinter

**Comment by BoldMonday** [comment]
No, it means that Freetype is autohinting the font itself.
You should get the same visual results when using the unhinted Plex Sans SC fonts.

**Comment by sommio** [comment]
TrueType doesn't look any different but readability is still better than OpenType.
Regular weight looks too thin, Text weight is closer to other Chinese fonts.
Maybe it's a good idea to replace the Regular weight with Text.

I used IBM Plex's Regular and Text weight in the image below,
sorry I forgot to label weight.

![1](https://github.com/user-attachments/assets/1857ed15-1081-4e15-bf49-721ee233100a)
![2](https://github.com/user-attachments/assets/19f868ec-175e-4061-89ac-e6cbe43f5242)
![3](https://github.com/user-attachments/assets/455a87ec-f641-4755-a580-8ee47185d533)
![4](https://github.com/user-attachments/assets/2d43355b-24fd-4331-803b-d065127962bb)

**Comment by BoldMonday** [comment]
Thanks for the overview.

The weight of the characters has been deliberately designed to match with all other scripts in Plex Sans: Latin, Greek, Cyrillic, Hebrew, Arabic, Devanagari, Thai, Hangul and Japanese. Changing weights is out of the question I'm afraid.

**Comment by khaledhosny** [comment]
> No, it means that Freetype is autohinting the font itself.

FreeType is highly configurable, and different systems can configure it differently. It supports native hinting as well as autohinting, so it can give really different results depending on how it is configured.
