### ISSUE TITLE
Issues and Recommendations for Sans TC

### ISSUE THREAD

**Issue by areeqa68** [IBM/plex#620]
Thank you for providing the TC community with such a great font! However, there are some significant issues and some personal suggestions that I hope Plex can resolve in the next release.

It seems that the character set of this font is based on Adobe-CNS1-7, so the CIDs are included for reference.

### Other miscellaneous not unified components [fixed in 1.1.0]

**Comment by BoldMonday** [comment]
Duplicate of https://github.com/IBM/plex/issues/556
