### ISSUE TITLE
Source files #609 #623

### ISSUE THREAD

**Issue by mamtaRaiTech** [IBM/plex#626]
Thank you for reaching out. Earlier this year, the source files (ufo, glyphs, etc.) were indeed removed from the repository due to file size concerns (#452, #554, #560). While it was suggested that these files would be made available as release artifacts or assets, it appears that this has not yet been implemented.

As for your question about future plans, I recommend checking the repository’s release section regularly for updates. You can also keep an eye on the project’s issues or discussions for any announcements regarding the reintroduction of the source files.

If you have further questions, don’t hesitate to ask.

**Comment by BoldMonday** [comment]
Duplicate of https://github.com/IBM/plex/issues/609
