### ISSUE TITLE
Context via comparision

### ISSUE THREAD

**Issue by ftrotter** [IBM/plex#64]
I am "design sensitive" I know what an impact good design can have, and I can tell when design elements are working and "telling me the same message" about a website or thing. But I am not a designer. 

For to understand your contribution and the appeal of the choices in your font, I really need to see them side-by-side with their competitors. 

You specifically mention Helvetica, but I think noto from Google is an obvious other reference. Noto solves a significant problem for me as a software developer, and I would hope that Plex would eventually do the same thing. (i.e. no tofu due to unicode.)

I would recomment that you have a page, linked to from your home page, that shows side by side comparisons between you, noto and Helvetica. 

I would think that css in a very simplified manner to simply illustrate very big font sizes for h1/h2/.../p would make for a very compelling differentiator page. 

Without that, it is really difficult for me to clearly interpret what the difference is here, and I think there are thousands of us "design senstive" types out there for every one web designer who is capable of just looking at a single webpage example of your work without comparision to anything. 

This might already exist. And if it does, then it should be made front and center.

Regards,
-FT

**Comment by seejamescode** [comment]
As mentioned at the bottom of [this article,](https://qz.com/1124664/ibm-plex-with-its-first-ever-custom-corporate-font-ibm-is-freeing-itself-from-the-tyranny-of-helvetica/) IBM Plex will be shipped to Google Fonts soon. This will allow you to compare with their catalog!

**Comment by mjabbink** [comment]
@ftrotter There will be a Plex website in end of February which will allow you to fully explore Plex.
