### ISSUE TITLE
Plex Mono l and 1 to similar 

### ISSUE THREAD

**Issue by kmf** [IBM/plex#66]
Not sure if it could be refined

![2017-11-10-07 22 51](https://user-images.githubusercontent.com/78700/32644083-15d57bb6-c5e8-11e7-9587-b66b2d57e7cd.png)

**Comment by seejamescode** [comment]
@mjabbink and @BoldMonday, thoughts?

**Comment by mjabbink** [comment]
This has come up before. We will discuss and resolve.

**Comment by seejamescode** [comment]
<img width="430" alt="screen shot 2018-02-21 at 1 57 48 pm" src="https://user-images.githubusercontent.com/7519029/36502336-3bca0490-170f-11e8-8890-b7e48caaedd2.png">
Looks like we adjusted the heights for more differentiation!

**Comment by kmf** [comment]
@seejamescode thanks.

**Comment by mjabbink** [comment]
Actually @seejamescode and @kmf that is the original. Here is the adjusted "one" compared to Mono letter "l" (el). In the Sans it’s a non issues given the letter "l" has not slabs serifs.
<img width="1117" alt="screen shot 2018-02-21 at 8 01 48 pm" src="https://user-images.githubusercontent.com/32881239/36514465-835cb626-1742-11e8-8e9d-1dc8071ae28e.png">
<img width="1117" alt="screen shot 2018-02-21 at 8 01 48 pm" src="https://user-images.githubusercontent.com/32881239/36514466-84c5e0aa-1742-11e8-91b8-cdda7c1306c4.png">

**Comment by mjabbink** [comment]
Actually @seejamescode and @kmf that is the original. Here is the adjusted "one" compared to Mono letter "l" (el). In the Sans it’s a non issues given the letter "l" has not slabs serifs.
<img width="1117" alt="screen shot 2018-02-21 at 8 01 48 pm" src="https://user-images.githubusercontent.com/32881239/36514497-a438cda8-1742-11e8-830e-b9cce8597a48.png">

**Comment by mjabbink** [comment]
The angle on "1" is steeper and the top was pulled over to create a flat top and a thinner joint which makes for a more distinguished "1"
