### ISSUE TITLE
IBM Plex editable sources? 

### ISSUE THREAD

**Issue by twardoch** [IBM/plex#68]
The IBM Plex is a very fine accomplishment. However, its language coverage is currently limited. 

Currently, the opensourced fonts are published only in compiled form, usable only by end-users but not by other developers. 

Do you plan to publish editable sources which would allow the community to enhance the fonts, e.g. by contributing additional glyphs, width variation or other enhancements?

**Comment by BoldMonday** [comment]
Yes, editable source files will be published soon.

**Comment by davelab6** [comment]
It would be helpful to know what the roadmap is too, since I saw an issue comment here that Cyrillic will arrive soon, and it may be wasted effort for say Bulgarian designers that Adam knows to start on Cyrillics when they will soon arrive anyways :)

**Comment by twardoch** [comment]
I’d like to applaud the Serif version of IBM Plex. It doesn't get featured widely in the materials bit it is a superbly designed text face for on-screen continuous reading. 

IBM Plex Serif is subtly retro, echoing Fleischmann along with great ball terminals, but manages to not appear dated. It's a very rare quality these days. It's so refreshing to see a new serif design that doesn't “try hard to look modern” and at the same time doesn't follow the ubiquitous “humanist calligraphic thing” that I abhor.

**Comment by twardoch** [comment]
Great news that sources will be published. And yeah, I won't be surprised if not just two but three or four different Cyrillic versions emerge. :D

**Comment by twardoch** [comment]
...perhaps less Fleischmann but more the Century/Excelsior genre — but done right. Not in a decorative “look! ball terminals! pretty” fashion, but very much to the purpose of providing superb legibility.

**Comment by BoldMonday** [comment]
Re: Cyrillic – we are hard at work adding Cyrillic to all fonts, and they are scheduled to be finished in January.

**Comment by mjabbink** [comment]
Early 2018 will kick-off Arabic, Greek, Hebrew, Hindi and Thai. CJK will kick off middle of 2018.

**Comment by mjabbink** [comment]
and thank you @twardoch!

**Comment by chengluyu** [comment]
@mjabbink Really? CJK characters will be included in a future update? I'm very happy to hear that.

**Comment by soviet-man** [comment]
I'm looking forward to support of Cyrillic.

**Comment by inferno986return** [comment]
It's a beautiful typeface family, I use it on my Chrome browser setup as the sole font family. My only real complaint is the lack of non-Latin support so it's great to see that you are (hopefully) working towards making this font family as complete as Adobe's Source fonts. :-)

**Comment by mjabbink** [comment]
@inferno986return Cyrillic here! Will be available here in the the next week or two. We also have Arabic, Devanagari, Greek, Hebrew, Thai, Hangul coming this year. Stay tuned. Chinese and Japanese will be 2019 as they take a long time to create.

**Comment by soviet-man** [comment]
Could you paste here some hi-res screenshots of cyrillic texts?

**Comment by seejamescode** [comment]
🎉 Editable sources included in v1.0.0!

**Comment by OrthoCube** [comment]
Looking forward to Japanese support! Currently, the M+ family of fonts are the best for me, but who knows, Japanese Plex might be more ＡＥＳＴＨＥＴＩＣ  :D
