### ISSUE TITLE
Additional characters and diacritics

### ISSUE THREAD

**Issue by rfpng** [IBM/plex#84]
Thanks for this font family! It would be great if the following characters and diacritics could be added for a language I'm working with:
→ U+0268 LATIN SMALL LETTER I WITH STROKE: ɨ
→ U+0197 LATIN CAPITAL LETTER I WITH STROKE: Ɨ
(Diacritics like U+0300 COMBINING GRAVE ACCENT, U+0301 COMBINING ACUTE ACCENT, U+0302 COMBINING CIRCUMFLEX ACCENT and U+0304 COMBINING MACRON should then also be rendered correctly on this barred i)
→ U+1DC4 COMBINING MACRON-ACUTE: e.g. a᷄
→ Diacritics should also be rendered correctly on the digits 0-9. This is needed to mark grammatical tone in some tone languages.
→ U+A789 MODIFIER LETTER COLON: ꞉
Thanks for considering this!

**Comment by BoldMonday** [comment]
Out of curiousity: what languages does this concern?

**Comment by rfpng** [comment]
These are languages in Papua New Guinea.

**Comment by BoldMonday** [comment]
Thanks. We’ll take it into consideration.

**Comment by mjabbink** [comment]
@BoldMonday did this get into v2? If not let’s consider for next rev.

**Comment by BoldMonday** [comment]
Not included in V02. For a future update then.

**Comment by mjabbink** [comment]
@BoldMonday should we consider for a v4?

**Comment by rfpng** [comment]
That would be wonderful!

**Comment by AlsoScratch** [comment]
On the topic of additional characters, I would also like to see the letters Ṅṅ, Ṣṣ (the letters in Igbo and Yoruba).

**Comment by AlsoScratch** [comment]
It would also be nice to add the following:

- first half of Latin Extended Additional (u+1e00 through u+1e95)
- Ǧ (u+01e6) and ǧ (u+0137)
- u+2010 through u+2015

**Comment by BoldMonday** [comment]
A new update for Plex Sans has been sent to IBM last week. It includes, among other things, the missing pinyin characters and mark support for accented glyphs such as `aogonek`.

The other glyphs mentioned in this thread have not been added and I cannot give a timeline.

**Comment by tay1orjones** [comment]
Hey there! [v6.1.0](https://github.com/IBM/plex/releases/tag/v6.1.0) was just released that references this issue. 

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/468) to provide feedback or voice concerns. Thanks!

**Comment by tay1orjones** [comment]
Hey there! [v6.3.0](https://github.com/IBM/plex/releases/tag/v6.3.0) was just released that references this issue.

Comment here or join the [release discussion](https://github.com/IBM/plex/discussions/520) to provide feedback or voice concerns. Thanks!
