### ISSUE TITLE
Font PostScript names are inconsistent with naming convention

### ISSUE THREAD

**Issue by Down10** [IBM/plex#88]
The PostScript names of each OpenType and TrueType font are not entirely consistent amongst each other, leading to conflicts.

For instance:
* PostScript name of `IBMPlexSerif-Regular.otf` is "IBMPlexSerif"
* PostScript name of `IBMPlexSerif-Regular.ttf` is "IBMPlexSerif"
* PostScript name of `IBMPlexSerif-ExtraLight.otf` is "IBMPlexSerif-ExtraLight"
* PostScript name of `IBMPlexSerif-ExtraLight.ttf` is "IBMPlexSerif-ExtraLight"
* PostScript name of `IBMPlexSerif-ExtraLightItalic.otf` is "IBMPlexSerif-ExtraLightItalicPS"
* PostScript name of `IBMPlexSerif-ExtraLightItalic.ttf` is "IBMPlexSerif-ExtraLightItalic"

Note the "PS" at the end of the name of Extra Light Italic. This is mostly found within the Plex Serif family.

The result of this inconsistent naming is that Font Book on MacOS will register the OTF and TTF fonts as different and unique faces, rather than as duplicate fonts, leading to both being activated.

P.S.: I'm not quite sure why OTF fonts are filed as "mac" and TTF fonts are filed as "pc", as both file types are platform-independent and haven't been unique to a single operating system since the mid-1990s. Why not name the folders "otf" and "ttf"?

**Comment by BoldMonday** [comment]
The PS extension in certain naming fields is definitely a bug, and will be fixed in the next update.

Thanks for reporting!

**Comment by seejamescode** [comment]
Hey @BoldMonday, did we resolve this?

**Comment by BoldMonday** [comment]
@seejamescode Yes. This is resolved.

**Comment by seejamescode** [comment]
🎉
